[[entries]]
id = 100
query = "field=0_y.....y.....y.....p.p..ypyyy.&steps=yp&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "初級 第1問"

[[entries]]
id = 101
query = "field=0_r.rr..r.gr.rorgg&steps=rg&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "初級 第2問"

[[entries]]
id = 102
query = "field=0_g.....g....gyy...ggy.&steps=ggyg&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "初級 第3問"

[[entries]]
id = 103
query = "field=0_r.brrrbrr&steps=rbrb&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "初級 第4問"

[[entries]]
id = 104
query = "field=0_b.pp..bbobbb&steps=bpbp&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "初級 第5問"

[[entries]]
id = 105
query = "field=0_oo....bo....bb....oo.bobbbob&steps=bbbb&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第1問"

[[entries]]
id = 106
query = "field=0_r..r..r.or..roor..yyoo.&steps=ryry&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第2問"

[[entries]]
id = 107
query = "field=0_bb....bo...yoby.yybbyy&steps=byby&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第3問"

[[entries]]
id = 108
query = "field=0_rr..ggoo..rgrog.rrogg&steps=rgrg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第4問"

[[entries]]
id = 109
query = "field=0_bb...ggoo..gobo..boog..bbgg.&steps=bgbg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第5問"

[[entries]]
id = 110
query = "field=0_p.....py....yy....pppyyyoyo&steps=pppy&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第6問"

[[entries]]
id = 111
query = "field=0_r.....y....yo...rryr..ryoyyy&steps=rrry&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第7問"

[[entries]]
id = 112
query = "field=0_b....gg....bo...gbb.bbgoo.gg&steps=bgbg&goal=_0"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第8問"

[[entries]]
id = 113
query = "field=0_r.....rb....oboobb&steps=rbbbrb&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第9問"

[[entries]]
id = 114
query = "field=0_orb...rbbr..yyrr.&steps=ryrbry&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第10問"

[[entries]]
id = 115
query = "field=0_g.....g.....g.....o.....g....gp.&steps=gpgpgp&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第11問"

[[entries]]
id = 116
query = "field=0_b....gb.g.bggogbb&steps=gbbggb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第12問"

[[entries]]
id = 117
query = "field=0_g.....p.g...g.p...o.o..ggppp&steps=pgpgpg&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第13問"

[[entries]]
id = 118
query = "field=0_o.....brb...bbrb..rrbb.&steps=rbbbbb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第14問"

[[entries]]
id = 119
query = "field=0_b.....p.....rr....rb....pp....bb....rp..pppbrr&steps=bprbrb&goal=0_0_6_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第15問"

[[entries]]
id = 120
query = "field=0_rrb..brob..booo.bbrrrbb&steps=rbbbrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第16問"

[[entries]]
id = 121
query = "field=0_y.....b.....b.....by....yy...ggb...grby..rrby.&steps=rgybby&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第17問"

[[entries]]
id = 122
query = "field=0_yy.oggggygyy&steps=ggyygy&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第18問"

[[entries]]
id = 123
query = "field=0_p.....b.....pp....bp....bb..b.or..bbopp.&steps=rprrbp&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第19問"

[[entries]]
id = 124
query = "field=0_bbb..rroor.roorr.obbbo.yyooy.yooyy.&steps=yrbyrb&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第20問"

[[entries]]
id = 125
query = "field=0_bbr...brb..ggrbg.gbbgg.&steps=bgrbbbgb&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第21問"

[[entries]]
id = 126
query = "field=0_o.....b.....gbb..rrbg..rbgg..bbrr.&steps=ggbgrrrg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第22問"

[[entries]]
id = 127
query = "field=0_b.....y.....bb....bg....og....bb....bo..b.ob..bbobob&steps=gybybgyb&goal=0_0_6_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第23問"

[[entries]]
id = 128
query = "field=0_b.....oo...rro..gbgbb.ggogb.&steps=bbggrrbg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第24問"

[[entries]]
id = 129
query = "field=0_o.....y.o...y.b...o.r...o.ry..o.yy.&steps=ybybrbry&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第25問"

[[entries]]
id = 130
query = "field=0_y.....b....by....ggbb..gryy..rrby.&steps=byrybybg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第26問"

[[entries]]
id = 131
query = "field=0_g..p.pp.gg.op.op.og.op.pppggg&steps=gpgpgpgp&goal=2_4_11_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第27問"

[[entries]]
id = 132
query = "field=0_b.....o....gb...ggbrrrrorr&steps=rbbbgbrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第28問"

[[entries]]
id = 133
query = "field=0_r.....r...g.g..bggog.bbogg.&steps=bbbrbrgb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第29問"

[[entries]]
id = 134
query = "field=0_o....or....rg...ggrg..rrog.&steps=gggrgggrgr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第30問"

[[entries]]
id = 135
query = "field=0_b.....b.....oo...rro...brbb..boob.&steps=rrbrbrbbrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第31問"

[[entries]]
id = 136
query = "field=0_o..o..rrgg..orgb..obbg..rrrb.&steps=bbggrrbggb&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第32問"

[[entries]]
id = 137
query = "field=0_r.o..gggg..bgbbr.rrbyrrbrgyybbygbrggggybybybyybyybggybb&steps=yyggyybgyg&goal=0_0_13_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第33問"

[[entries]]
id = 138
query = "field=0_r.....r.....g.g..bb.r.rggrg.rrbbbg&steps=bgbrrrrgbr&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第34問"

[[entries]]
id = 139
query = "field=0_og....bg....bg....br....gr....gb....rb....rb....ro..&steps=rbgbrgbbbrgb&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第35問"

[[entries]]
id = 140
query = "field=0_rr....gybgggyybbrrrg&steps=yryyggbryygr&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第36問"

[[entries]]
id = 141
query = "field=0_b...obgg..rrgo.ggbbb.grorr.&steps=bgrgbgrgbgrg&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第37問"

[[entries]]
id = 142
query = "field=0_brrggybbrgyyrrgrggyygrbbgygrbrgbbyyrgbybyrrrrggg&steps=ryrbrbygygbg&goal=_0"
title = "イグアス"
creators = "π"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第38問"

[[entries]]
id = 143
query = "field=0_bbrooobrroooyygoooyggyggbbryygbrrooo&steps=brgybrgybrgybr&goal=_0"
creators = "aojil"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第39問"

[[entries]]
id = 144
query = "field=0_r.y.r.y.r.y.y.r.b.b.b.b.r.y.y.y.b.y.y.r.r.r.b.b.b.y.r.b.r.b&steps=byyrbyrbyrrbbyrb&goal=_0"
title = "トライデント"
creators = ["π", "OrangeP"]
source = "早大なぞぷよマスターズ2019"
sourceDetail = "第40問"

[[entries]]
id = 145
query = "field=0_g.b.r.b.b.r.r.g.b.r.g.g.b.r.g.g.b.r.g.r.g.r.r.b.r.b.b.b.g.r.b.g.g&steps=brbgrgrbgbrbrgrgbg&goal=0_0_10_1_0"
title = "トリシューラ"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2019"
sourceDetail = "おまけ問題"
