[[entries]]
id = 146
query = "field=0_g...g.g...g.g...o.p...gpg...gpg.&steps=pggg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第1問"

[[entries]]
id = 147
query = "field=0_o....pp....op...ppbp..popp.&steps=bppbpb&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第2問"

[[entries]]
id = 148
query = "field=0_opp..prpr..pprr.&steps=prrrpr&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第3問"

[[entries]]
id = 149
query = "field=0_g.....r.....r..gror..rrgg.&steps=gggrgr&goal=0_0_4_0_"
creators = ["Pon!通", "π"]
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第4問"

[[entries]]
id = 150
query = "field=0_g.g...g.g...g.y..&steps=gyyggy&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第5問"

[[entries]]
id = 151
query = "field=0_r.....g.....g.o...r.g...oog..&steps=rggggr&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第6問"

[[entries]]
id = 152
query = "field=0_gy....yy....gg....gy....yg..&steps=gyyggy&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第7問"

[[entries]]
id = 153
query = "field=0_g.....rr.g..robb..gogb..ggogg&steps=gbgggr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第8問"

[[entries]]
id = 154
query = "field=0_g..r..r..rbbr..rogo.gggogg&steps=brgrbr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第9問"

[[entries]]
id = 155
query = "field=0_g....ob....bb....oggg..rrrb..gobb.&steps=rgbgbg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第10問"

[[entries]]
id = 156
query = "field=0_r....bry..bbobyyyyybbo&steps=rybryb&goal=0_0_5_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第11問"

[[entries]]
id = 157
query = "field=0_y.....y.....o.....bb....ob....bo....bb...yypp..yboo.&steps=pypyby&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第12問"

[[entries]]
id = 158
query = "field=0_g.....o.r...orr.orggy.yrryy.yyoggg&steps=rggyyr&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第13問"

[[entries]]
id = 159
query = "field=0_y..pp.oy.pbboopbyyypp&steps=ybypyp&goal=0_0_5_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第14問"

[[entries]]
id = 160
query = "field=0_g....bo...ggg..rrbbb.roorrr&steps=brbbbr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第15問"

[[entries]]
id = 161
query = "field=0_b.....b....yy....yb..r.bbr.rroorr&steps=brbybr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第16問"

[[entries]]
id = 162
query = "field=0_bbbrbbrbrbrrorrooborbrobrbbbrrbb&steps=rbrbbr&goal=0_0_6_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第17問"

[[entries]]
id = 163
query = "field=0_b.....oo...ooo..rgogg.oggog&steps=gbrbrbrg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第18問"

[[entries]]
id = 164
query = "field=0_bbb...rro.bbgoo.bgogg.&steps=gggbgrbr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第19問"

[[entries]]
id = 165
query = "field=0_b....yb....oo..ggoo..ogoo.bbbyyy&steps=yybbyygb&goal=0_0_5_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第20問"

[[entries]]
id = 166
query = "field=0_o.....r....rr.b..oogg..gorg..grrb..gobb.&steps=brbgbgbr&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第21問"

[[entries]]
id = 167
query = "field=0_y.....o.....gy....ggo.y.yoy.yyoggg&steps=gyyyrygy&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第22問"

[[entries]]
id = 168
query = "field=0_r....oo....ry.r.yro.r.yyoyyr&steps=rppypryp&goal=0_0_5_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第23問"

[[entries]]
id = 169
query = "field=0_o.....yyy...boo..bbgo.yoggoyy&steps=bbgybbyb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第24問"

[[entries]]
id = 170
query = "field=0_g....gg...bbyy.ygggb.yyoobb&steps=ybgbgyby&goal=0_0_6_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第25問"

[[entries]]
id = 171
query = "field=0_ro....gg....bo..rggg..rrbbboooorrr&steps=gbrbgbgb&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第26問"

[[entries]]
id = 172
query = "field=0_r.....o.g...ygo..yyooy.gggoyy&steps=ggrryrgy&goal=0_0_5_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第27問"

[[entries]]
id = 173
query = "field=0_r.....rr...byb...yyo..rrbo.yyryb.yboyy.&steps=byybrbyr&goal=0_0_6_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第28問"

[[entries]]
id = 174
query = "field=0_o.....y.....o.....y.....y.....r.....o.....y.....y..&steps=yyryryyyry&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第29問"

[[entries]]
id = 175
query = "field=0_b....bg....oo.o.bbbgg.gyyyg.ggbbb&steps=yybbyyybgb&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第30問"

[[entries]]
id = 176
query = "field=0_y....orr...yyog.gyooy.ggrrr.&steps=ryggryrggy&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第31問"

[[entries]]
id = 177
query = "field=0_b....bo....bb....pp...ypo...pbyb.ppyybb&steps=ybpbbyypyb&goal=0_0_7_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第32問"

[[entries]]
id = 178
query = "field=0_rr....pp...ggg..rrro..ogpp..pggp.pporrr&steps=pprrgpprgr&goal=0_0_8_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第33問"

[[entries]]
id = 179
query = "field=0_g.y...oyy..ggrr.ygogr.yyogg.&steps=gggryyyyygyg&goal=0_0_7_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第36問"

[[entries]]
id = 180
query = "field=0_p.....bbb..ppoopgpooppggbbbo&steps=bgggpppgpgpb&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第37問"

[[entries]]
id = 181
query = "field=0_y....yy....ro...rrb...bobbr.bborrroyyborroybb&steps=brbyyyryyybr&goal=0_0_8_0_"
creators = "lufu"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第38問"

[[entries]]
id = 182
query = "field=0_bg..bgbygbrgbyyrrgrggyybrgbrybrbbrrbgyyggygrygbygrrbbyyggyyryrgybryrrbbr&steps=gbbggrbgrbyrgy&goal=_0"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第39問"

[[entries]]
id = 183
query = "field=0_pb.pb.bp.pb.oo.oo.pb.pb.pb.bp.oo.oo.bp.bb.pb.pp.oo.oo.bb.bp.pp.pb.&steps=pbppbbpbppbbpbpb&goal=0_0_8_1_0"
title = "コラプサー"
creators = "π"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第40問"
