[[entries]]
id = 1090
query = "field=0_o....or....yy....rrrryyyygggrryybbbrrrryyyyygggrybbbrrrrryyy&steps=bgbyrgryry&goal=0_0_14_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第1問"

[[entries]]
id = 1091
query = "field=0_r..r..b..y.grbyb.rrbggygbrgbrggrbgrrbyybrbbyrbgrygbggrrygrryyggrg&steps=yggbbygrgryb&goal=0_0_17_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第2問"

[[entries]]
id = 1092
query = "field=0_r..gr.r..br.bb.yb.bbbyb.grybr.brgybybgybyrbrgybyrrgybyr&steps=gbrbggygbgbbgr&goal=0_3_14_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第3問"

[[entries]]
id = 1093
query = "field=0_y.r..yyrrbggppbbgrrbyybbrbbygbypprggyyrr&steps=ybrgrpgyrbby&goal=1_3_5_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第4問"

[[entries]]
id = 1094
query = "field=0_pprr..pbbr..rbgg..rrgy..bbyy..gbrr..ggyr..ryyb..rrbb.&steps=rbrgybpgryrb&goal=0_0_12_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第6問"

[[entries]]
id = 1095
query = "field=0_gbbggggbyybbgrryrbbryrrgbbyybggggbbg&steps=rbrgyygbgbbbgg&goal=0_0_12_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第8問"

[[entries]]
id = 1096
query = "field=0_b.....b...oyb..bygy..bgby..rbry..rggbybbgrggryrrgbrygbrrygbbggrygg&steps=brryygbr&goal=_0"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第10問"

[[entries]]
id = 1097
query = "field=0_yy....oy....yp..r.bp..gppr..bggg..yrrr&steps=bbrbrbybyryb&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第11問"

[[entries]]
id = 1098
query = "field=0_rr....yy....gg.y.obr.bbrrbbbyyyrb&steps=bbrgrbgbybby&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第14問"

[[entries]]
id = 1099
query = "field=0_b..r..y..y..y..y..y..y.bb..rryb..ryoo..oooooooooooooooooooooooooo&steps=ryrgrygggyry&goal=0_0_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第15問"

[[entries]]
id = 1100
query = "field=0_ryryryrbrbrbrgrgrg&steps=ryryrygbgbyy&goal=2_2_13_1_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第16問"

[[entries]]
id = 1101
query = "field=0_y.r.gyorogooyorogyorogooyorog&steps=yryryggrgrrryr&goal=0_0_7_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第17問"

[[entries]]
id = 1102
query = "field=0_oy.b..ggrr..ybbr..yygg..bbbgr.&steps=gbbyrrrgrg&goal=0_0_7_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Lunatic 第18問"

[[entries]]
id = 1103
query = "field=0_yy...ryr...yrg...rrbb.rrggbggygbrbyyrrbgrrbbggrb&steps=rgggrygbrb&goal=1_2_4_0_"
creators = "K-NES"
source = "戦技研HP"
sourceDetail = "Lunatic 第19問"

[[entries]]
id = 1104
query = "field=0_r....rroooorrogggrgoooobgorrrbgoooob&steps=rbgybyrybyrg&goal=0_0_7_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第20問"

[[entries]]
id = 1105
query = "field=0_rroorrroggorobbgbbobgoobyoggoyyyooyy&steps=gybyyyrbyygr&goal=0_0_9_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第21問"

[[entries]]
id = 1106
query = "field=0_y..b..ggbb..gbyyr.bbyrr.yyryybyrrybb&steps=yryrybybygyb&goal=0_0_10_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第22問"

[[entries]]
id = 1107
query = "field=0_bgg...bobyy.ggbog.obyyg.obobyyoggbogoooyygoooooooooooooooooo&steps=gbgyybgbybyb&goal=0_0_9_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第23問"

[[entries]]
id = 1108
query = "field=0_ooooooyyyoyyobooobybyyybobooobyyyoyyoooooooooooo&steps=bybybyyybbby&goal=0_0_8_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Lunatic 第24問"

[[entries]]
id = 1109
query = "field=0_rggr..rgyr..ryyr..bbgg..yybb.&steps=ygbbygyrbgbr&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第25問"

[[entries]]
id = 1110
query = "field=0_rroorrrobboryobrbbyyooyybbrboyrobborrroorr&steps=rbbyrbryrbrr&goal=0_0_10_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Lunatic 第26問"

[[entries]]
id = 1111
query = "field=0_gyggyggbbbbbrrygbyyryyyrrggg&steps=gbgrbyyygy&goal=0_0_9_0_"
creators = "K-NES"
source = "戦技研HP"
sourceDetail = "Lunatic 第27問"

[[entries]]
id = 1112
query = "field=0_&steps=rrrrrrggggggggrrrrrrrrrrggggggggggggrrrrrrrrrrrrrrrr&goal=2_0_42_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第28問"

[[entries]]
id = 1113
query = "field=0_r.....y.....b.....o.yo..ooro..orooy.orroyyyybbbbbbrrr&steps=byrbyybyrbby&goal=0_0_8_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Lunatic 第29問"

[[entries]]
id = 1114
query = "field=0_g.....g...o.r.o.ooyyo.oboro.obgoo.obggo.rrryyygggrrr&steps=rrgyrgbyry&goal=0_0_8_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Lunatic 第30問"

[[entries]]
id = 1115
query = "field=0_or.yo.oogyo.oroyo.obyoo.obrro.yygrgrybybgrrybbg&steps=rrgygbrgbyry&goal=0_0_10_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Lunatic 第31問"

[[entries]]
id = 1116
query = "field=0_g.....by..y.rg..bygg.ggyrygybgrybgbbrgryggbbggygbrgryy&steps=bbgybyrggy&goal=1_0_4_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Lunatic 第32問"

[[entries]]
id = 1117
query = "field=0_y...gggyyyyoooogyobbbgroooogrobbbrroooorggyyyr&steps=byrgggrygbgy&goal=0_0_10_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Lunatic 第33問"

[[entries]]
id = 1118
query = "field=0_br..g.brryb.bggyy.ygbbb.yygrr.rggyr.rryyg.bbbgg&steps=ryggryybrb&goal=0_0_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第34問"

[[entries]]
id = 1119
query = "field=0_bb....rro...rgg...bbg..gbrr.yyggy.ybgyyb&steps=brbbgrgbyryb&goal=0_1_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第35問"

[[entries]]
id = 1120
query = "field=0_obro.obbrrogooooyggooyyorooboorrbbooooooo&steps=ypgprpbrbp&goal=0_0_6_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic 第36問"

[[entries]]
id = 1121
query = "field=0_yyoyyybbbobbggogggrrrorr&steps=gyrbrgbgbyry&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Lunatic 第37問"

[[entries]]
id = 1122
query = "field=0_r....ryy..yyyb..byrr..rryrbbry&steps=ryrbybybrbry&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Lunatic 第38問"

[[entries]]
id = 1123
query = "field=0_y.....yy....bbyy..bgyr..ggrryyrryyygrbgyggbbgg&steps=bgbryrgygy&goal=0_0_10_0_0"
creators = "あおじる"
source = "戦技研HP"
sourceDetail = "Lunatic 第39問"

[[entries]]
id = 1124
query = "field=0_o...brybbybrybrybryrryyybybbybbyyb&steps=ybybrbybyr&goal=2_0_22_1_"
creators = "あおじる"
source = "戦技研HP"
sourceDetail = "Lunatic 第40問"

[[entries]]
id = 1125
query = "field=0_r.....b.....r....br....byg...rrr...gbb...gyyy.&steps=ggbrbgbgrg&goal=0_0_7_0_"
creators = "あおじる"
source = "戦技研HP"
sourceDetail = "Lunatic 第41問"

[[entries]]
id = 1126
query = "field=0_yy....yg....rr....gr....yy....yg....rr....gr....&steps=bbbybrbybrbb&goal=0_0_7_0_"
creators = "あおじる"
source = "戦技研HP"
sourceDetail = "Lunatic 第42問"

[[entries]]
id = 1127
query = "field=0_bb.r..br.yyoyy.yrgry.rgrgr.rbgbr.yrbry.yyryy.&steps=ggrgryrygyrbyb&goal=0_0_12_0_"
creators = "あおじる"
source = "戦技研HP"
sourceDetail = "Lunatic 第43問"

[[entries]]
id = 1128
query = "field=0_r.....gb...grg..gyrro.yybbb.rryyy.oooooo&steps=rgybrgybggbb&goal=0_0_8_0_0"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Lunatic 第44問"

[[entries]]
id = 1129
query = "field=0_o.y..ooyg..bgyyr.roooooogoooobggoobo&steps=bbrybyrggybbgy&goal=0_0_7_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Lunatic 第45問"

[[entries]]
id = 1130
query = "field=0_g....yg...gyg..bgyb.rbgbb.rbrrr.ryyyg.bbbgg&steps=ybygrgrbgb&goal=0_0_9_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Lunatic 第46問"

[[entries]]
id = 1131
query = "field=0_g.....b.....bbr..rryrg.rbyygggggbbb&steps=ggygrgrbrg&goal=0_0_8_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Lunatic 第47問"

[[entries]]
id = 1132
query = "field=0_grrrggggyyygbrrrbbbbyyybgrrrggggyyyg&steps=yrbgyrbgyr&goal=1_0_4_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Lunatic 第48問"

[[entries]]
id = 1133
query = "field=0_orgo..rgrg..orgo..rgrg..orgo..rgrg..orgo..rgrg..orgo.&steps=rrggbbbbggrr&goal=0_0_7_1_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Lunatic 第49問"

[[entries]]
id = 1134
query = "field=0_boog..obgo..bgbg..gbgb..ogbo..goob.&steps=bbbbggggbbggbgbg&goal=0_0_8_0_0"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Lunatic 第50問"

[[entries]]
id = 1135
query = "field=0_yy....bb....gg....rr....yy....bb....gg....rr..oooooo&steps=rrggbbyyrrggbbyy&goal=0_0_8_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Lunatic 第51問"

[[entries]]
id = 1136
query = "field=0_pypy.gggrrrrrrggggppprrggyyyrrpppggrryyyg&steps=grypgrgrgr&goal=0_0_11_0_"
creators = "sim"
source = "戦技研HP"
sourceDetail = "Lunatic 第52問"

[[entries]]
id = 1137
query = "field=0_bygyrbbygyrbbygyrbrrrbyyyggbryyygbrr&steps=ybgyrybgyb&goal=2_0_18_1_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Lunatic 第53問"

[[entries]]
id = 1138
query = "field=0_p.y..yyppyypyypyppppypyypyyppy&steps=pypyyypypypy&goal=0_0_8_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Lunatic 第54問"

[[entries]]
id = 1139
query = "field=0_b.....by..yggb.rybrbggrryygbbrby&steps=bybbrgrbggry&goal=0_0_9_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Lunatic 第55問"

[[entries]]
id = 1140
query = "field=0_y....yrb.y.yrryoyggbyrygbbyrrbrrrggbbgbbggrrbrrggrgbrrrggbb&steps=ygbrryybybrg&goal=0_0_13_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Lunatic 第56問"

[[entries]]
id = 1141
query = "field=0_o.....r....rp....pr....ryo...yrp...rpr...pry...roppr.prpyp.rproyp&steps=rpryrppyryry&goal=0_0_8_0_2"
creators = "井上"
source = "戦技研HP"
sourceDetail = "Lunatic 第57問"

[[entries]]
id = 1142
query = "field=0_rr...roor..royr..orrbb.oobooboobyoborrbboroorooryorooorrooo&steps=ryrbrbrbrbrb&goal=0_0_7_0_2"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Lunatic 第58問"

[[entries]]
id = 1143
query = "field=0_gggoogyrrrogyobbbgyooyyygggoogybbbogyorrrgyooyyy&steps=bygyyggrrybg&goal=0_0_11_1_0"
creators = "shimogon"
source = "戦技研HP"
sourceDetail = "Lunatic 第59問"
