[[entries]]
id = 1
query = "field=0_rrbbrr&steps=brbr&goal=2_0_6_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2016"
sourceDetail = "練習問題 第1問"

[[entries]]
id = 2
query = "field=0_b.....rb....rr....&steps=bbrr&goal=0_0_2_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2016"
sourceDetail = "練習問題 第2問"

[[entries]]
id = 3
query = "field=0_g.....g.....goooooorrryyyoooooo&steps=rgyg&goal=_1"
creators = "aojil"
source = "早大なぞぷよマスターズ2016"
sourceDetail = "練習問題 第3問"

[[entries]]
id = 4
query = "field=0_bbg...bgg...gbb...ggb...&steps=bgbg&goal=0_0_4_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2016"
sourceDetail = "練習問題 第4問"

[[entries]]
id = 5
query = "field=0_b.....bb....rg...rrgg.&steps=rbgg&goal=0_0_3_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2016"
sourceDetail = "練習問題 第5問"

[[entries]]
id = 6
query = "field=0_b....brrr.bbbbbrrr&steps=yrbr&goal=0_0_4_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2016"
sourceDetail = "練習問題 第6問"
