[[entries]]
query = "field=0_b...r.b...rgb...ggo..&steps=brgr&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "例題"

[[entries]]
query = "field=0_y.....y.....gg..yygyyy&steps=gy&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "初級 第1問"

[[entries]]
query = "field=0_pp....py....oy...ypyp..yypp&steps=yp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "初級 第2問"

[[entries]]
query = "field=0_bob.rrryyy&steps=brby&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "初級 第3問"

[[entries]]
query = "field=0_o..g.po..g.po..g.gg..&steps=gpgp&goal=_0"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "初級 第4問"

[[entries]]
query = "field=0_g.....b.....b....gb....go....oy...yybbb&steps=bybg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "初級 第5問"

[[entries]]
query = "field=0_b.r.r.r.b.r.&steps=brrrbr&goal=0_0_3_0_"
title = "出鼻くじきトライタワー"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第1問"

[[entries]]
query = "field=0_b.....bb....ryyb.rrybb&steps=byrb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第2問"

[[entries]]
query = "field=0_ry....ry....yo....yr....or..rryy..&steps=yryr&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第3問"

[[entries]]
query = "field=0_o.....o.....o...orr...grgg..ggrg..orro.&steps=grgr&goal=0_0_4_0_"
title = "アンテナ付き卍ガラケー"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第4問"

[[entries]]
query = "field=0_p..yrpp..yyry..rryy.&steps=ypyp&goal=0_0_2_0_0"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第5問"

[[entries]]
query = "field=0_g.....po....pg....pg....og..o.pp..gggp.&steps=gpgp&goal=1_0_2_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第6問"

[[entries]]
query = "field=0_oo...bbb...ooo...bbbyyyyyooy&steps=ybyb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第7問"

[[entries]]
query = "field=0_r.....r.....bbo...brb...oorrr&steps=bbrbrb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第8問"

[[entries]]
query = "field=0_r...b.bb..bbybr.rryyr.&steps=byrrrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第9問"

[[entries]]
query = "field=0_googogggoogg&steps=bggggg&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第10問"

[[entries]]
query = "field=0_r.....brr..obog..rrggo&steps=gbrrbr&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第11問"

[[entries]]
query = "field=0_ooooo.roror.roror.roror.ororo.&steps=rrrrrr&goal=0_0_3_1_0"
title = "早稲田なぞぷよ"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第13問"

[[entries]]
query = "field=0_r.....o.....rr....bb....rry..ooyy.&steps=rrbrby&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第14問"

[[entries]]
query = "field=0_r.....o.....ro....bbr...orb..robb.&steps=rrbbbr&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第15問"

[[entries]]
query = "field=0_yy...bygyy.bbggygggbbb&steps=yggbby&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第16問"

[[entries]]
query = "field=0_r.....o..g.ggo.b.grrbb&steps=ggrgbg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第17問"

[[entries]]
query = "field=0_pppbbyybbpbpybppoppyyyp&steps=pyybbp&goal=0_0_6_1_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第18問"

[[entries]]
query = "field=0_o.....yo....yy...bbbo..yyoy.bbobyybybboo&steps=ybybyb&goal=0_0_5_1_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第19問"

[[entries]]
query = "field=0_g.....g.....g.....y.....g...oogooobbgbbb&steps=yybgbybg&goal=0_0_5_0_"
title = "かぐや姫"
creators = "こな"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第20問"

[[entries]]
query = "field=0_r.....brb...bbr...rrgg..rgrrr&steps=gbbbbrrr&goal=0_0_6_0_"
title = "2トリ未遂"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第21問"

[[entries]]
query = "field=0_b...rbrr.gggbrgorrbgg&steps=bgbrbrbg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第22問"

[[entries]]
query = "field=0_b.....g.....b..rgbrbrrgrrggg&steps=rgrbbbbg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第23問"

[[entries]]
query = "field=0_b....rrrg..gbgr.rgrrg.rgrgg.rooooo&steps=gbgrgbgr&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第24問"

[[entries]]
query = "field=0_o....ogb...gbb...ggrr..rogr..rrgb.&steps=gbrbrbgb&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第25問"

[[entries]]
query = "field=0_r....rb...rbr...byy...oby...brr...ybb...yyb..&steps=brbrbyby&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第26問"

[[entries]]
query = "field=0_o...b.y...o.b...oob...ybo..yhyb..yboy..bboyy&steps=yybbybby&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第27問"

[[entries]]
query = "field=0_p.....r.....rb..p.pp..bbrp.rrrpb.&steps=rbbbrpbp&goal=0_0_6_0_"
creators = "山下"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第28問"

[[entries]]
query = "field=0_oh....gb...hbb..brrr..bbggo.&steps=grrbrrrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第29問"

[[entries]]
query = "field=0_ggg..bbobb.brrrb.obgbo.rgbgr.rgbgr.rgbgr&steps=rgbgbgrg&goal=_0"
title = "凱旋門"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第30問"

[[entries]]
query = "field=0_bbb..bggy..bygb..bgyb..ybgb..bbgg.&steps=gbgbgbgb&goal=_0"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第31問"

[[entries]]
query = "field=0_r.....b.y...brr.y.oyr.yyobyy&steps=bbrbrbrbry&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第32問"

[[entries]]
query = "field=0_ybbyb.yobgbgyggoog&steps=gbyyyggbyb&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第33問"

[[entries]]
query = "field=0_yyygggoroorobbbyyyoroorogggbbboro&steps=rbrggyryrb&goal=1_0_4_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第34問"

[[entries]]
query = "field=0_g....rrgb..rgbrr.bgobrgbbobgg&steps=bbgbgbrrgggb&goal=0_0_8_0_"
title = "知恵の輪"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第35問"

[[entries]]
query = "field=0_r.....oro...rbb..ggbg..rrrg..obbg.&steps=bgrrbgrrrgrb&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第36問"

[[entries]]
query = "field=0_ry...rryy..ggbb.rrgbyyrbrygyyybgrrybbggrrgrybyrrgbyyggoobb&steps=rgbgbybyrgry&goal=_0"
title = "羅生門"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第37問"

[[entries]]
query = "field=0_b.....o.....r.....o.....b.....r.....b.....o.....r.....b.....r...&steps=rbrbrrbbrrbbbrbr&goal=0_0_6_0_"
title = "蜘蛛の糸"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第39問"

[[entries]]
query = "field=0_ob....ob....obbbyyogbgryogggrrogbbggoybrrgoyyryyoyybbyorybggorrrrgor&steps=bgrgrybyybyrgrgb&goal=0_0_12_1_"
title = "究極虚数銀河"
creators = ["OrangeP", "π"]
source = "早大なぞぷよマスターズ2018"
sourceDetail = "第40問"

[[entries]]
query = "field=0_oggo..roob..ggro..gooo..orro.&steps=rrbrbrgggb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "オイラーなぞぷよ「e」"

[[entries]]
query = "field=0_bbyyr.oroyo.ororo.booorr&steps=rryrbrbbbrbr&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "オイラーなぞぷよ「π」"

[[entries]]
query = "field=0_oro...ooo...pro...opo...opr..&steps=prrrprpppr&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "オイラーなぞぷよ「i」"

[[entries]]
query = "field=0_oro...rro...obo...ogo...bbb..&steps=bgbgbrgb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "オイラーなぞぷよ「1」"

[[entries]]
query = "field=0_gbg...ooo...brr...ooo..&steps=ggbgrgrgbg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "オイラーなぞぷよ「=」"

[[entries]]
query = "field=0_ggp...gog...pop...pog...bbb..&steps=gpgpgppb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2018"
sourceDetail = "オイラーなぞぷよ「0」"
