[[entries]]
id = 184
query = "field=0_r..rrrorr&steps=rr&goal=_0"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第1問"

[[entries]]
id = 185
query = "field=0_p.....p....pbb..ppbpp.&steps=pb&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第2問"

[[entries]]
id = 186
query = "field=0_b.....b.....b.....y.....y.....b....yo....yby...bbyy.&steps=by&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第3問"

[[entries]]
id = 187
query = "field=0_p.....yyyypyy&steps=ypyp&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第4問"

[[entries]]
id = 188
query = "field=0_p.o...gpg..ppgg..&steps=gggg&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第5問"

[[entries]]
id = 189
query = "field=0_o...o.b...r.b...r.b...yyy..&steps=brry&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第6問"

[[entries]]
id = 190
query = "field=0_g.....org...rgg.gggrrr&steps=rrrg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第7問"

[[entries]]
id = 191
query = "field=0_bb....rr....rg....bg.o..bgrr.&steps=rrgr&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第8問"

[[entries]]
id = 192
query = "field=0_o..y..rryryrrrroggg&steps=rgry&goal=_0"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第9問"

[[entries]]
id = 193
query = "field=0_b.....b.....p.o..orpp.&steps=rrpbrb&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第10問"

[[entries]]
id = 194
query = "field=0_p.....b.....g....gp.gggpp&steps=bgbgbg&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第11問"

[[entries]]
id = 195
query = "field=0_p.....rr..gppprrr&steps=grgrgr&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "初級 第12問"

[[entries]]
id = 196
query = "field=0_g.....g.....g.....y.....p.....p.....p.....y..oooyy.&steps=gyyypy&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第1問"

[[entries]]
id = 197
query = "field=0_y.....rb....rry...yyb...ybyyy&steps=yybyry&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第2問"

[[entries]]
id = 198
query = "field=0_y..o..o.gg..y.yy..o.oo.&steps=gyyygy&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第3問"

[[entries]]
id = 199
query = "field=0_p..p..p..p..o..gg.g..opgg.&steps=gpgpgp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第5問"

[[entries]]
id = 200
query = "field=0_b.rb..b.or..yyryy.yobyb&steps=bybrby&goal=0_0_5_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第6問"

[[entries]]
id = 201
query = "field=0_r.....p.....o.....pp...rpr...ryr..rpyy.&steps=rpppry&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第7問"

[[entries]]
id = 202
query = "field=0_g.....p.....b.....b.....b.....p.....p.....b.g..bopbbbppbb&steps=bpgpgb&goal=0_0_6_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第9問"

[[entries]]
id = 203
query = "field=0_p....pppp..rropgoor&steps=gprggp&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第10問"

[[entries]]
id = 204
query = "field=0_r.....y.....r.....ry...ryy...roo..yyoo..orrr.&steps=yrrryr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第11問"

[[entries]]
id = 205
query = "field=0_rr....ry....bb.y..boyb..yybb.&steps=byryby&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第12問"

[[entries]]
id = 206
query = "field=0_r.....g....og....or....gg...rrg...ggr...orp...gggp.&steps=gprpgr&goal=0_0_6_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第13問"

[[entries]]
id = 207
query = "field=0_g.....b.....g..gobobggbb&steps=bbgggg&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第14問"

[[entries]]
id = 208
query = "field=0_p.....b.....p.....pp.p..bbob..pbpp..boop..bppb..bobbp.oooppo&steps=pppbpb&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第15問"

[[entries]]
id = 209
query = "field=0_r..r..ryor..ryyr..yrry..ybry..ybby..byyb..bryb..brrb..rbbr..rybr..ryyr.&steps=rybbry&goal=_0"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第16問"

[[entries]]
id = 210
query = "field=0_g.o...g.g...gpg..goog..&steps=pppggggg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第17問"

[[entries]]
id = 211
query = "field=0_yb....op....ppy...oyy.&steps=yybbyybp&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第18問"

[[entries]]
id = 212
query = "field=0_oo...yggy..yooy.gggbbb&steps=byggyygy&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第19問"

[[entries]]
id = 213
query = "field=0_r.....p.y..pp.y..yo.r..yyrr.&steps=ryyprrry&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第20問"

[[entries]]
id = 214
query = "field=0_bg....ggog..obgb..ggbb.&steps=bgggbgbg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第21問"

[[entries]]
id = 215
query = "field=0_r.....r....go....gr....rg...rog...yyy.&steps=rrgyggrg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第22問"

[[entries]]
id = 216
query = "field=0_y....yp....yp....py....yp....oo....yyy.&steps=ypyyppyp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第23問"

[[entries]]
id = 217
query = "field=0_bb...yooy..ybby..ybrr.&steps=rrbbyyby&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第24問"

[[entries]]
id = 218
query = "field=0_r.....y.....g.....g.....g.....rg....ry....gyy.&steps=rgrrrgrg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第25問"

[[entries]]
id = 219
query = "field=0_y.....gy....og....po....yy...gyp...ggo..&steps=gggpyyyp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第26問"

[[entries]]
id = 220
query = "field=0_r.....g.....r.....r.....r.....p.....o.....g....oo....org...rrg..&steps=ppggpgrg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第27問"

[[entries]]
id = 221
query = "field=0_rgb...rrog.bbbbgbbrrgbggrggbbg&steps=rgbggbgr&goal=0_0_7_1_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第28問"

[[entries]]
id = 222
query = "field=0_pb..pppprbpbbbppbbprprrrrrbbbp&steps=prpbbrrb&goal=0_0_7_1_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第29問"

[[entries]]
id = 223
query = "field=0_&steps=o1_0_0_0_0_0oyyo0_1_0_1_0_1oyyo1_0_0_0_1_1oyyo0_1_0_0_1_1oyyo0_0_1_0_1_1oyy&goal=_0"
title = "流れ星"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第30問"

[[entries]]
id = 224
query = "field=0_o.....b.....b.....b..r.or.bbbrb.&steps=rrrbbbrbrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第31問"

[[entries]]
id = 225
query = "field=0_r.....gb....br...bog...rrbb..ggob.&steps=rbrgggrbrg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第32問"

[[entries]]
id = 226
query = "field=0_b...b.b...g.o...g.obb.gobob&steps=bgggbgbbbg&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第33問"

[[entries]]
id = 227
query = "field=0_p.....p.....o....po....gg...gpg..ggoo.&steps=gggppgpggp&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第34問"

[[entries]]
id = 228
query = "field=0_r.....y.....yg.g..gyyy..gooo.rrryyy&steps=yyrygyggrrrg&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第35問"

[[entries]]
id = 229
query = "field=0_g.....ryy...yry..yyrg.gggogg&steps=rryyrgggrgrg&goal=0_0_7_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第36問"

[[entries]]
id = 230
query = "field=0_b...yrr...roy..yyyr..ooobb.&steps=bbrrbbryryby&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第37問"

[[entries]]
id = 231
query = "field=0_yy..bbyr..bgrr..ggoobbooyyrbyygyrrgyggooggooyyoobbygbbbrggbrrroorr&steps=grybygrgbryrbgyb&goal=0_0_13_1_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第38問"

[[entries]]
id = 232
query = "field=0_o....ooo..oooo..ooooo.oooooooooooooooooooooooooooooooooooooooooooo&steps=brrrbrgrbbgrgrbgbbbr&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第39問"

[[entries]]
id = 233
query = "field=0_&steps=o1_0_0_0_0_1oppo0_1_0_1_0_1oppo1_0_0_0_1_0oppo1_1_1_2_1_1oppo1_1_1_0_1_0oppo0_1_1_1_0_1oppo1_0_0_1_1_1oppo0_1_1_0_1_0oppo1_0_1_1_1_0oppo0_1_1_1_1_0oppo1_0_1_0_0_1opp&goal=_0"
title = "流星群"
creators = ["π", "OrangeP"]
source = "早大なぞぷよマスターズ2022"
sourceDetail = "第40問"
