[[entries]]
id = 284
query = "field=0_p.....op....pp...ggo...gppp.&steps=gp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第1問"

[[entries]]
id = 285
query = "field=0_p.....p.....p....po...ggp...gpp..&steps=gp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第2問"

[[entries]]
id = 286
query = "field=0_g.....p.....p.....pg....gg....oo...ggg..&steps=gp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第3問"

[[entries]]
id = 287
query = "field=0_p.....p.....p.....g.....p.....p....ggpg..gpgg.&steps=gp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第4問"

[[entries]]
id = 288
query = "field=0_g.....g.....p....pp...ogo...gpgp..ggpp.&steps=gp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第5問"

[[entries]]
id = 289
query = "field=0_y.....y....ro.y.yry.y&steps=yryr&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第6問"

[[entries]]
id = 290
query = "field=0_r....br....br....oy....oyy.&steps=rbyb&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第7問"

[[entries]]
id = 291
query = "field=0_yy....by....bb....oorr.&steps=ryrb&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第8問"

[[entries]]
id = 292
query = "field=0_b.....o.....bbr.bbobr.&steps=rbrb&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第9問"

[[entries]]
id = 293
query = "field=0_p.....p.....p.....o.....p.....pg...pgo..&steps=gpgp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第10問"

[[entries]]
id = 294
query = "field=0_p.....o.....p.....o.....op..pgggp.&steps=ppgp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第11問"

[[entries]]
id = 295
query = "field=0_pg....pog..ggog..ooog.&steps=gpgp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第12問"

[[entries]]
id = 296
query = "field=0_rr....bb....by...ryyo..rror.&steps=bryr&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第13問"

[[entries]]
id = 297
query = "field=0_g...ogg...ppp...gggo..popp.&steps=gpgp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第14問"

[[entries]]
id = 298
query = "field=0_b.....o.g...gbo...gbb...gog...bbb.&steps=gggb&goal=0_0_4_0_"
creators = "花ロア"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第15問"

[[entries]]
id = 299
query = "field=0_g.og..g.gg..ppop..pgpp.&steps=gpgp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第16問"

[[entries]]
id = 300
query = "field=0_o..o..po.g..pg.ggopggppp&steps=gpgp&goal=1_0_2_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第17問"

[[entries]]
id = 301
query = "field=0_b.....b.....o.....b.....o.....b.....yb...&steps=bybyby&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第18問"

[[entries]]
id = 302
query = "field=0_o..o..o.po..p.pg..p.og.&steps=pgpppg&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第19問"

[[entries]]
id = 303
query = "field=0_y....ppo.pyypypy&steps=yypppy&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第20問"

[[entries]]
id = 304
query = "field=0_b...b.yygggbbb&steps=bbyygb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第21問"

[[entries]]
id = 305
query = "field=0_p.....py....oo....yy....op...oopo..oyyy&steps=yypppp&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第22問"

[[entries]]
id = 306
query = "field=0_r.....o.....y.....ryy...ooy.yrorr&steps=ryryry&goal=0_0_4_0_"
creators = "KaKe"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第23問"

[[entries]]
id = 307
query = "field=0_p.o...p.p.ogg.ppgpg.&steps=gpgggp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第24問"

[[entries]]
id = 308
query = "field=0_g.....o.....oorg..ooor.rrroo.gggoo.ooooo&steps=grgrgr&goal=0_0_4_0_"
creators = "花ロア"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第25問"

[[entries]]
id = 309
query = "field=0_p....rpp..prbbr.pprbr.&steps=rprbrp&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第26問"

[[entries]]
id = 310
query = "field=0_r.....o.r...ygg..yybgr.orrbb.&steps=rbrgry&goal=0_0_5_0_"
creators = "Kimo"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第27問"

[[entries]]
id = 311
query = "field=0_r.....r.....p.....p.....p....gg....rg....rp...rpoo..ppggg&steps=rrgprg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第28問"

[[entries]]
id = 312
query = "field=0_gr....grb...brb..gbgb..bgbg..oobb.&steps=bgbrbg&goal=0_0_6_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第29問"

[[entries]]
id = 313
query = "field=0_o....yyy.byryggrbbrrrgrbbbbrggrgrbygrrgrbyggrrbb&steps=ggrbry&goal=0_0_12_0_"
creators = "花ロア"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第30問"

[[entries]]
id = 314
query = "field=0_rgbrgbrgbrgbrgbrgboooooorgbrgbrgbrgbrgbrgb&steps=rggbbr&goal=1_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第31問"

[[entries]]
id = 315
query = "field=0_pp...gph...ghpg..rrrp..hgpp.&steps=ggrggp&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第32問"

[[entries]]
id = 316
query = "field=0_p....pr....rh....hy....yr....rr..rryyy&steps=pypyyr&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第33問"

[[entries]]
id = 317
query = "field=0_o.....r.....p.....r.....r.....p.....o.....r.....o....orp..&steps=rppprprp&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第34問"

[[entries]]
id = 318
query = "field=0_pp....op....pyy..yoyo.&steps=bbyybyby&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第35問"

[[entries]]
id = 319
query = "field=0_r.....p.....o...o.o..poro..pprr.&steps=prpprrrp&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第36問"

[[entries]]
id = 320
query = "field=0_bb..grbg..ggoo.&steps=rgrbggrg&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第37問"

[[entries]]
id = 321
query = "field=0_r.....g....rg....or....gr....bb...ggb.&steps=rrrgggrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第38問"

[[entries]]
id = 322
query = "field=0_r.....r.gb..bbgb..rbrr.&steps=bgbrbrgr&goal=0_0_5_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第39問"

[[entries]]
id = 323
query = "field=0_y.....b.....o....yb....yo....rr....rbb...oyb..&steps=bybyrbyy&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第40問"

[[entries]]
id = 324
query = "field=0_r.....y....yy....pr....oo....rr...yyry.&steps=rpryppry&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第41問"

[[entries]]
id = 325
query = "field=0_g...r.r..ggogy.grgyy.&steps=gryrrrrg&goal=0_0_5_0_"
creators = "花ロア"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第42問"

[[entries]]
id = 326
query = "field=0_g.....yb....oy.b..ob.bbybb.yyggg.&steps=gybygygg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第43問"

[[entries]]
id = 327
query = "field=0_b.....y.....by...rry..bbyr..byyrr&steps=rbrybbyr&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第44問"

[[entries]]
id = 328
query = "field=0_o.g.o.o.o.orrrbbbooooooyyyrrroooooobbbyyyoooooorrrggg&steps=rygrbybr&goal=0_0_8_0_"
creators = "Kimo"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第45問"

[[entries]]
id = 329
query = "field=0_y....gb....gb....gbr...rrg...yyr..ggygrrbyrrggbyrrrgryrgbrgrbgbrrbb&steps=bbgbggyg&goal=4_4_17_0_"
creators = "KaKe"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第46問"

[[entries]]
id = 330
query = "field=0_y.....g.....o.o...yyy...pog...oyyy&steps=gygpgggpgp&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第47問"

[[entries]]
id = 331
query = "field=0_ryy...yry..yyrg..ggogg&steps=ryrrryggrg&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第48問"

[[entries]]
id = 332
query = "field=0_b....byo...oyb...bby...byb...oyy...yoo..&steps=ybbbbyyyyb&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第49問"

[[entries]]
id = 333
query = "field=0_r.....b.....o.....b.....b...bgr...ogg...bro...oog..&steps=gbrgggrbrrrb&goal=0_0_6_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第50問"

[[entries]]
id = 334
query = "field=3_~ggbb..g.rr.....r&steps=bgbr&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第51問"

[[entries]]
id = 335
query = "field=1_y...ppyr..rooo.opppop&steps=rpypyrR&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第52問"

[[entries]]
id = 336
query = "field=0_&steps=o0_0_0_0_0_1orro1_0_1_0_1_0orro0_1_1_0_0_0orro0_1_0_1_1_1orr&goal=_0"
creators = "π"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第53問"

[[entries]]
id = 337
query = "field=1_o.....o.....p.....p....pop...&steps=ppgpRgpppRgpgpR&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第54問"
