[[entries]]
query = "field=0_rb...orrb.brbbrbboooorro&steps=rrrrrb&goal=0_0_5_0_"
creators = "（´・ω・｀）"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.1"

[[entries]]
query = "field=0_r.....r.....r....ro....ro....ro....or....or....or....ro....ro....ro.&steps=bbggbbgg&goal=_0"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.2"

[[entries]]
query = "field=0_y....yy....yg....rg....rb....bb....br....gr....gy....yy....y&steps=rryybbggyy&goal=0_0_5_0_"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.3"

[[entries]]
query = "field=0_g.....g.....b.....b.....rb....rb.&steps=yyrryyggrrrr&goal=1_0_4_0_"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.4"

[[entries]]
query = "field=0_bbbyrryyryyryrrbbb&steps=ybrbry&goal=0_0_6_0_"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.5"

[[entries]]
query = "field=0_y.....y.y...bbbobbyyrrrb&steps=yrbyby&goal=0_0_5_0_"
creators = "まてりあ"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.6"

[[entries]]
query = "field=0_g.....o.....y....yyg...grg..ggyy..rryr.&steps=yygyyygy&goal=0_0_6_0_"
creators = "まてりあ"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.7"

[[entries]]
query = "field=0_ggooyygobroyobbrrooyyggoroygobrroobb&steps=bygrbrgy&goal=0_0_8_0_"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.8"

[[entries]]
query = "field=0_bbbrrroggyyopogyoppoygopoyyggorrrbbb&steps=ryybrggb&goal=0_0_8_0_"
creators = "STK"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.9"

[[entries]]
query = "field=0_b..o..b..bb.o..orbo..oorb..rrbb..&steps=rbrbrbrb&goal=0_0_5_0_"
creators = "くわーてぃ"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.10"

[[entries]]
query = "field=0_r...b.r...gyg...yyg...rbb...rrb.gyggggygrbyyybggggrbrbyggrgggrrbbyy&steps=gybgyrbrgb&goal=0_0_14_0_"
creators = "aojil"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.11"

[[entries]]
query = "field=0_b..yy.b..yr.rgygorrrgyorggyygg&steps=gbgrgrgygb&goal=0_0_8_0_"
creators = "まてりあ"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.12"

[[entries]]
query = "field=0_bb..yyby..ybryybbbrrbb&steps=yrrbrrbbyr&goal=0_0_7_0_"
creators = "まてりあ"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.13"

[[entries]]
query = "field=0_yg...gygy..bbrr.rbgyrbrrgybb&steps=rybyggbyrg&goal=0_0_8_0_"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.14"

[[entries]]
query = "field=0_rrgrggrggrrgoooooobbrgyybrrggyooooooyybybbybbyyb&steps=byrgbyrgbyrg&goal=0_0_12_0_"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.15"

[[entries]]
query = "field=0_ggppyygpbrpypbbrrppyyggprpygpbrrppbb&steps=prpypbpgrbgy&goal=0_0_12_0_"
creators = "ウァルト"
source = "2011年度駒場祭ぷよぷよ大会"
sourceDetail = "No.16"
