[[entries]]
query = "field=0_bb.rrrrr.bbb&steps=brbr&goal=_0"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 1"

[[entries]]
query = "field=0_y.r..yr.y..yy.y.&steps=ryry&goal=0_0_3_0_"
creators = "まてりあ"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 2"

[[entries]]
query = "field=0_rr....gg...rbgr..rbbr.&steps=rgrb&goal=0_0_4_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 3"

[[entries]]
query = "field=0_gyy...ggy.rrrbbboooooo&steps=rbgy&goal=0_0_4_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 4"

[[entries]]
query = "field=0_gy....yy...rgg...gry.rrggyy&steps=gygy&goal=0_0_5_0_"
creators = "kattun"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 5"

[[entries]]
query = "field=0_g.....rgg..roro..oogg..rrrg.&steps=rgrg&goal=0_0_4_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 6"

[[entries]]
query = "field=0_bbrrrbboooobrorrobroororrbbborooooorrrrbbb&steps=rbrb&goal=0_0_7_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 1"

[[entries]]
query = "field=0_grrr..yyoo..rrro.yyggg.&steps=yryyyr&goal=0_0_5_0_"
creators = "（´・ω・｀）"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 2"

[[entries]]
query = "field=0_g.....y.g...y.rg..gggy..rryy..&steps=gryygy&goal=0_0_5_0_"
creators = "まてりあ"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 3"

[[entries]]
query = "field=0_r.....oo...bobobbbbororrrrorr&steps=rbrrrb&goal=0_0_5_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 4"

[[entries]]
query = "field=0_yyog..yogg..rrob..robb..ggoy..goyy..bbor..borr.&steps=rrggbbyy&goal=0_0_8_0_"
creators = "kattun"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 5"

[[entries]]
query = "field=0_r..r.yy..ggbg..grrb..bryb..yygb.bbygg&steps=gyrrrbby&goal=0_0_8_0_"
creators = "colo"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 6"

[[entries]]
query = "field=0_g.....oy...rggbb.rrgyr.ggyyr.gbbbr&steps=ybyrbrybyg&goal=0_0_8_0_"
creators = "まてりあ"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 1"

[[entries]]
query = "field=0_y.....yy....bg.yo.rgryo.rbboo.rbrrr&steps=ybgbybrbgy&goal=0_0_7_0_"
creators = "kattun"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 2"

[[entries]]
query = "field=0_rrro..oyyy..gggo..orrr..bbbo..oggg..yyyo..obbb.&steps=gbygrrby&goal=2_2_16_0_"
creators = "kattun"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 3"

[[entries]]
query = "field=0_g....ggbb..yyrr.bgbybrbbgbybggbybbyybyggygyrbggrrbrrggrbbr&steps=rbbybyrgbg&goal=0_0_15_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 4"

[[entries]]
query = "field=0_obbb..rrro..oyyy..gggo..obbb..rrro..oyyy..gggo..obbb..rrro.&steps=ryrbgbgrby&goal=0_0_10_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 5"

[[entries]]
query = "field=0_r.....rb....rr....yb....bb....yg....yy....rg....gg....rbg...rrb...bbr...yyyrrr&steps=rbrgrbybggrb&goal=0_0_11_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 6"

[[entries]]
query = "field=0_yybg..yrgb..brrg..bgyg..byrg..yrbb..ybrb..brgg..bbrr.&steps=bgrgbybgrgbr&goal=0_0_12_0_"
creators = "kattun"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Impossible 1"

[[entries]]
query = "field=0_o....orrbryyyybrbbbryyrybrbbryyyrybbbbryrr&steps=yrybyrybybyb&goal=_0"
creators = "kattun"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Impossible 2"

[[entries]]
query = "field=0_r....br....rr...gbg...bbr...ggg.y.ryr.y.brr.y.gggyb.yyybb.bbbyyyrrrrrrggg&steps=rgbgygbbrgbgrrrb&goal=0_0_16_0_"
creators = "ウァルト"
source = "2012年度駒場祭ぷよぷよ大会"
sourceDetail = "Impossible 3"
