[[entries]]
query = "field=0_rr....bbb...rrr...bbb.&steps=rrbb&goal=_0"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 1"

[[entries]]
query = "field=0_gbg...gbg...gbg...rrr...&steps=gbgr&goal=0_0_4_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 2"

[[entries]]
query = "field=0_yrr..ryyr..rrggg.&steps=ryrg&goal=0_0_4_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 3"

[[entries]]
query = "field=0_gyy.ggoog.gyyygg&steps=yyyg&goal=0_0_4_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 4"

[[entries]]
query = "field=0_rbrg..rrgg..gbbr..ggrr..&steps=gbrg&goal=0_0_5_0_"
creators = "hemios"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 5"

[[entries]]
query = "field=0_b...bbr...brr..rggb..rrgbb.&steps=rgrb&goal=0_0_5_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 6"

[[entries]]
query = "field=0_brr...boor.rrbbr.&steps=bbbrbr&goal=0_0_4_0_"
creators = "colo"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 7"

[[entries]]
query = "field=0_r.r...rbr...brb..bbrbb.ggyyy.&steps=ryggrb&goal=0_0_6_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 8"

[[entries]]
query = "field=0_r..g..r..g..yybb.&steps=rybyrgbg&goal=1_0_3_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 9"

[[entries]]
query = "field=0_r..g..rg.ggrgg.rrbbb.&steps=grrrgb&goal=0_0_5_0_"
creators = "くだら"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 1"

[[entries]]
query = "field=0_byy..rbyrybbboooobyyyrrr&steps=rrrbby&goal=0_0_6_0_"
creators = "colo"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 2"

[[entries]]
query = "field=0_yr....ygrr..yrggy.grryy&steps=rgygggyr&goal=0_0_6_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 3"

[[entries]]
query = "field=0_br....bb....yy...rgrrb.rggbb&steps=ryrbgbyr&goal=0_0_6_0_"
creators = "まてりあ"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 4"

[[entries]]
query = "field=0_oobbb.yyyoo.ooggg.rrroo.ooggg.yyyoo.oobbb.rrroo.&steps=rbyyrgbg&goal=0_0_8_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 5"

[[entries]]
query = "field=0_yg..y.rr.grygygrrgbbyrrogyor&steps=grbrbygryr&goal=0_0_8_0_"
creators = "くだら"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 6"

[[entries]]
query = "field=0_g.....gy.y..yryr..rgyr..rggro.oooooo&steps=gyrygygr&goal=0_0_6_0_1"
creators = "colo"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 1"

[[entries]]
query = "field=0_g.....r....rbg...bgg...rrb.ggrbbo&steps=rgrbgbrb&goal=0_0_6_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 2"

[[entries]]
query = "field=0_pp...prbp.prrbbppggyypopgypoooppoo&steps=pgpbprpy&goal=_0"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 3"

[[entries]]
query = "field=0_rry...ryy..bbbrr.ygggr.yybbyy&steps=ybygrbybyr&goal=0_0_8_0_"
creators = "まてりあ"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 4"

[[entries]]
query = "field=0_y...bbb.rryyyyybbrrrybyyyrgggrr&steps=yrbrygrrbr&goal=0_0_9_0_"
creators = "まてりあ"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 5"

[[entries]]
query = "field=0_brr...yyy...brr...yyy.obbrr.o&steps=ybrrbbbbyb&goal=0_0_6_0_0"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 6"

[[entries]]
query = "field=0_bbyybbboryobgorroygooooygoggoyyogbogyybbgg&steps=gbybgrgyby&goal=0_0_10_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "H"

[[entries]]
query = "field=0_bbg...booo..orgro.orgro.orgro.booob.bbgbb.&steps=bgbgrgbr&goal=0_0_7_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "O"

[[entries]]
query = "field=0_gg..rrryyygboobbgbobobgbooggryobbgryorbyryrryy&steps=bgryygrgbgry&goal=0_0_12_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "P"

[[entries]]
query = "field=0_ooo...obbb.booorrboyyrbbooobbrrryyybbbggg&steps=yrybgbybrb&goal=0_0_9_0_"
creators = "ウァルト"
source = "2013年度駒場祭ぷよぷよ大会"
sourceDetail = "E"
