[[entries]]
id = 400
query = "field=0_b....yyb..bbyb&steps=bybb&goal=0_0_3_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 1"

[[entries]]
id = 401
query = "field=0_rr...rrbbbrr&steps=rbrb&goal=_0"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 2"

[[entries]]
id = 402
query = "field=0_byy...byr...bggggggrrr&steps=gygb&goal=0_0_5_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 3"

[[entries]]
id = 403
query = "field=0_g..rrog..roog..goro..ggrr.&steps=rgrg&goal=0_0_4_0_"
creators = "colo"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 4"

[[entries]]
id = 404
query = "field=0_or....grr...ggb...orbb..orro.&steps=rbrg&goal=0_0_4_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 5"

[[entries]]
id = 405
query = "field=0_g...gbr...ggr...bbb..rrrggg&steps=rrrg&goal=0_0_5_0_"
creators = "colo"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 6"

[[entries]]
id = 406
query = "field=0_yrb...yrb...rby...rby...rby...yrb..&steps=yrybrb&goal=0_0_6_0_"
creators = "まてりあ"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 7"

[[entries]]
id = 407
query = "field=0_b...ggb..booo..gggbb&steps=gbbbgg&goal=0_0_4_0_"
creators = "colo"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 8"

[[entries]]
id = 408
query = "field=0_rr....yy....bb....rr..&steps=ryrbryrb&goal=1_0_3_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Easy 9"

[[entries]]
id = 409
query = "field=0_rg....rr....ygg...yyg...grrr..ggyy.&steps=yyryrg&goal=0_0_6_0_"
creators = "かにすけ"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 1"

[[entries]]
id = 410
query = "field=0_r.....r.....gg....rgo...bbrb..bggb..rrgb&steps=rbrgbg&goal=0_0_6_0_"
creators = "colo"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 2"

[[entries]]
id = 411
query = "field=0_gr....ggrg..rogoorrroggooogrro&steps=rgrrggrg&goal=0_0_6_0_"
creators = "hemios"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 3"

[[entries]]
id = 412
query = "field=0_rg....rr.g..yg.y..yyryy.rrggg.&steps=yggryr&goal=0_0_6_0_"
creators = "まてりあ"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 4"

[[entries]]
id = 413
query = "field=0_bbr...brr...yyb...ybb...rry...ryy.&steps=ybrryb&goal=0_0_6_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 5"

[[entries]]
id = 414
query = "field=0_rr..rrgr..rbgb..gbgb..gb&steps=rgbbbgrg&goal=0_0_6_0_"
creators = "kattun"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 6"

[[entries]]
id = 415
query = "field=0_rr....bb....gg....rr...bbbr.&steps=brgrgbrb&goal=0_0_5_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 7"

[[entries]]
id = 416
query = "field=0_yrg.ryrrrgyrrggrryy&steps=rrryryryrr&goal=0_0_7_0_"
creators = "えむてぃ"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 8"

[[entries]]
id = 417
query = "field=0_oorrbbooroobbbooorbooorrrooboorrbboo&steps=brrrbbbr&goal=_0"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Normal 9"

[[entries]]
id = 418
query = "field=0_r.....bb..rryy.brbbybb&steps=rbrbrbybrb&goal=0_0_6_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 1"

[[entries]]
id = 419
query = "field=0_bbb..bggg..ryyyggybbbgryggyyyrrbgrryrbgybybyybbrbrryrr&steps=rybgrgryrb&goal=0_0_15_0_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 2"

[[entries]]
id = 420
query = "field=0_r.....o.....g..y..rgrygggrrrrryyy&steps=ygyrrrggyr&goal=0_0_7_0_"
creators = "colo"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 3"

[[entries]]
id = 421
query = "field=0_bbbrrrygygygygygygrrrbbbygygygygygygbbbrrr&steps=ryrbgybyrb&goal=2_2_19_1_"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 4"

[[entries]]
id = 422
query = "field=0_g.....gb.o.rrrgggyyyrrrbbb&steps=bbbyggbrgr&goal=0_0_7_0_"
creators = "colo"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 5"

[[entries]]
id = 423
query = "field=0_ooooooobbyyoobrryooggrgoogyggooryyboorrbbooooooo&steps=ryrgrbrgrbry&goal=0_0_9_0_1"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Hard 6"

[[entries]]
id = 424
query = "field=0_grybgrgrybgrgrybgroooooooooooooooooorggrrgrrgrggoooooobbbyyygrybgr&steps=ybrbyygbygbbybyr&goal=_0"
creators = "ウァルト"
source = "2014年度駒場祭ぷよぷよ大会"
sourceDetail = "Despair"
