[[entries]]
query = "field=0_g....gg....rr....rbr...gbr...byb...byb...yry...yrr...&steps=rr&goal=1_2_3_0_"
creators = "かれーぱん"
source = "新大祭2015"
sourceDetail = "No.01"

[[entries]]
query = "field=0_b....yybrr.bbrggg&steps=yygr&goal=0_0_4_0_"
creators = "m@s"
source = "新大祭2015"
sourceDetail = "No.02"

[[entries]]
query = "field=0_b..r..b..b..g.rr.&steps=gggbbr&goal=0_0_3_0_"
creators = "さくらす"
source = "新大祭2015"
sourceDetail = "No.03"

[[entries]]
query = "field=0_b.....b....ro....oo....oo....oo....oo....oo....ob....rb....rb....r&steps=rrrr&goal=0_0_2_0_"
creators = "たまごやき"
source = "新大祭2015"
sourceDetail = "No.04"

[[entries]]
query = "field=0_r.....grr...ygg...ryy...grr...bgg...ybb...byy&steps=brgyrgbybb&goal=0_0_8_0_"
creators = "Mimi"
source = "新大祭2015"
sourceDetail = "No.05"

[[entries]]
query = "field=0_g.....r.....rgb...rbb.oooooo&steps=gbgr&goal=0_0_3_0_"
creators = "iko"
source = "新大祭2015"
sourceDetail = "No.06"

[[entries]]
query = "field=0_b.....by....brb...rgrb..rgrb..rgrb..&steps=yyrbgryy&goal=0_0_6_0_"
creators = "REF"
source = "新大祭2015"
sourceDetail = "No.07"

[[entries]]
query = "field=0_g.....b...gggryybbbrbygygbggyggbrrgyy&steps=bryyrrgr&goal=0_0_9_0_0"
creators = "しょこら"
source = "新大祭2015"
sourceDetail = "No.08"

[[entries]]
query = "field=0_oo....oo....oo....ro.y..bo.g..rb.o.ybbooogryoooorroooobgoooobboooorryyoorgggyo&steps=gygybb&goal=0_0_8_0_"
creators = "しょこら"
source = "新大祭2015"
sourceDetail = "No.09"

[[entries]]
query = "field=0_g.....y.....yy.rrggrrbrygbrbbyybb&steps=rbybyr&goal=0_0_7_0_"
creators = "m@s"
source = "新大祭2015"
sourceDetail = "No.10"

[[entries]]
query = "field=0_g.....b.....r...g.yr..gyyg..grbg..rryr&steps=bbbbrgbgbr&goal=0_0_7_0_"
creators = "たまきち"
source = "新大祭2015"
sourceDetail = "No.11"

[[entries]]
query = "field=0_y.....y.....b.....g.....r....gr...brb..brbb..byrr&steps=rgygrb&goal=0_0_6_0_"
creators = "REF"
source = "新大祭2015"
sourceDetail = "No.12"

[[entries]]
query = "field=0_g.....ygr...ygr...yrg...bgrg..bgrg..bgrg..&steps=brgygr&goal=0_0_7_0_"
creators = "REF"
source = "新大祭2015"
sourceDetail = "No.13"

[[entries]]
query = "field=0_rgbb..rrgrbbggbbrbrrrbrr&steps=rbrbrb&goal=2_2_11_0_"
creators = "かれーぱん"
source = "新大祭2015"
sourceDetail = "No.14"

[[entries]]
query = "field=0_brb.r.bbrbb.rrbrrr&steps=rro2_2_2_2_2_2orrrrrr&goal=_3"
creators = "かれーぱん"
source = "新大祭2015"
sourceDetail = "No.15"

[[entries]]
query = "field=0_b.....g.bbg.gbbbb.bggggbbgb&steps=ggggbg&goal=_2"
creators = "かれーぱん"
source = "新大祭2015"
sourceDetail = "No.16"

[[entries]]
query = "field=0_o.....o....oo..ooooooooogoooorggygogbbbyggryybbbrbbgyrbggyrrbrrgyy&steps=bryrrrbrgyyy&goal=_0"
creators = "しょこら"
source = "新大祭2015"
sourceDetail = "No.17"

[[entries]]
query = "field=0_r.....g.....r.....b..o.bbgroyyyggrbgrrrbbgr&steps=gryrbrbrgr&goal=0_0_8_0_0"
creators = "しょこら"
source = "新大祭2015"
sourceDetail = "No.18"

[[entries]]
query = "field=0_y....yy....rr....by....bb...byyyrggrbryygrrbrrybbrggy&steps=brgbryggbbgr&goal=0_0_11_0_"
creators = "にわとり"
source = "新大祭2015"
sourceDetail = "No.19"

[[entries]]
query = "field=0_rr....br....ry....yb....yb....yb..oooooooooooo&steps=yyyrrryr&goal=0_0_5_0_"
creators = "かれーぱん"
source = "新大祭2015"
sourceDetail = "No.20"

[[entries]]
query = "field=0_gg....oooooorrrgggoooooogggrrr&steps=rggrrrggrr&goal=0_0_6_0_"
creators = "REF"
source = "新大祭2015"
sourceDetail = "No.21"

[[entries]]
query = "field=0_r.....go....ggo...rbg.ybrrbggybbgryyrrrbbb&steps=ggggbbybgb&goal=0_0_9_0_"
creators = "しょこら"
source = "新大祭2015"
sourceDetail = "No.22"

[[entries]]
query = "field=0_o.....oo....oo...gbbo.robborrobboooogrrooggrbbgybbggybbbrrgyy&steps=ggbrrrgbgr&goal=0_0_10_0_0"
creators = "しょこら"
source = "新大祭2015"
sourceDetail = "No.23"

[[entries]]
query = "field=0_&steps=rrrrbbbbrrrrbbbbbbbbrrrrrrrrrbrbrbrbbbrrbbrrrbrbrbrbrbrbrbrbrrrr&goal=0_0_16_0_"
creators = "REF"
source = "新大祭2015"
sourceDetail = "No.24"
