[[entries]]
query = "field=0_rgby..rgby..rgby.&steps=byrg&goal=0_0_4_0_0"
creators = "sample"
source = "新大祭2017"
sourceDetail = "No.0"

[[entries]]
query = "field=0_rrr...yyyr..rrrg..gggbb.&steps=yrbb&goal=_2"
creators = "ギンパチ"
source = "新大祭2017"
sourceDetail = "No.1"

[[entries]]
query = "field=0_oo.oooogggooooooooobbbooooooooorrrooooooooooyooo&steps=rybygy&goal=_6"
creators = "M@S"
source = "新大祭2017"
sourceDetail = "No.2"

[[entries]]
query = "field=0_r.r...r.ro..r.oo.ro.orroo.oorry.yyoyy.yorro.oorrr.oor&steps=yyyr&goal=2_0_24_0_"
creators = "M@S"
source = "新大祭2017"
sourceDetail = "No.3"

[[entries]]
query = "field=0_yr...bgyr..bgyr..bgyr.&steps=bygr&goal=0_0_4_0_0"
creators = "M@S"
source = "新大祭2017"
sourceDetail = "No.5"

[[entries]]
query = "field=0_rrr...gyb...gyb...gyb.&steps=rgby&goal=0_0_4_0_"
creators = "だいや"
source = "新大祭2017"
sourceDetail = "No.7"

[[entries]]
query = "field=0_g....rr....brb...bbr...gggrr.&steps=gggrgr&goal=0_0_5_0_"
creators = "かれぱん"
source = "新大祭2017"
sourceDetail = "No.8"

[[entries]]
query = "field=0_rrr...ggg...bbb...ggg...rrryyy&steps=grbgry&goal=0_0_6_0_"
creators = "M@S"
source = "新大祭2017"
sourceDetail = "No.9"

[[entries]]
query = "field=0_bb....bggybbgrrryy&steps=bygrbb&goal=0_0_5_0_"
creators = "たまきち"
source = "新大祭2017"
sourceDetail = "No.10"

[[entries]]
query = "field=0_r.....y....rr..rggy..grrryy&steps=gyryyy&goal=0_0_5_0_"
creators = "たまきち"
source = "新大祭2017"
sourceDetail = "No.12"

[[entries]]
query = "field=0_brbrbbbbrbrbrrbbrr&steps=rrrbrb&goal=0_0_6_0_"
creators = "だいや"
source = "新大祭2017"
sourceDetail = "No.13"

[[entries]]
query = "field=0_y....rpp..rprp..pryy..rroy&steps=pppyrr&goal=0_0_5_0_"
creators = "たまきち"
source = "新大祭2017"
sourceDetail = "No.17"

[[entries]]
query = "field=0_rr..yyyy..rrbb..yyyy.bbb&steps=rbbyyrrb&goal=_0"
creators = "だいや"
source = "新大祭2017"
sourceDetail = "No.18"

[[entries]]
query = "field=0_g.....g.....r.....r..yb.rggbybbrbyybbbrrrb&steps=yybybbry&goal=0_0_8_0_"
creators = "だいや"
source = "新大祭2017"
sourceDetail = "No.19"

[[entries]]
query = "field=0_rrrbbryyybrrbbbyybrrrybb&steps=rbbyyrrb&goal=0_0_8_0_"
creators = "だいや"
source = "新大祭2017"
sourceDetail = "No.20"

[[entries]]
query = "field=0_rbrrbrrrbbrrbborbbrrrorr&steps=rbrbrbrrbb&goal=2_2_15_0_"
creators = "だいや"
source = "新大祭2017"
sourceDetail = "No.22"
