[[entries]]
query = "field=0_yyggg.yoooo.oobbb.royyy.rrooo.ooggg.&steps=byrgyg&goal=0_2_6_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第1問"

[[entries]]
query = "field=0_h.....p.....r....rp....hh....pr....ppr...rhr...rph..rhhp..hprp.&steps=rprprp&goal=0_0_4_1_0"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第2問"

[[entries]]
query = "field=0_g....yy....gy....gb....gyg...yybg..bbgg..&steps=ygggyg&goal=0_2_6_0_"
creators = "きゅい"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第3問"

[[entries]]
query = "field=0_y.....p.....y....yygy..pggy..pypp..&steps=pypgpy&goal=0_0_5_0_"
creators = "しろま"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第4問"

[[entries]]
query = "field=0_bb....br....rrb..ggyy.yygry.ggrbb.yyrrb.&steps=gygbgr&goal=_0"
creators = "わんりゅう"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第5問"

[[entries]]
query = "field=0_orrorrbrooorbboobborobrbrrbbrr&steps=brbrbr&goal=_0"
creators = "ウァルト"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第6問"

[[entries]]
query = "field=0_r....rgby..rgby..gbyr..rgby..&steps=rryyyy&goal=0_0_5_0_0"
creators = "easis"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第7問"

[[entries]]
query = "field=0_r.....bby...ryb.rrgyg.rggrr.yyygrg&steps=gbgyry&goal=0_0_7_0_"
creators = "凸凹マスター"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第8問"

[[entries]]
query = "field=0_gbry..bbrr.oooooooggyyobbbrrr&steps=gbrbry&goal=0_0_6_0_"
creators = "mino"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第9問"

[[entries]]
query = "field=0_r.yy..r.by..ybbr..yyrr.&steps=ryrbry&goal=0_0_5_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第10問"

[[entries]]
query = "field=0_oy.royyorooyryoryoroyorroryyor&steps=ryyrry&goal=0_0_6_0_0"
creators = "PRRN"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第11問"

[[entries]]
query = "field=0_r.....r.y...ggy...gog...oro...yyyg..rrryyy&steps=ggryrg&goal=0_0_6_0_"
creators = "けんろう"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第12問"

[[entries]]
query = "field=0_b.....rrr...bgy...bbg...ggy...rbr...rrbr..bbrrgg&steps=yyggrr&goal=0_0_8_0_"
creators = "りさ"
source = "新春なぞぷよ大会2014"
sourceDetail = "中辛 第13問"

[[entries]]
query = "field=0_rrbg..rygg..byyr..bbrr.&steps=rybbbbgr&goal=0_2_6_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第1問"

[[entries]]
query = "field=0_b.....b....hgb...bgg...ghbb..gbhhg.hhbghg&steps=gbgbgbgb&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第2問"

[[entries]]
query = "field=0_g.....y.....y.....bbbg.ggrybbbggryggrryygb&steps=ygbgygyb&goal=0_0_8_0_"
creators = "きゅい"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第3問"

[[entries]]
query = "field=0_b.....b.....r.....r.....br..rryr..bbybb&steps=bbbybrby&goal=0_0_5_0_"
creators = "しろま"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第4問"

[[entries]]
query = "field=0_b.....br...ggb...rgo...rro...ggog..gbbr..rrbrr.grgbb.gbggb&steps=bbgrgggr&goal=_0"
creators = "わんりゅう"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第5問"

[[entries]]
query = "field=0_r...hoh...pyb...ypp...ypb...rbb..ohoh..ggyyr.rgygr.rrggr&steps=rygyrrrg&goal=0_0_8_0_0"
creators = "ウァルト"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第6問"

[[entries]]
query = "field=0_o.....or....boo...rbgooorbgoyorbgbyyooob&steps=ryrbgbrr&goal=0_0_6_0_0"
creators = "easis"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第7問"

[[entries]]
query = "field=0_y.....g....yy..b.oy..b.rb..ryyy..orbbb.orrgg.rbobyyrrbggg&steps=gybbgyby&goal=0_0_10_0_"
creators = "凸凹マスター"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第8問"

[[entries]]
query = "field=0_g.....gg....by....bby...yyrb..yrrb&steps=ybbrygyb&goal=0_0_6_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第10問"

[[entries]]
query = "field=0_o.b...y.r...r.gg..y.yr..y.gg..rrrbrrbgyyorbgybbo&steps=bgryrbgr&goal=_0"
creators = "PRRN"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第11問"

[[entries]]
query = "field=0_ooooo.bbbgg.rgrgrorgrbrorgbbr&steps=rbrgrgrb&goal=0_0_6_0_"
creators = "けんろう"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第12問"

[[entries]]
query = "field=0_o.....o.....o.....b.b...rrr...bgy...bbg...ggy...rbry..rrbr..bbrrgg&steps=bbygrbrg&goal=0_0_9_0_"
creators = "りさ"
source = "新春なぞぷよ大会2014"
sourceDetail = "激辛 第13問"
