[[entries]]
query = "field=0_bg....bg....bg..gggbbbrrryyy&steps=ygbrbg&goal=0_0_6_0_"
creators = "mtsd"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第2問"

[[entries]]
query = "field=0_grrgbbgrbggbgbbrrr&steps=grgbrb&goal=0_0_6_0_"
creators = "かにすけ"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第3問"

[[entries]]
query = "field=0_r..y..r..yy.y..bbby..hooo..ybby..yrry&steps=bybyby&goal=0_0_5_1_0"
creators = "PRRN"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第4問"

[[entries]]
query = "field=0_gbggg.gbbyy.gooyg.yyobg.gybbg.ggyyy.&steps=gygygy&goal=_0"
creators = "ウァルト"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第5問"

[[entries]]
query = "field=0_y....ryy..prro.rppooyrrooyyyooyy&steps=yrypyr&goal=0_0_6_0_0"
creators = "穴ぼこのにんじん"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第6問"

[[entries]]
query = "field=0_h....yg....yr....gr....gyr...gbrygybbygyyyyrrgg&steps=yrybyr&goal=_0"
creators = "わんりゅう"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第7問"

[[entries]]
query = "field=0_ryb...byb..gbyb..gbrr..gyyyg&steps=ygrbyb&goal=0_0_6_0_"
creators = "きゅい"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第8問"

[[entries]]
query = "field=0_p.p...pbrb.bbprbpppbrb&steps=bprpbp&goal=0_0_5_0_"
creators = "しろま"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第9問"

[[entries]]
query = "field=0_y..g.yybrggobbrrorooooyrrooyyooo&steps=bryryg&goal=0_0_6_0_"
creators = "だっち"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第10問"

[[entries]]
query = "field=0_r.....g.rb..ggbr..rrbb.bgggobb&steps=rgrgrb&goal=0_3_5_0_"
creators = "Sera"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第11問"

[[entries]]
query = "field=0_y....gg...yog...ygy...oyy...ogr...ggr...oyr...oyy...yrr...yyo.&steps=yyyrgy&goal=0_0_6_1_3"
creators = "りさ"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第12問"

[[entries]]
query = "field=0_y.....yb....ygb...ggrr..byry..bbyy.&steps=rbgbyb&goal=0_0_6_0_"
creators = "まてりあ"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第13問"

[[entries]]
query = "field=0_b.....g.....b....ggbg.bgrrg.bbryyy&steps=gbbrgy&goal=0_0_6_0_"
creators = "のの"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第14問"

[[entries]]
query = "field=0_r.....g.....g....bg....gr....rbg...rbg..brbgh.bbrrr&steps=rbrrrg&goal=0_0_6_1_"
creators = "飛車ちゅう"
source = "夏季なぞぷよ大会2015"
sourceDetail = "中辛 第15問"

[[entries]]
query = "field=0_bg....bg.o..bg.hgggbbbrrryyy&steps=gygbgrgb&goal=0_0_6_0_0"
creators = "mtsd"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第2問"

[[entries]]
query = "field=0_oobb..ooyy..rroy..rogg..ooog..oobb..rrob..royy..oooy..&steps=yrgbbrby&goal=0_0_6_1_0"
creators = "かにすけ"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第3問"

[[entries]]
query = "field=0_y.....y....gg....gy....ryogy.rryyo.byoyg.bbygg.ggooo.ygyoy.&steps=rygygbyy&goal=_0"
creators = "PRRN"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第4問"

[[entries]]
query = "field=0_p.p...ggyy..bbrr..yygg..rrbb..ggyy..bbrr..yygg..rrbb.&steps=ygyrbrbg&goal=1_0_2_0_"
creators = "ウァルト"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第5問"

[[entries]]
query = "field=0_r....yg.r.grrrg.ggygg.oooyy.ogooy.ooooo.&steps=ggygygyr&goal=0_0_5_1_2"
creators = "穴ぼこのにんじん"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第6問"

[[entries]]
query = "field=0_h.....r.by..byyyrrbbobggyoobbyyooorroooooooo&steps=rgrgryby&goal=_0"
creators = "わんりゅう"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第7問"

[[entries]]
query = "field=0_r.....g....yrg...ror...ryr...oro...gyor..ggrr.&steps=grgygggr&goal=0_0_6_0_"
creators = "きゅい"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第8問"

[[entries]]
query = "field=0_p....rgg...roo..gggpp.oooop.pppggg&steps=rgpgggrg&goal=0_0_6_0_"
creators = "しろま"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第9問"

[[entries]]
query = "field=0_ryybbgrrybggoooooorgggyyrrbbby&steps=rygrbgyb&goal=0_0_8_0_"
creators = "だっち"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第10問"

[[entries]]
query = "field=0_r..p.pprbppprpbbrrrpprr&steps=rprbrprp&goal=0_0_7_0_"
creators = "Sera"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第11問"

[[entries]]
query = "field=0_orrr..bbbo..oyyy..bbbo..oyyy..hbbo..oyyy..bbbo..orrr.&steps=yrybrbyb&goal=0_0_7_1_2"
creators = "りさ"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第12問"

[[entries]]
query = "field=0_y.....b.....b.....rry...ryy...bbr..yyrr..&steps=rybybbrb&goal=0_0_6_0_"
creators = "まてりあ"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第13問"

[[entries]]
query = "field=0_y.g...g.y..yb.y..ggyb..gbbg.oobgg.y&steps=yybbbygy&goal=0_0_6_0_"
creators = "のの"
source = "夏季なぞぷよ大会2015"
sourceDetail = "激辛 第14問"
