[[entries]]
query = "field=0_g.....r...bgrg..gbrb..grhr..bbgg.rrbghrrbhhrr&steps=bgrgbr&goal=_0"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第1問"

[[entries]]
query = "field=0_r.....b.....r.....bo....rr...bob...bbr...hrb...rbrb..brbr.rbrbrb&steps=brrbbr&goal=0_0_3_1_0"
creators = "PRRN"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第2問"

[[entries]]
query = "field=0_b.....o....bg....bg....rr....gg...rgy...byy...ooo...bbb...ggg.&steps=brygrg&goal=0_4_5_1_"
creators = "mtsd"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第3問"

[[entries]]
query = "field=0_y.....yy....ogg...bgy...bby...oyo...ggb...ygbb.&steps=ygybgb&goal=1_0_3_0_"
creators = "redeye"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第4問"

[[entries]]
query = "field=0_y..y..rrry..yyyr..rrry..oooo..yyrr..yryr..rryy.&steps=yryryr&goal=2_2_16_0_"
creators = "えんぢゃ"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第5問"

[[entries]]
query = "field=0_y.....y..yrrh..yryr..yppy..prryy.&steps=yrypyr&goal=0_0_6_0_"
creators = "穴ぼこのにんじん"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第6問"

[[entries]]
query = "field=0_p.....p.....hp....bphbbbbhpppppphbbbbbppp&steps=bpbbbp&goal=0_0_5_1_0"
creators = "こなた"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第7問"

[[entries]]
query = "field=0_b...bbyy..ybgy..yygg..bbrr..brbr..rrbb.&steps=ygrbrb&goal=_0"
creators = "ウァルト"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第8問"

[[entries]]
query = "field=0_bb...yyb...ygg...rrg...rbb...yyb...ygg...rrg...rbbb..&steps=ryyggb&goal=1_2_3_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第9問"

[[entries]]
query = "field=0_r....rrb..rgbb..gbgg..ggbg..rrbb..rggg.&steps=rgbgbr&goal=0_0_6_1_"
creators = "りさ"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第10問"

[[entries]]
query = "field=0_b.....g.....g....ry...yyg.b.yoo.y.grh.yyrroyrrgggyyr&steps=rbgyby&goal=0_0_8_0_"
creators = "凸凹マスター"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第11問"

[[entries]]
query = "field=0_y.....b.....b.....b.....y.....yr....yr....br....yy..rrrbb.&steps=rybrby&goal=0_0_6_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第12問"

[[entries]]
query = "field=0_bb....rrb...bor...rrb...brb...rbr...brb..&steps=rrbbrb&goal=_0"
creators = "わんりゅう"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第13問"

[[entries]]
query = "field=0_gg....yg....yy....bb....gb....ggbb.&steps=bgbybg&goal=0_0_5_0_"
creators = "Sera"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第15問"

[[entries]]
query = "field=0_g....yy....yg....bb.ogggb.h&steps=gygggb&goal=0_0_4_0_0"
creators = "platinum"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第16問"

[[entries]]
query = "field=0_g.....r.....rg..r.gr..r.bbr.b.bro.bgrrh.bbggorr&steps=bgrrbg&goal=0_0_7_0_"
creators = "飛車ちゅう"
source = "新春なぞぷよ大会2016"
sourceDetail = "中辛 第17問"

[[entries]]
query = "field=0_g..r..g..g..h..g..g.hr..rrgg..rhog..ggrr..orhg..rrggrggghrr&steps=rgrrrgrg&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第1問"

[[entries]]
query = "field=0_r.....g.....r.....gh...ghg...hgh..ggrgg.ghrhg.hrhrh.ghrhg.ggrgg.&steps=grrggrrg&goal=0_0_4_1_0"
creators = "PRRN"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第2問"

[[entries]]
query = "field=0_b....bb....rg....rg...yyr...ygg...rgy...byy...ooo...bbb...ggg...rrr.&steps=rbyrygbg&goal=0_0_5_1_5"
creators = "mtsd"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第3問"

[[entries]]
query = "field=0_r.....hbb...orb...hgg...ogr...hrbb..rgrb..ggyy.&steps=gyrbrygb&goal=_0"
creators = "redeye"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第4問"

[[entries]]
query = "field=0_ryry..yryr..ryry..yryr..ryry..yryr..ryry..oror..roro.&steps=rrryrrry&goal=2_2_20_0_"
creators = "えんぢゃ"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第5問"

[[entries]]
query = "field=0_yr...yyoy..rryy..rorr..ppyr..&steps=prpryrrr&goal=0_0_6_0_"
creators = "穴ぼこのにんじん"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第6問"

[[entries]]
query = "field=0_b.....byrr..gggbb.yyyrb.gggrr.&steps=rbrbggrb&goal=0_0_7_0_"
creators = "ウァルト"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第8問"

[[entries]]
query = "field=0_gg...rrg...rbb...yyb...yggby.rrgryyrbbbrr&steps=ryrgbgry&goal=0_2_8_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第9問"

[[entries]]
query = "field=0_rrryy.yhhhy.yoyyr.yhyhr.rrrhr.hhhhy.rrryy&steps=ryryryry&goal=0_0_7_0_"
creators = "りさ"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第10問"

[[entries]]
query = "field=0_b.....g.....g.....h.....gbb.o.yrb.b.byy.yyoyr.ryorr.orogoyyyogg&steps=rrgygbby&goal=0_0_9_0_"
creators = "凸凹マスター"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第11問"

[[entries]]
query = "field=0_y.....y.....rg...grg...grg...rbb...rrb.&steps=rgygybrg&goal=0_0_6_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第12問"

[[entries]]
query = "field=0_p....ypy.pgpyy.pygpp.yyggp.&steps=pypgpppy&goal=0_0_6_0_0"
creators = "わんりゅう"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第13問"

[[entries]]
query = "field=0_gryy..rgbb..brbg..ybry..byyr..byrg..grgy..rggb..yrbb.&steps=yygygbby&goal=_3"
creators = "へみおす"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第14問"

[[entries]]
query = "field=0_rr....rb....yb....yy....rr....br....by....yy..&steps=rbybrbyb&goal=0_0_6_0_"
creators = "Sera"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第15問"

[[entries]]
query = "field=0_b.gg..bbyy..rrrb.yyybb.&steps=bygygrby&goal=0_0_6_0_"
creators = "platinum"
source = "新春なぞぷよ大会2016"
sourceDetail = "激辛 第16問"
