[[entries]]
id = 570
query = "field=0_r.....b.....g.....rgr..bbbg..ggrr..rgrg.rrbbgg&steps=bgbrgr&goal=0_0_6_1_"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第2問"

[[entries]]
id = 571
query = "field=0_b.....r.....r.....r.....b.....r.....g.....g....br....br..yyyrbb&steps=bygbrg&goal=0_0_6_0_"
creators = "しろま"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第3問"

[[entries]]
id = 572
query = "field=0_r...brr.o.yby.yyrybbbbrry&steps=ybbryr&goal=0_2_6_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第4問"

[[entries]]
id = 573
query = "field=0_h.....rrry..ggyy..grrr..yyyh.rrrggg&steps=grygry&goal=0_0_3_0_0"
creators = "iso"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第5問"

[[entries]]
id = 574
query = "field=0_g.....g.....r.....r.....o.....r...grg...rro..&steps=grgggr&goal=0_0_4_0_"
creators = "redeye"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第6問"

[[entries]]
id = 575
query = "field=0_y....pp...yyp...ggy...gppp..yggrrr&steps=pypyry&goal=0_0_5_1_0"
creators = "くだら"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第7問"

[[entries]]
id = 576
query = "field=0_gb....yy..b.by..bbrrrrrrggg&steps=rbbbry&goal=0_0_6_0_"
creators = "ウァルト"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第8問"

[[entries]]
id = 577
query = "field=0_b.....r.....gg....gbg..brrb..brgb..rhgg.&steps=rbrbrg&goal=0_0_6_0_"
creators = "mtsd"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第9問"

[[entries]]
id = 578
query = "field=0_bb....yb....yy...bbg...ggyyy&steps=bgbyby&goal=0_0_5_0_"
creators = "Sera"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第10問"

[[entries]]
id = 579
query = "field=0_g.....g....bbb..boyy..gggy.yyybbb&steps=ybgggy&goal=0_0_6_0_"
creators = "せりー"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第11問"

[[entries]]
id = 580
query = "field=0_g....prg..rropg.ggppggrrrog&steps=grgpgr&goal=0_0_5_0_"
creators = "こなた"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第12問"

[[entries]]
id = 581
query = "field=0_r.....r.....yr....ybbr..ybrry.gggyy&steps=yrgbyr&goal=0_0_6_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第13問"

[[entries]]
id = 582
query = "field=0_yr....yb....by....bbo...ryy...rry&steps=ryryrr&goal=1_0_3_0_"
creators = "貧弱PC"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第14問"

[[entries]]
id = 583
query = "field=0_rr....bb....rr....br...boor.rbbrrbrroobb&steps=bbrb&goal=0_0_5_0_"
creators = "りさ"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第15問"

[[entries]]
id = 584
query = "field=0_y.....yrr...obr...rbb.bbbyy.&steps=rbrrrb&goal=0_0_5_0_"
creators = "platinum"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第16問"

[[entries]]
id = 585
query = "field=0_r....bb.bb.brbgb.rrggo&steps=rrrgrb&goal=0_0_5_0_"
creators = "りさ"
source = "新春なぞぷよ大会2017"
sourceDetail = "中辛 第17問"

[[entries]]
id = 586
query = "field=0_r.....gg...brr...bbgb..ggrr..rgrg.rrbbggbhhhhb&steps=brgrbrgr&goal=0_0_4_1_0"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第2問"

[[entries]]
id = 587
query = "field=0_y.....p.....y.....yp....gp...ggp...ppy...ygg.&steps=ypyggpgy&goal=0_0_6_0_"
creators = "しろま"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第3問"

[[entries]]
id = 588
query = "field=0_y.....r....ry.r..yr.y..bbbr.&steps=ryyyryrb&goal=0_2_5_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第4問"

[[entries]]
id = 589
query = "field=0_h....yy....rrr..bbbh..rhhr..brrb.rrbbrrryrryr&steps=ybbryrrb&goal=2_0_17_0_"
creators = "iso"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第5問"

[[entries]]
id = 590
query = "field=0_o.....g.....g.....o.....r.....o.....r.....g.....g...rro..&steps=rrgrgggr&goal=0_0_4_0_"
creators = "redeye"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第6問"

[[entries]]
id = 591
query = "field=0_y.....y.y...y.y...g.ry..g.rgg.g.rgygyrgyryyryyggg&steps=yyrygy&goal=2_0_15_0_"
creators = "くだら"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第7問"

[[entries]]
id = 592
query = "field=0_bb...ggbgg.rgrrg.rbbrbborbggbhorrgo&steps=gbgrgbbr&goal=_0"
creators = "ウァルト"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第8問"

[[entries]]
id = 593
query = "field=0_rg....rb....bb...gggr..roor..gggr.&steps=bbrbgbrb&goal=0_0_6_0_"
creators = "mtsd"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第9問"

[[entries]]
id = 594
query = "field=0_rgr...bbboorbbgrrggggrgbb&steps=bgbbbrbr&goal=0_3_7_0_"
creators = "Sera"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第10問"

[[entries]]
id = 595
query = "field=0_y.....rg....yr...rby...ygo...grr...gry..rbgr..rbgg..&steps=brygyryr&goal=0_0_6_1_"
creators = "せりー"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第11問"

[[entries]]
id = 596
query = "field=0_ggh...bby...yyg...bbbgg.ggyyy.&steps=bgybbgyb&goal=0_0_4_1_0"
creators = "こなた"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第12問"

[[entries]]
id = 597
query = "field=0_r....gb....rb....by....bb....rrb...ryy...gby...ggb...rrr..&steps=ybbbyyyb&goal=0_0_8_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第13問"

[[entries]]
id = 598
query = "field=0_by..rrrgggbbbyyyyyygggrrrbbb&steps=bgryrrrg&goal=0_0_8_0_"
creators = "貧弱PC"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第14問"

[[entries]]
id = 599
query = "field=0_yrrg..yygg..ggbb..grby..rryy.&steps=rgyyrbrg&goal=0_0_7_0_"
creators = "りさ"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第15問"

[[entries]]
id = 600
query = "field=0_bb....gg.g..ybrrg.yrbbg.ybyyy&steps=rbgbgygy&goal=0_0_7_0_"
creators = "platinum"
source = "新春なぞぷよ大会2017"
sourceDetail = "激辛 第16問"
