[[entries]]
query = "field=0_pb.pb.bp.pb.oo.oo.pb.pb.pb.bp.oo.oo.bp.bb.pb.pp.oo.oo.bb.bp.pp.pb.&steps=pbppbbpbppbbpbpb&goal=0_0_8_0_0"
creators = "π"
title = "コラプサー"
source = "早大なぞぷよマスターズ2020"
sourceDetail = "第40問"
