[[entries]]
query = "field=0_b...g.r..bb.r..rggb..rrbb.&steps=rrbgbr&goal=0_0_5_0_"
creators = "りさ"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第1問"

[[entries]]
query = "field=0_y....yy...yrgy..yyyy..rrgg.gggrrr&steps=yrgrgr&goal=0_0_4_0_0"
creators = "PRRN"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第2問"

[[entries]]
query = "field=0_ggy...yybb..bbyy..ggbg..yyyg.&steps=gbbygb&goal=0_0_5_0_0"
creators = "こなた"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第3問"

[[entries]]
query = "field=0_r.....y....rbrr..bbrb..yybb.&steps=rbyrbr&goal=0_0_5_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第4問"

[[entries]]
query = "field=0_y.....rb....rry...byb...rrbr..brbr..ryry..bbrr..rbyb..ryyb.&steps=bryrbr&goal=0_0_8_1_"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第5問"

[[entries]]
query = "field=0_b...ybb...yyrr..rbry.rrbbyy&steps=rrybyb&goal=_0"
creators = "ウァルト"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第7問"

[[entries]]
query = "field=0_gg....ygy...gyy.ygrrr.yybbb.&steps=bgrgyg&goal=0_0_6_0_"
creators = "platinum"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第8問"

[[entries]]
query = "field=0_b.y...r.r...r.r...yyb...ybb...rrr...ybb...yyb...rrr..byyby.bybby.&steps=rbryby&goal=_0"
creators = "iso"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第9問"

[[entries]]
query = "field=0_y.....y.....b.....b.....y.....by..b.rr..byyr..rbyb..rrbb.&steps=ybrbrb&goal=0_0_7_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第10問"

[[entries]]
query = "field=0_r....yb....yy....br....rr....yy...rby..&steps=yrbryr&goal=0_0_5_0_"
creators = "redeye"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第11問"

[[entries]]
query = "field=0_b....bg....rb....grbbgbbbgrgrrrbbg&steps=grbgrb&goal=0_0_7_0_"
creators = "π"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第12問"

[[entries]]
query = "field=0_br....gg....rg.r..bb.ggbbrrrbb&steps=grbgrg&goal=0_0_6_0_"
creators = "くだら"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第13問"

[[entries]]
query = "field=0_bb....rbg...ggrg..grrgg.&steps=brrrgr&goal=0_0_5_0_"
creators = "貧弱PC"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第14問"

[[entries]]
query = "field=0_b....rgg...brr...gbg..bbgg..grbr.&steps=brrrgb&goal=0_0_6_0_"
creators = "mtsd"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第15問"

[[entries]]
query = "field=0_b.....b....byb...yry..yrry..ybbb..&steps=ybrbyb&goal=0_0_5_0_"
creators = "platinum"
source = "新春なぞぷよ大会2018"
sourceDetail = "中辛 第16問"

[[entries]]
query = "field=0_g..g..bbrr..boor..rggb..rrbb.&steps=grgbgrgb&goal=0_0_6_0_"
creators = "りさ"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第1問"

[[entries]]
query = "field=0_yg....gy....yp....py....ho...rgpr..rrrrhogypygyygygg&steps=gryggyyg&goal=_0"
creators = "PRRN"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第2問"

[[entries]]
query = "field=0_y.....y..b.yh.gopbg.oppgb.ggygbbpppogo&steps=gbybpbpg&goal=0_0_6_0_6"
creators = "こなた"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第3問"

[[entries]]
query = "field=0_ggb...grrbg.yyryggybbbyy&steps=brbgbyyg&goal=0_2_7_0_"
creators = "かにすけ"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第4問"

[[entries]]
query = "field=0_b.....r.....r.....b.r...rby...rbby..ryry..bbrr..rbyb.rryybbhhhhhh&steps=bryryrbr&goal=_0"
creators = "可憐な私(笑)"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第5問"

[[entries]]
query = "field=0_r....yy....rrr..yyrp..pyyrryyryrooyrypooprrrryyy&steps=yrprypyr&goal=0_0_8_0_7"
creators = "ウァルト"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第7問"

[[entries]]
query = "field=0_gggb..rrrb..gyyyg.gbbgg.grrbb&steps=rbgyrbrg&goal=_0"
creators = "platinum"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第8問"

[[entries]]
query = "field=0_h...bbb...hyyy..rrrb..hbbh..rhhr..brrb.rrbbrrryrryr&steps=brybyrrb&goal=2_1_6_0_"
creators = "iso"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第9問"

[[entries]]
query = "field=0_y.....y.....b.b.rrb.y.rgr.rgygg.rgyybbbg&steps=rygygbbr&goal=0_0_8_0_"
creators = "まてりあ"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第10問"

[[entries]]
query = "field=0_y.....yrr...oyy...rhh...rbb...ooyy.&steps=yrbrbryr&goal=0_0_5_0_"
creators = "redeye"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第11問"

[[entries]]
query = "field=0_r.r...o.y...r.y...o.b...r.b..&steps=ybyrrrbr&goal=0_0_4_0_"
creators = "π"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第12問"

[[entries]]
query = "field=0_g.....r.....b.....b...r.g.r.g.bgr.grbbr&steps=bggrrbbg&goal=0_0_6_0_"
creators = "くだら"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第13問"

[[entries]]
query = "field=0_br....oo...rbrb..bbrr.&steps=bbrrbr&goal=0_0_4_0_"
creators = "貧弱PC"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第14問"

[[entries]]
query = "field=0_r.....r...r.gh..r.og..o.rr..o.gh..r.go..rrhg..oghg..ggrg.&steps=grgrgg&goal=2_0_15_0_"
creators = "mtsd"
source = "新春なぞぷよ大会2018"
sourceDetail = "激辛 第15問"
