[[entries]]
query = "field=0_gy.yg.yy.gg.gb.yb.gg.yy.yb.rb.bbgbb.ygrrr.yyggg&steps=gygygy&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題1"

[[entries]]
query = "field=0_y.....g.....b....gb....gb...yyg...ybbb..gggy.&steps=ygybyb&goal=0_0_6_0_"
creators = "π"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題2"

[[entries]]
query = "field=0_br....gb...rbrb..bgbr..rrgg..grgr..ggrr.rrrggggggrrr&steps=rgrgrg&goal=0_0_6_1_0"
creators = "あすなろ"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題3"

[[entries]]
query = "field=0_b.....p.....p....bbb...ggp...gbbb.pppggg&steps=gbbppg&goal=0_0_5_1_0"
creators = "こなた"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題4"

[[entries]]
query = "field=0_y.....y.....pb....pb....py....yp...pbyy.&steps=bppyyp&goal=0_0_5_0_"
creators = "しろま"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題5"

[[entries]]
query = "field=0_r....gr....gg...rrbg..rbbgg&steps=rgrbrg&goal=0_0_5_0_"
creators = "りさ"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題6"

[[entries]]
query = "field=0_g...ggy...ybg...bby..yyyg..&steps=gygbgy&goal=0_0_5_0_"
creators = "redeye"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題7"

[[entries]]
query = "field=0_gg...ygr...yryr..grgy..yyrr.&steps=yrgryr&goal=0_0_4_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2019"
sourceDetail = "中辛 問題8"

[[entries]]
query = "field=0_y..g.yy.gg.gb.yb.gg.yy.yb.rb.bbhbb.yorrr.yyggg&steps=rbgyrbgy&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2019"
sourceDetail = "激辛 問題1"

[[entries]]
query = "field=0_r.....ob....ro....ob....rh....ob....rb..&steps=rrbbbrbr&goal=0_0_4_0_"
creators = "π"
source = "初春なぞぷよ大会2019"
sourceDetail = "激辛 問題2"

[[entries]]
query = "field=0_y..y..ybby..oygo..gbbr..ggrr..obbo..rrgg.orbbgo&steps=rygyryrg&goal=0_0_8_0_"
creators = "あすなろ"
source = "初春なぞぷよ大会2019"
sourceDetail = "激辛 問題3"

[[entries]]
query = "field=0_g.....g.....y.....g...ghg...bbb...gog...bbb..&steps=gybggyby&goal=0_0_5_0_0"
creators = "こなた"
source = "初春なぞぷよ大会2019"
sourceDetail = "激辛 問題4"

[[entries]]
query = "field=0_r.r...b.by..bbrby.rrbbyy&steps=yyrbryry&goal=0_0_6_0_"
creators = "しろま"
source = "初春なぞぷよ大会2019"
sourceDetail = "激辛 問題5"

[[entries]]
query = "field=0_rrg.bbgrg.rgoog.rrbbb.&steps=gbrbggrb&goal=0_0_6_0_"
creators = "りさ"
source = "初春なぞぷよ大会2019"
sourceDetail = "激辛 問題6"

[[entries]]
query = "field=0_y.....r...r.ob..b.yb..bbyo..roro..rrorr&steps=brbryrbr&goal=0_0_6_0_"
creators = "redeye"
source = "初春なぞぷよ大会2019"
sourceDetail = "激辛 問題7"
