[[entries]]
query = "field=0_b.b...g.g..br.rb.gb.gr.bb.gg.rr.rr.rbbbr.&steps=grbrbg&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題1"

[[entries]]
query = "field=0_y.....g....bg....bb....yy....byg...bbo...ogg...bbg..gbyy..ggybg.&steps=bggyby&goal=_0"
creators = "こなた"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題2"

[[entries]]
query = "field=0_b....pp....gb.b..pgpb..ppgggobbboo&steps=gpgbgp&goal=0_0_5_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題3"

[[entries]]
query = "field=0_r.....r.....r.....b.....b.....b.....o.....r.....rb.r.bbb.rorb&steps=rrrbrb&goal=6_3_5_0_"
creators = "platinum"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題4"

[[entries]]
query = "field=0_g.....r.g...o.r...oyy.rrroy.&steps=grgryr&goal=0_0_4_0_"
creators = "redeye"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題5"

[[entries]]
query = "field=0_rr....by...brr...borb..yybb.&steps=yrbrbr&goal=0_0_5_0_"
creators = "やまゆう"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題6"

[[entries]]
query = "field=0_g....ppr...ggg...pro...prg...pgg&steps=ggpppr&goal=0_0_5_0_"
creators = "貧弱PC"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題7"

[[entries]]
query = "field=0_ppp...bobp..ppbb.&steps=bpbbbp&goal=0_0_4_0_"
creators = "π"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題8"

[[entries]]
query = "field=0_r.....rb....ob....ggg...rbr...bob...rbr...ggg...rrbb.bbrggo&steps=rbrggb&goal=0_0_6_0_"
creators = "あすなろ"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題9"

[[entries]]
query = "field=0_b.....y...bgyb..ygyb..yygggbbbooo&steps=gygbgy&goal=0_0_5_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "中辛 問題10"

[[entries]]
query = "field=0_g.r..rg.rg.rb.bg.bg.gb.br.rb.gb.gr.bb.gg.rr.rr.rbbbr.&steps=grbrbgbr&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題1"

[[entries]]
query = "field=0_b.....bg..ohgg.yyoyy.ybbby.ghggoggbgbbggbbhbg&steps=bggyybbg&goal=0_0_7_0_0"
creators = "こなた"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題2"

[[entries]]
query = "field=0_b.....y.....b.....p.o...bby...hopy.pbppb.pbbhypphyyppypopoy&steps=ybpypypb&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題3"

[[entries]]
query = "field=0_b..g..b..y..r..y..rh.g.&steps=byrgbgry&goal=0_0_4_0_"
creators = "platinum"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題4"

[[entries]]
query = "field=0_gg....og....yy....bb....yy...ygg..&steps=gygbybgy&goal=0_0_5_0_"
creators = "redeye"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題5"

[[entries]]
query = "field=0_gggr..bbrr..rbgg..rrbg..ggbb..gbgg..bbgr..rrrg..gggr..rrrg.&steps=rggbbrrg&goal=0_0_6_1_0"
creators = "やまゆう"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題6"

[[entries]]
query = "field=0_y....gy...bgr...ory...bgy...org...brg...oyy...byg...orr...byr...&steps=ryggrrrp&goal=_5"
creators = "貧弱PC"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題7"

[[entries]]
query = "field=0_r.....o.....ggg..bobbb.boooogbrrrgg&steps=grbrgrbr&goal=0_0_6_0_"
creators = "π"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題8"

[[entries]]
query = "field=0_b..r.rr..bbgr..bgbb..rrbr..brgg..ggbg..grrr..bbrg..gbbb..rrrb..rb&steps=rgbbgbbb&goal=0_0_4_0_"
creators = "あすなろ"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題9"

[[entries]]
query = "field=0_g.....y.....goyb..bbgb..ybog..yybg.oooooo&steps=byygbgyg&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "激辛 問題10"

[[entries]]
query = "field=0_r.....y..yooy..yoryo.rryrr.&steps=yryryr&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "テスト 問題3"

[[entries]]
query = "field=0_y.....ro....yoyy..oryo.rryrr.&steps=yryryr&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "テスト 問題4"

[[entries]]
query = "field=0_y.....y.....o...r.y...o.y...rryo.royrr.&steps=yryryr&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "テスト 問題5"

[[entries]]
query = "field=0_oo..y.yyr.yrryo.royrr.&steps=yryryr&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "テスト 問題6"

[[entries]]
query = "field=0_r....yo....yoy...ryr..rroy..yyrr.&steps=yryryr&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2020"
sourceDetail = "テスト 問題7"

[[entries]]
query = "field=0_gg....og....yy...gob...yyy...obgg.&steps=gygbybgy&goal=0_0_5_0_"
creators = "redeye"
source = "初春なぞぷよ大会2020"
sourceDetail = "テスト 問題10"
