[[entries]]
id = 671
query = "field=0_y....yy....rr..y.yy.&steps=ryry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題1"

[[entries]]
id = 672
query = "field=0_y.y...y.y.y.r&steps=ryryry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題2"

[[entries]]
id = 673
query = "field=0_r...r.y..yy.y.&steps=ryyyry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題3"

[[entries]]
id = 674
query = "field=0_r.....y.y...ryy...&steps=ryyyry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題4"

[[entries]]
id = 675
query = "field=0_y.....ry....yyr...&steps=ryyyry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題5"

[[entries]]
id = 676
query = "field=0_g.....g....yor...yor&steps=ryggry&goal=0_0_3_0_"
creators = "PRRN"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題6"

[[entries]]
id = 677
query = "field=0_b.b...y.g...oyog..ybgb..ybgb&steps=bybgyg&goal=_5"
creators = "PRRN"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題7"

[[entries]]
id = 678
query = "field=0_rgyob.rgyob.rgyob.boryg.boryg.boryg.gyobr.gyobr.gyobr&steps=rbyg&goal=_1"
creators = "PRRN"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題8"

[[entries]]
id = 679
query = "field=0_ooryoo&steps=rryyry&goal=0_0_2_0_0"
creators = "FELF"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題9"

[[entries]]
id = 680
query = "field=0_o.....gg...obgbbbrrrgggbbb&steps=grbg&goal=0_0_4_0_"
creators = "べ～た"
source = "初春なぞぷよ大会2021"
sourceDetail = "甘口 問題10"

[[entries]]
id = 681
query = "field=0_o.....ggy.g.yoy.ggygg.yyoyg.yggyy.&steps=ygygyg&goal=0_0_6_0_"
creators = "PRRN"
source = "初春なぞぷよ大会2021"
sourceDetail = "中辛 問題1"

[[entries]]
id = 682
query = "field=0_b.....pp....bo....bp....go....gogg..gppg&steps=ppbgpg&goal=0_0_5_0_"
creators = "FELF"
source = "初春なぞぷよ大会2021"
sourceDetail = "中辛 問題2"

[[entries]]
id = 683
query = "field=0_g.....gg..r.rr.rrgryyygg&steps=rgygrg&goal=0_0_5_0_"
creators = "べ～た"
source = "初春なぞぷよ大会2021"
sourceDetail = "中辛 問題3"

[[entries]]
id = 684
query = "field=0_go.r..gbrr.bbobb&steps=gbbbgr&goal=0_0_4_0_"
creators = "π"
source = "初春なぞぷよ大会2021"
sourceDetail = "中辛 問題4"

[[entries]]
id = 685
query = "field=0_y.....y.....y....yr...rgr...rgg...ryy..&steps=gyrrry&goal=0_0_5_0_"
creators = "ROI_yas"
source = "初春なぞぷよ大会2021"
sourceDetail = "中辛 問題5"

[[entries]]
id = 686
query = "field=0_r.....gr....rr....go....og....rg....ro...&steps=gggrgr&goal=0_0_4_0_"
creators = "redeye"
source = "初春なぞぷよ大会2021"
sourceDetail = "中辛 問題6"

[[entries]]
id = 687
query = "field=0_b.....g.....o.....o.....b....gby..bgryg.bbrgg.&steps=ygbrygbr&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2021"
sourceDetail = "激辛 問題1"

[[entries]]
id = 688
query = "field=0_b.....b.....b.....r.b...y.yb.rr.oy.oooyy.&steps=ybyyrybb&goal=0_0_5_0_"
creators = "べ～た"
source = "初春なぞぷよ大会2021"
sourceDetail = "激辛 問題2"

[[entries]]
id = 689
query = "field=0_p.....h.....pp....op...ggb...bop...bbp..&steps=gbbbgppb&goal=0_0_5_0_"
creators = "π"
source = "初春なぞぷよ大会2021"
sourceDetail = "激辛 問題3"

[[entries]]
id = 690
query = "field=0_y.....g.....yr....yy....gr...ggrg..yyrg.&steps=rgyyrrrg&goal=0_0_6_0_"
creators = "ROI_yas"
source = "初春なぞぷよ大会2021"
sourceDetail = "激辛 問題4"

[[entries]]
id = 691
query = "field=0_g.....r.....g...r.o...g.r...ogr..&steps=ggrrgrgr&goal=0_0_4_0_"
creators = "redeye"
source = "初春なぞぷよ大会2021"
sourceDetail = "激辛 問題5"

[[entries]]
id = 692
query = "field=0_o.o...g.y.y.y.o.o.g.g.g.o.o.y.y.y.g.g.o.o.y.g.g.oyoyo&steps=ygyygyggyg&goal=_1"
creators = "PRRN"
source = "初春なぞぷよ大会2021"
sourceDetail = "殿堂 問題1"

[[entries]]
id = 693
query = "field=0_br....rb...rrb..pobob.ppopp.&steps=rpbrrbbppr&goal=0_0_6_0_"
creators = "π"
source = "初春なぞぷよ大会2021"
sourceDetail = "殿堂 問題2"

[[entries]]
id = 694
query = "field=0_y.....y.....y.....ry...yyr..&steps=ryry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "テスト 問題1"

[[entries]]
id = 695
query = "field=0_y.....y.....r...y.y...ryy...&steps=ryry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "テスト 問題2"

[[entries]]
id = 696
query = "field=0_y.....y...y.r.y.y.y.r&steps=ryry&goal=0_0_3_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2021"
sourceDetail = "テスト 問題4"
