[[entries]]
id = 724
query = "field=0_y.....yrgr.yggoryrrrgyy&steps=ryry&goal=0_0_4_0_"
creators = "PRRN"
source = "初春なぞぷよ大会2023"
sourceDetail = "甘口 問題2"

[[entries]]
id = 725
query = "field=0_yry...ryy...rro...bbrr.obyyy.&steps=bryr&goal=0_0_5_0_"
creators = "π"
source = "初春なぞぷよ大会2023"
sourceDetail = "甘口 問題3"

[[entries]]
id = 726
query = "field=0_r....ooy...oooo.oo&steps=yyryryyyry&goal=2_2_12_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2023"
sourceDetail = "甘口 問題6"

[[entries]]
id = 727
query = "field=0_y.....yyg...rry...rgyy.oggrrr&steps=yryr&goal=0_0_5_0_"
creators = "べ～た"
source = "初春なぞぷよ大会2023"
sourceDetail = "甘口 問題10"

[[entries]]
id = 728
query = "field=0_b.....b.....b..yyy&steps=by&goal=1_0_2_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題1"

[[entries]]
id = 729
query = "field=0_g....gr....gy....gyr...ygr...ygy...rrgyyyyrgg&steps=ryggry&goal=0_0_5_0_2"
creators = "ROI_yas"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題2"

[[entries]]
id = 730
query = "field=0_b.....b.....o.....b.....y.....ryy...rrb.oyybb.&steps=bybyry&goal=0_0_5_0_"
creators = "OrangeP"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題3"

[[entries]]
id = 731
query = "field=0_r....ggg...ror...yoy..yygyy.rrgrr.orgrg&steps=rgryry&goal=0_0_7_0_"
creators = "PRRN"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題4"

[[entries]]
id = 732
query = "field=0_bgbb..bbgb..rgrr..rrgr.&steps=brbrbr&goal=0_0_5_0_0"
creators = "やまちゃん"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題5"

[[entries]]
id = 733
query = "field=0_bbb...rrr...ggg...ooo...ggg...rrr...yyyb..rrrb..gggb&steps=ryrgrg&goal=_6"
creators = "あすなろ"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題6"

[[entries]]
id = 734
query = "field=0_g.....r.....yg....yy....gg....grrr..yygg..goyy..rrgg.gorgor&steps=yryggr&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題7"

[[entries]]
id = 735
query = "field=0_b.....p.....b.b...ggpg..ogog..pppg.&steps=ppgbgp&goal=0_0_5_0_"
creators = "π"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題8"

[[entries]]
id = 736
query = "field=0_yy....oo....yb....oo....yb....ob...yyb..&steps=ybybbb&goal=0_0_4_0_"
creators = "べ～た"
source = "初春なぞぷよ大会2023"
sourceDetail = "中辛 問題9"

[[entries]]
id = 737
query = "field=0_b..y.bb..yy&steps=by&goal=1_0_2_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2023"
sourceDetail = "激辛 問題1"

[[entries]]
id = 738
query = "field=0_y...g.yrrry.rpyygyppyggr&steps=ryypryry&goal=0_0_5_0_"
creators = "ROI_yas"
source = "初春なぞぷよ大会2023"
sourceDetail = "激辛 問題2"

[[entries]]
id = 739
query = "field=0_r.....rg....yg....oy....yoy..rrgg..gyoy.gyoyrr&steps=rygyrygy&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2023"
sourceDetail = "激辛 問題3"

[[entries]]
id = 740
query = "field=0_b....hrb...gor...brb...rbr...gro...ggo...oog..rrgg.gggrrr&steps=ryrgrgrg&goal=_5"
creators = "あすなろ"
source = "初春なぞぷよ大会2023"
sourceDetail = "激辛 問題4"

[[entries]]
id = 741
query = "field=0_g....yg...rgry..hhyy..yygr..rrgg..gryr.ggygrrhhhhhh&steps=yrgryggr&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2023"
sourceDetail = "激辛 問題5"

[[entries]]
id = 742
query = "field=0_r.....o..g..r..r..o..o.&steps=rrggrrrg&goal=0_0_3_0_"
creators = "π"
source = "初春なぞぷよ大会2023"
sourceDetail = "激辛 問題6"

[[entries]]
id = 743
query = "field=0_o.....oo....yb....oo....yb....ob...yyb..&steps=yyybybbb&goal=0_0_4_0_"
creators = "べ～た"
source = "初春なぞぷよ大会2023"
sourceDetail = "激辛 問題7"

[[entries]]
id = 744
query = "field=0_b..y..b..y..b..y.&steps=by&goal=1_0_2_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2023"
sourceDetail = "殿堂 問題1"

[[entries]]
id = 745
query = "field=0_r..g..rg.r..yy.g..rg.r..oyyg..rorr.yygoyy&steps=rggyyrrgyrgy&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2023"
sourceDetail = "殿堂 問題2"

[[entries]]
id = 746
query = "field=0_y....gr....ryr...ggrr..rhhg..ygry..oyyh..ggrr..grgr..rrgg.&steps=ygyrgryryrgr&goal=0_0_9_1_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2023"
sourceDetail = "殿堂 問題4"

[[entries]]
id = 747
query = "field=0_r.....y.....yg.g..gyyy..gooo.rrryyy&steps=gygyrrgyrrgy&goal=0_0_7_0_"
creators = "π"
source = "初春なぞぷよ大会2023"
sourceDetail = "殿堂 問題5"
