[[entries]]
query = "field=0_y.....b....brbbbbrrby&steps=ryby&goal=0_0_4_0_"
creators = "べ〜た"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第1問"

[[entries]]
query = "field=0_bb....yb....ggbbbyyy&steps=gbgb&goal=0_0_4_0_"
creators = "べ〜た"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第2問"

[[entries]]
query = "field=0_o.....bb....yoy.yyoyy.&steps=bbyy&goal=0_0_3_0_"
creators = "redeye"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第3問"

[[entries]]
query = "field=0_ygg.ggygb.bygbybyygbbybbbyybggg&steps=gbyg&goal=2_2_13_1_"
creators = "べ〜た"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第4問"

[[entries]]
query = "field=0_b....oo....bo...bob..ooobb.bbooo&steps=bbbb&goal=0_0_3_0_"
creators = "ことみ"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第5問"

[[entries]]
query = "field=0_g.....yg...ygr...yrgr..grgr.yyrgyr&steps=yryg&goal=0_0_5_0_0"
creators = "カレンナ"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第6問"

[[entries]]
query = "field=0_o.....p...o.oo..popp.&steps=pppp&goal=0_0_2_0_"
creators = "π"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第7問"

[[entries]]
query = "field=0_r..y..ry.y..ryrr.ryooy.&steps=ryry&goal=_0"
creators = "PRRN"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第8問"

[[entries]]
query = "field=0_g...p.y...g.r...yyrrg.gypyp.grygr.gpyyrrprrggpprygrp&steps=ggrp&goal=0_0_9_0_"
creators = "ことみ"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第9問"

[[entries]]
query = "field=0_op....pp...yoop..yppoo&steps=ypyp&goal=0_0_3_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第10問"

[[entries]]
query = "field=0_r..y..r..y..ryrr.ryoyy.&steps=ryry&goal=_0"
creators = "PRRN"
source = "新春なぞぷよ大会2025"
sourceDetail = "甘口 第11問"

[[entries]]
query = "field=0_gg...rygr..ryrg.ygrgryyyrgyy&steps=rgrygy&goal=0_0_5_1_"
creators = "カレンナ"
source = "新春なぞぷよ大会2025"
sourceDetail = "中辛 第1問"

[[entries]]
query = "field=0_p.....p.....rp....gg....ppo...pro.&steps=rpgrpg&goal=0_0_4_0_"
creators = "π"
source = "新春なぞぷよ大会2025"
sourceDetail = "中辛 第2問"

[[entries]]
query = "field=0_r....yy....yry...ggg...oro...ror...oroy.&steps=ryrygy&goal=_0"
creators = "PRRN"
source = "新春なぞぷよ大会2025"
sourceDetail = "中辛 第3問"

[[entries]]
query = "field=0_g.....rg....rr....yyo...yoorrr&steps=yggrgr&goal=0_0_4_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2025"
sourceDetail = "中辛 第4問"

[[entries]]
query = "field=0_r.....b.....b.....r.....o.....r.....b...rrorb.&steps=brbbbr&goal=0_0_4_0_"
creators = "redeye"
source = "新春なぞぷよ大会2025"
sourceDetail = "中辛 第5問"

[[entries]]
query = "field=0_b....bo...boby..yoyy..yyoo.&steps=bbybyb&goal=0_0_4_0_"
creators = "べ〜た"
source = "新春なぞぷよ大会2025"
sourceDetail = "中辛 第6問"

[[entries]]
query = "field=0_bob..bobo..rrgg..rgrr..ggor..rrgg..rgrg..ggrr.&steps=rgrbrg&goal=_0"
creators = "あすなろ"
source = "新春なぞぷよ大会2025"
sourceDetail = "中辛 第7問"

[[entries]]
query = "field=0_bb...ggrr.rgobrgrobbogrgorrgoggoro&steps=rggbbrrg&goal=_0"
creators = "あすなろ"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第1問"

[[entries]]
query = "field=0_o.....y.....o.....y.....o.....y.....o.....r.g...ryg.&steps=yyyryggr&goal=0_0_4_0_"
creators = "redeye"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第2問"

[[entries]]
query = "field=0_g....gr....go.r..oo.g..grrg..gogoo&steps=rgrrggrg&goal=0_0_5_0_"
creators = "ことみ"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第3問"

[[entries]]
query = "field=0_r.....o.....r....ggg...oyy...ooy...ggg...yry...ryr...yry..&steps=rygyrygy&goal=_0"
creators = "PRRN"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第4問"

[[entries]]
query = "field=0_o....ooo...obo..obob..bobo..oobo..bbob.&steps=ybyybbyb&goal=0_0_4_0_0"
creators = "べ〜た"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第5問"

[[entries]]
query = "field=0_ggry..brbr..rbgy..rgby..ggbb.&steps=rrrygbgb&goal=0_0_7_0_"
creators = "ぬえ"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第6問"

[[entries]]
query = "field=0_r.....y.....r.....r.....oy...bbb...rryy.&steps=ryrryyby&goal=0_0_5_0_"
creators = "π"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第7問"

[[entries]]
query = "field=0_g.....r..rg.g..ryyg.ygrgryyyrgyy&steps=grgrygyr&goal=_0"
creators = "カレンナ"
source = "新春なぞぷよ大会2025"
sourceDetail = "激辛 第8問"

[[entries]]
query = "field=0_gg....yy....py....oo....yp...ogg...oyy...ooo..&steps=gyggyypyygyp&goal=0_0_6_0_"
creators = "PRRN"
source = "新春なぞぷよ大会2025"
sourceDetail = "殿堂 第1問"

[[entries]]
query = "field=0_g.....y...rbb..bgggrgybgrggybbgyyrrrrrrbgygggrrgbyyggrbbybbrgrbyybggrbbyrrbggg&steps=grbrrrbyrgrb&goal=0_0_19_0_"
creators = "ぬえ"
source = "新春なぞぷよ大会2025"
sourceDetail = "殿堂 第2問"

[[entries]]
query = "field=0_go....or....ry....yg....oy....yg....or....rg..&steps=ygrrygyrygrg&goal=0_0_6_0_"
creators = "redeye"
source = "新春なぞぷよ大会2025"
sourceDetail = "殿堂 第3問"

[[entries]]
query = "field=0_g.....b.....g.....b.....rbb.r.ooo.rroogg&steps=bbrrggrbggrb&goal=0_0_6_0_"
creators = "π"
source = "新春なぞぷよ大会2025"
sourceDetail = "殿堂 第4問"

[[entries]]
query = "field=0_y.rr..yprpr.ppbryyyrpyppyprpyp&steps=rpyrbbypybry&goal=0_0_7_1_"
creators = "べ〜た"
source = "新春なぞぷよ大会2025"
sourceDetail = "殿堂 第5問"

[[entries]]
query = "field=0_r.....b.....y.....b..rb.r..yrby..rrbb..byor.bbyyrroooooooooooooooooo&steps=yyyrybbyrybr&goal=5_2_35_0_"
creators = "カレンナ"
source = "新春なぞぷよ大会2025"
sourceDetail = "殿堂 第6問"
