[[entries]]
query = "field=0_bygr..bbgg..ryrb..ryrb.&steps=rrygrbbb&goal=0_0_6_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal 第1問"

[[entries]]
query = "field=0_g.....go....go...rrr...ogoggg&steps=rrrrrg&goal=0_0_4_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal 第2問"

[[entries]]
query = "field=0_r...rbg...ggb...grr...brgg&steps=rbrgrg&goal=0_0_5_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Normal 第3問"

[[entries]]
query = "field=0_g...yrrr..rgbyr.rgbyr.rgbyr.yrrrg.&steps=yyygbgrg&goal=0_0_8_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Normal 第4問"

[[entries]]
query = "field=0_y...byr..rbbb..yyrbrryr&steps=bbbybyyyby&goal=_0"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Normal 第5問"

[[entries]]
query = "field=0_ry..yryyggyyrgbbgrrrggrr&steps=bbgygy&goal=0_0_7_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal 第6問"

[[entries]]
query = "field=0_y....yr....ryr.y.yryyyyrroy&steps=yryryr&goal=0_2_5_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal 第7問"

[[entries]]
query = "field=0_yr....yr...yoo...yoo..yrrr..yoyyy&steps=rryyyr&goal=0_0_5_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Normal 第8問"

[[entries]]
query = "field=0_ggooggogobogroorobrrorro&steps=rgbrgb&goal=0_0_5_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Normal 第9問"

[[entries]]
query = "field=0_o...grr...goo...rrr...ooo...rrr..rooo.rgrrr.rgooo.&steps=rbbbrb&goal=0_0_6_0_"
creators = "igo"
source = "戦技研HP"
sourceDetail = "Normal 第10問"

[[entries]]
query = "field=0_g.....y...g.g...ggr...yrr...yybb..ggyy..grry..&steps=yrbrbr&goal=0_0_7_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Normal 第11問"

[[entries]]
query = "field=0_roro..roro..roro..oror..oror..roro..roro..oror..oror..roro..roro.&steps=rrrrrr&goal=2_2_15_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Normal 第12問"

[[entries]]
query = "field=0_yr....rr....yb....yy.y..gb.rg.bb.grrgr.rgrggrrgg&steps=rgrg&goal=0_0_2_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Normal 第13問"

[[entries]]
query = "field=0_bb..bbyr..gyyy..yyrrrgggoggrrooogroorrrggg&steps=bgbgbyby&goal=0_0_9_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Normal 第14問"

[[entries]]
query = "field=0_b.rg.bbrrggbggbbrrgrrggrbbrgbb&steps=rgrgrg&goal=1_0_3_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal 第15問"

[[entries]]
query = "field=0_yyybbbbrrggybbrgyyyyybbb&steps=byrgbyby&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal 第16問"

[[entries]]
query = "field=0_brbrrrrbrrbbbrbb&steps=rbrbrb&goal=2_0_11_1_"
creators = "K-NES"
source = "戦技研HP"
sourceDetail = "Normal 第17問"

[[entries]]
query = "field=0_orro..oror..oogg..oror..orro..&steps=rrggrr&goal=0_0_4_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Normal 第18問"

[[entries]]
query = "field=0_rrr..rooor.rooor.orrro.ooooo.ooororooororooooorooooro&steps=rrrrrr&goal=_3"
creators = "ワタリ"
source = "戦技研HP"
sourceDetail = "Normal 第19問"

[[entries]]
query = "field=0_yy....bbb...rgr.grgrgrgrgrgrgrgrgr&steps=ybygrg&goal=0_0_8_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Normal 第20問"

[[entries]]
query = "field=0_r..o..r..o..o.ror.r.rro.r.oorrorororooorrorrrooroorrorroooooororrror&steps=yyyyrr&goal=_0"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal 第21問"

[[entries]]
query = "field=0_gbyr..byrg..yrgb..rgby..&steps=yybbggbbggyy&goal=1_0_4_0_"
creators = "エナメル"
source = "戦技研HP"
sourceDetail = "Normal 第22問"

[[entries]]
query = "field=0_y.....y.....or..rrgryrrrrgryyggrryr&steps=ryyyyyry&goal=0_0_7_0_"
creators = "ミケ"
source = "戦技研HP"
sourceDetail = "Normal 第23問"

[[entries]]
query = "field=0_r.....ryyrggrybbgybbgbrybggrry&steps=bgyrbryg&goal=0_0_8_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Normal 第24問"

[[entries]]
query = "field=0_b.b...b.yg..r.pb.prygybbrggppp&steps=ybrgyb&goal=0_0_6_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal 第25問"

[[entries]]
query = "field=0_r...b.bbgbyybgygbbrrrgbybyyrrybygggrbgyrrgybgrgryyrbggbbbrrrrrrggg&steps=bgbyby&goal=0_0_12_1_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal 第26問"

[[entries]]
query = "field=0_b.....r.....y.....rg..r.rrg.r.ggbbbr&steps=bbbyyybr&goal=0_0_6_0_"
creators = "エナメル"
source = "戦技研HP"
sourceDetail = "Normal 第27問"

[[entries]]
query = "field=0_ry....rryr..yybb..rrrbrr&steps=ggrgrgrb&goal=0_0_6_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Normal 第28問"

[[entries]]
query = "field=0_rrgg..rgrg..grgr..ggrr.&steps=rrgrgg&goal=_0"
creators = "akst"
source = "戦技研HP"
sourceDetail = "Normal 第29問"

[[entries]]
query = "field=0_r....rb..rrbr..bbry..rryy..&steps=rbbbbbyb&goal=0_0_5_0_0"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Normal 第30問"

[[entries]]
query = "field=0_g.r...gbb...gbyyyoooooooooooo&steps=rrryrbrg&goal=_1"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Normal 第31問"

[[entries]]
query = "field=0_pbpbpbpbpbpb&steps=pbpbpb&goal=2_0_10_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Normal 第32問"

[[entries]]
query = "field=0_b....rrb...brbr..bbrr..rrbb.&steps=bbrbrb&goal=2_0_18_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Normal 第33問"

[[entries]]
query = "field=0_r...b.r...rbr..brgg..ggbb..grrbg&steps=rgrbgb&goal=0_0_6_0_"
creators = "すぴぃちゃん"
source = "戦技研HP"
sourceDetail = "Normal 第34問"

[[entries]]
query = "field=0_gggor.orogr.rooor.rgoro.roggg&steps=rgrgrr&goal=0_0_5_0_0"
creators = "h!de"
source = "戦技研HP"
sourceDetail = "Normal 第35問"

[[entries]]
query = "field=0_ggb...grr..yrbrb.yyrby.rrbbyy&steps=gbbyyr&goal=0_2_7_0_"
creators = "mino"
source = "戦技研HP"
sourceDetail = "Normal 第36問"

[[entries]]
query = "field=0_b...gbbyyygggbbbg&steps=ygbgbg&goal=0_0_5_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Normal 第37問"

[[entries]]
query = "field=0_bbb..byygg.bgygy.bggyy&steps=bygygb&goal=1_0_3_0_"
creators = "h!de"
source = "戦技研HP"
sourceDetail = "Normal 第38問"

[[entries]]
query = "field=0_y.....yp....yp....rp....rg....rgg...&steps=grgygggp&goal=0_0_5_0_"
creators = "山岸"
source = "戦技研HP"
sourceDetail = "Normal 第39問"

[[entries]]
query = "field=0_ggggbooooggoggbbbbgbb&steps=gbgbgb&goal=0_0_5_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal 第40問"

[[entries]]
query = "field=0_b.rr..b.gr..bggb..rrbb..rggg.&steps=bgrgrb&goal=0_0_6_0_"
creators = "さっか"
source = "戦技研HP"
sourceDetail = "Normal 第41問"

[[entries]]
query = "field=0_bb..bbbro.rbggooggpgrrgp&steps=pgpbpgpb&goal=_7"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal 第42問"

[[entries]]
query = "field=0_b..y..bbyy..ggrr..gybr..yybb.bbbyyy&steps=gyrbby&goal=0_0_5_1_0"
creators = "shimogon"
source = "戦技研HP"
sourceDetail = "Normal 第43問"
