[[entries]]
query = "field=0_bb....brg...org...bbrg..brgg..&steps=gygygybybg&goal=0_0_6_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第1問"

[[entries]]
query = "field=0_y.....r...b.r...bggg..rryr..&steps=yrygbbrr&goal=0_2_5_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第2問"

[[entries]]
query = "field=0_bygr..bbgg..ryrb..ryrb.&steps=gbrrybrb&goal=0_0_6_0_"
creators = "ワタリ"
source = "戦技研HP"
sourceDetail = "Normal+ 第4問"

[[entries]]
query = "field=0_bygr..bbgg..ryrb..ryrb.&steps=brrgbybr&goal=0_0_6_0_"
creators = "ワタリ"
source = "戦技研HP"
sourceDetail = "Normal+ 第5問"

[[entries]]
query = "field=0_rr....gy....yb....ggb...gyy...&steps=ybrbryyy&goal=0_0_5_0_"
creators = "ワタリ"
source = "戦技研HP"
sourceDetail = "Normal+ 第6問"

[[entries]]
query = "field=0_y..o..b..yrrrrgyyrryggbgbyybggbbgybb&steps=gyrgry&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第7問"

[[entries]]
query = "field=0_y...r.gb..r.bggrg.bbgrggggyybbgbrygbyybrrgybbrgg&steps=gbybbbgb&goal=0_0_12_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第8問"

[[entries]]
query = "field=0_r....bg....gb....gg....br.r..bbrb..rrbb..&steps=rrbbggbgbg&goal=0_0_7_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第10問"

[[entries]]
query = "field=0_r....ryyrrrrybbbyrgggryyyyrry&steps=ygygybrr&goal=0_0_8_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Normal+ 第11問"

[[entries]]
query = "field=0_b.....ggg.bbbrrrogggoorrrbbb&steps=rbggrb&goal=0_0_6_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal+ 第12問"

[[entries]]
query = "field=0_ybbbgyyrrggyyrbbbygggrrr&steps=rygbrygb&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal+ 第13問"

[[entries]]
query = "field=0_ggyy..grry..pprp..yygg..yrrg..prpp.&steps=rgyprpgy&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal+ 第14問"

[[entries]]
query = "field=0_y.....y.g..rygb..bggb..yybg..bygbg.bgryrybrgryrrgryryrgryry&steps=gygyyygy&goal=0_0_12_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第15問"

[[entries]]
query = "field=0_b.....y.....b.....bygyb.bgyyrryygbbrbygybobrbrgrbrrbrgyybrgryrbrgr&steps=rgyyyrby&goal=0_0_14_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第16問"

[[entries]]
query = "field=0_g.....bb....bg.b..gbbg.grrgb.grgbb.&steps=gggbrbgb&goal=0_0_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第17問"

[[entries]]
query = "field=0_g....gry..grybg.rybgb.ybgbr.yybrr.&steps=ryygbbrg&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第18問"

[[entries]]
query = "field=0_bbbrrrooooooyyyoooooogggoooooorrrbbbooo&steps=rbgyrb&goal=0_2_6_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Normal+ 第19問"

[[entries]]
query = "field=0_o...b.g...byg...bgo...ogo...rob...ryby..ryby..oyoy..&steps=yyyrybyb&goal=0_3_7_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Normal+ 第20問"

[[entries]]
query = "field=0_r.b...r.b...yry...yry...rgr...yry...bbb...grg...grg...grg.&steps=rbrybybg&goal=0_0_9_0_"
creators = "igo"
source = "戦技研HP"
sourceDetail = "Normal+ 第21問"

[[entries]]
query = "field=0_rrr...ooor..oooo.ooooo.ooooooooooooooooooooooooooooooooooooooooo&steps=yyyyrryyyyrr&goal=0_0_3_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Normal+ 第22問"

[[entries]]
query = "field=0_bbb...ggg...yyy...grg...grg...grg...bbb..oooooooooooo&steps=ggggrgrb&goal=_3"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Normal+ 第23問"

[[entries]]
query = "field=0_by...ryy...ggo...goo.gyroobgrrooogygoogbyygyooggyy&steps=bbbygy&goal=_0"
creators = "九十九"
source = "戦技研HP"
sourceDetail = "Normal+ 第24問"

[[entries]]
query = "field=0_r..ro.ooooo.ooooo.roror.roror.rororoororororororororor&steps=rrrrrrrr&goal=0_0_6_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Normal+ 第25問"

[[entries]]
query = "field=0_o.....o.....o.....r.oy..r.oy..r.oyr.y.rorryrro&steps=yryryr&goal=0_0_5_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Normal+ 第26問"

[[entries]]
query = "field=0_rb..b.brbobbrbgggbrrbbb&steps=rrbgbr&goal=0_0_6_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第27問"

[[entries]]
query = "field=0_g.....gb....yy....yb....bb....yr....rr....yy....yr.grrgggbbrrrrggg&steps=ygbrbgrg&goal=0_3_10_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第28問"

[[entries]]
query = "field=0_y....yy....yr....rry..yrrybbyrbryyrbbbrrbbrryyrryybbyy&steps=rbrbbbrb&goal=0_0_10_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal+ 第29問"

[[entries]]
query = "field=0_bbrb..roob..boor..brbb..&steps=bybybbyy&goal=_3"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Normal+ 第30問"

[[entries]]
query = "field=0_o.....o....ro....ro....ryo...yyoo.yrogyoyoogyyrrr&steps=yrrrggrr&goal=_1"
creators = "ぱぴこ"
source = "戦技研HP"
sourceDetail = "Normal+ 第31問"

[[entries]]
query = "field=0_y.....y.....g....rrg...ryb.o.ybboo.&steps=gggrbggg&goal=0_0_5_0_"
creators = "和樹"
source = "戦技研HP"
sourceDetail = "Normal+ 第32問"

[[entries]]
query = "field=0_bg....ygyb.rbyggbrbgygrbggyrbbbbgbyybygyryybrggrybbgrr&steps=grgrgrgbgb&goal=0_0_14_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第33問"

[[entries]]
query = "field=0_b.....b.....ob....gg....gr...gyrrorrryyy&steps=ggbrygrg&goal=0_0_6_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第34問"

[[entries]]
query = "field=0_bb....yb....yy....gbrrbbggbgbgrrbbgg&steps=rgbybgbg&goal=2_0_17_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第35問"

[[entries]]
query = "field=0_bb....bo....gbrrbbggbgbgrrbbgg&steps=ggbbrgbb&goal=2_2_15_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第36問"

[[entries]]
query = "field=0_o..o..o..o..o..o.gggoooooobbboorrrooyyyoo&steps=pyprpbpg&goal=_0"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第37問"

[[entries]]
query = "field=0_ggbb..bryg..bryg..yyrr..rgby..rgby.&steps=rbygybygrb&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal+ 第38問"

[[entries]]
query = "field=0_b.gy..bbbb..yyby..gyyygbyggrbyggggrbyyrrbbyg&steps=gggybybg&goal=0_0_10_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Normal+ 第39問"

[[entries]]
query = "field=0_p....ygrb..ygrb..ygrb..ooooooggoooooopppo&steps=gygggrgbgg&goal=0_2_6_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal+ 第40問"

[[entries]]
query = "field=0_oo....oo...ppprrrrrryyybbbrrrrrrggg&steps=rgrbryrp&goal=0_0_8_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal+ 第41問"

[[entries]]
query = "field=0_g.....bg.bbgbbgbgrrrrgrr&steps=grgbgrgb&goal=0_0_6_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal+ 第42問"

[[entries]]
query = "field=0_o.....y.....ybbo..ggby..rrry..&steps=ygbrygyy&goal=0_0_5_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal+ 第43問"

[[entries]]
query = "field=0_o.....o.....o.....o.....o.....o.....o.....o..y..o..y..orrgbborygybo&steps=yrygygyb&goal=0_0_5_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal+ 第44問"

[[entries]]
query = "field=0_yby..byby..byby.ooooo.oybybooybybooybybo&steps=ybybyb&goal=0_0_6_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal+ 第45問"

[[entries]]
query = "field=0_gg.gg.gyygyybbybbybrrbrr&steps=rrgbryrbgy&goal=0_0_8_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Normal+ 第46問"

[[entries]]
query = "field=0_g.....gg...bbr...rgr...rgr...rgbb.&steps=bbrggbrb&goal=0_0_6_0_"
creators = "じんじょ"
source = "戦技研HP"
sourceDetail = "Normal+ 第47問"

[[entries]]
query = "field=0_brrr..bygb..bygb..rrrb.&steps=yyggbbrr&goal=0_0_6_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第48問"

[[entries]]
query = "field=0_ry....rryr..yybb..rrrbrr&steps=ggrgrbrg&goal=0_0_6_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Normal+ 第49問"

[[entries]]
query = "field=0_y.g...g.yg..g.ybggr.bybrrrrbbygrggyyg&steps=rbgbgbry&goal=0_0_9_0_"
creators = "ぺいぺい"
source = "戦技研HP"
sourceDetail = "Normal+ 第50問"

[[entries]]
query = "field=0_y....gb...yyg..gbyg..rrrg..gbyr&steps=grgbyrrryy&goal=0_0_7_0_"
creators = "あべし"
source = "戦技研HP"
sourceDetail = "Normal+ 第51問"

[[entries]]
query = "field=0_rb....bg....ggb..bybb.bbrrr.ooobooooooryyygrr&steps=yrybybyb&goal=0_0_8_0_"
creators = "あべし"
source = "戦技研HP"
sourceDetail = "Normal+ 第52問"

[[entries]]
query = "field=0_b....rr...bbr...bgyy..ggby..rbbg..rrgg.&steps=yrgbgr&goal=0_0_7_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Normal+ 第53問"

[[entries]]
query = "field=0_ggbrrrgobooooobyyyyyybooooobogrrrbgg&steps=gbyrgbyr&goal=0_0_8_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Normal+ 第54問"

[[entries]]
query = "field=0_y....brrrgggbbbyyyyyyrrrgggbbb&steps=bygrgr&goal=0_0_8_0_"
creators = "enamel"
source = "戦技研HP"
sourceDetail = "Normal+ 第55問"

[[entries]]
query = "field=0_g.....y.....yg...ggrr..ygrgrryrgrgrgrgrrgg&steps=yryryyry&goal=0_0_7_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Normal+ 第56問"

[[entries]]
query = "field=0_g.....r.....rg...ggrr..ygrgrryygrgrgrgrrgg&steps=yryyyrry&goal=0_0_7_0_"
creators = "すぴぃちゃん"
source = "戦技研HP"
sourceDetail = "Normal+ 第57問"

[[entries]]
query = "field=0_bbr...byrr..gyybg.ggbbgg&steps=ygbrrrbgrr&goal=0_0_7_0_"
creators = "prime"
source = "戦技研HP"
sourceDetail = "Normal+ 第58問"

[[entries]]
query = "field=0_p....rr...bbb..rrro.bbboprrropo&steps=rbrbrp&goal=_0"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Normal+ 第59問"

[[entries]]
query = "field=0_b.y..rr.yybgr.brrgg.bbrbb.&steps=bryrgr&goal=0_0_6_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Normal+ 第60問"

[[entries]]
query = "field=0_bbb...ggg...rrr...bbb...ggg...rrr..&steps=rggbbr&goal=1_0_3_0_"
creators = "sim"
source = "戦技研HP"
sourceDetail = "Normal+ 第61問"

[[entries]]
query = "field=0_b....bb....oyyoooyyyyobbbbbbooooyyyoo&steps=ybybyb&goal=2_2_12_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Normal+ 第62問"

[[entries]]
query = "field=0_r....ggb...gbb...rgrb.brrgg.&steps=rrgbrbgb&goal=0_0_6_0_"
creators = "すぴぃちゃん"
source = "戦技研HP"
sourceDetail = "Normal+ 第63問"

[[entries]]
query = "field=0_gggrrryybbbyygggyyrrrbbb&steps=rybbgyrg&goal=0_0_8_0_"
creators = "h!de"
source = "戦技研HP"
sourceDetail = "Normal+ 第64問"

[[entries]]
query = "field=0_g.....rrg...rgg...yyy...grr...ggr...yyy...rrg..yrggy.&steps=grgygr&goal=_0"
creators = "iso"
source = "戦技研HP"
sourceDetail = "Normal+ 第65問"

[[entries]]
query = "field=0_r..g..oggo..gbyg..yybb..yggb.bbbyyy&steps=rrrrggby&goal=0_0_7_0_0"
creators = "すぴぃちゃん"
source = "戦技研HP"
sourceDetail = "Normal+ 第66問"

[[entries]]
query = "field=0_byy.b.byb.g.brrggbgggrbb&steps=bybbrgbg&goal=0_0_7_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Normal+ 第67問"
