[[entries]]
query = "field=0_gg....rg...yrrb..yybb.gbbyyrggbyrr&steps=bryggrby&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第1問"

[[entries]]
query = "field=0_b.....b...ybr...rgb...rgb...grb..ggrg&steps=ryrbbgrygy&goal=0_0_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第3問"

[[entries]]
query = "field=0_b...b.b...b.g...r.bb.bb.rgrgr.rgrgr.grgrg.grgrg.&steps=ggbrrggbgg&goal=0_3_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第4問"

[[entries]]
query = "field=0_o.....og.brbbrgyrbyrryyybbggrybrgyr&steps=gyybyygygb&goal=0_0_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第5問"

[[entries]]
query = "field=0_p.....p..b..r..r..rg.g..ggprggboppogbproopobooppprrgrroprgbrbbbgbb&steps=rpbgbrpg&goal=0_0_12_0_"
creators = "へーょまは"
source = "戦技研HP"
sourceDetail = "Hard 第6問"

[[entries]]
query = "field=0_r.....rg...gbb..yybg..gyrg..grrg&steps=rybygyryry&goal=0_0_7_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Hard 第7問"

[[entries]]
query = "field=0_y...ggyg..gyggbbbbybb&steps=byyybgyg&goal=0_0_6_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Hard 第8問"

[[entries]]
query = "field=0_yy...byr..brry..bryr..gygr.gygyrbbgygybygygy&steps=gyyyrbby&goal=0_0_10_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第9問"

[[entries]]
query = "field=0_b.....bb...yyr...ybrry.rryyggrgrbyggbbyrrggbyyr&steps=bybgrgrbyb&goal=0_0_11_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第10問"

[[entries]]
query = "field=0_gyyr..ryrr..bbyyrrbgbyryrggbyyrrbbrg&steps=gygrgygbry&goal=0_0_10_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第11問"

[[entries]]
query = "field=0_bb....brr...yyg...ygr...grr.&steps=bbrbrbygrb&goal=0_0_6_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第12問"

[[entries]]
query = "field=0_g.....r.....r.....b....br.g..grrg..bggr.bbgrr&steps=rbgbrrrb&goal=0_0_6_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第13問"

[[entries]]
query = "field=0_o.....o...o.o..oo.o..oooo..yoob..obyo.ygrrgbyobyobybrrybobrgyoobggyo&steps=yyybbbggygyb&goal=_1"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第14問"

[[entries]]
query = "field=0_y....yb..gyyy..ggbg..rbbyyyrrygggbyyyyybbrbbbgrryrrggyyygrrrrrryyy&steps=ybrbygry&goal=0_0_16_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第15問"

[[entries]]
query = "field=0_o....oo....yo....oy..ooyy..oooo..yyoy..yooyyooyooooyyooo&steps=ggyyggyy&goal=0_3_5_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Hard 第16問"

[[entries]]
query = "field=0_gggyoroooyorpppyorroyppproyoooroyggg&steps=rypgrpgy&goal=0_2_8_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Hard 第17問"

[[entries]]
query = "field=0_r....rp....yyy...prp...prpyrrypyyyrppy&steps=ppyyyprp&goal=0_2_8_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Hard 第18問"

[[entries]]
query = "field=0_y.....y.....b.g...bygg..rbyy..rrbb..&steps=rybygbyb&goal=0_0_6_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Hard 第19問"

[[entries]]
query = "field=0_ybb...oob...orr...yoo...yyg...brr...bor...boy...goy...ggy&steps=ryrrrbby&goal=0_0_7_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Hard 第20問"

[[entries]]
query = "field=0_bggbbroogborobbyorrooyogrrbygg&steps=gbybrgrbbb&goal=0_0_8_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Hard 第21問"

[[entries]]
query = "field=0_r.....grg...rgrg..grgr..rgrg..&steps=rgrrggrg&goal=0_0_6_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Hard 第22問"

[[entries]]
query = "field=0_gggbbybyrrrybyoogygyoogrgbbbgrgrryyy&steps=gbrbgbybgb&goal=0_2_10_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard 第23問"

[[entries]]
query = "field=0_r.r...grrgr.grbbgrgrbggrrg&steps=rbrrrrrg&goal=2_0_16_1_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard 第24問"

[[entries]]
query = "field=0_oo....rr...rgbr.rggbbrrbbggrorbgrooorroooooooooooooo&steps=rgrbrgrb&goal=0_0_8_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard 第25問"

[[entries]]
query = "field=0_grooorrrbobbrrbobrgggorgggooorr&steps=rgbbgbggrg&goal=0_0_8_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard 第26問"

[[entries]]
query = "field=0_r.....b....rryygyrbyrrgbbrggrrr&steps=ygrygyygrg&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第27問"

[[entries]]
query = "field=0_o.....or...orr...ooo...goy.o.oyy.o.ooo.y.obbgggooo&steps=bygyggbyry&goal=_1"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第28問"

[[entries]]
query = "field=0_rrbb..brbr..bbrr..rrbb..rbrb..bbrr.&steps=rbrbrb&goal=2_0_22_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第29問"

[[entries]]
query = "field=0_r.....rr...ygg...bbg.r.ygryrrgbyygbgrrgbbgbrygg&steps=byyyrgyyry&goal=0_0_11_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第30問"

[[entries]]
query = "field=0_b..b..brgrb.rggbr.rbrrbrrbgrbr&steps=gbrgrgbbgb&goal=0_0_8_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Hard 第31問"

[[entries]]
query = "field=0_y....bb....yyyybbbborroybogorybooggyyoorrbyorogbyoggob&steps=byggrrby&goal=_0"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Hard 第32問"

[[entries]]
query = "field=0_y.....o...yyo..yooy..oooy..oyyo..orro..roor..roor..orro..&steps=ryryryry&goal=_0"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard 第33問"

[[entries]]
query = "field=0_g.....r.g..rgpb.rppbrrrgpgbb&steps=bpgpgprpgr&goal=0_2_7_0_"
creators = "ワタリ"
source = "戦技研HP"
sourceDetail = "Hard 第34問"

[[entries]]
query = "field=0_b.rr..bbyybbgrbrrbgbrbbggbbrbg&steps=gybyrrgbgb&goal=0_0_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard 第35問"

[[entries]]
query = "field=0_b.....b....gr.b..ggbrb.rrrggg&steps=rbgbrrgb&goal=0_0_6_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第36問"

[[entries]]
query = "field=0_r..g..rg.ggrgggbbgrbyybrbbygggrr&steps=rrgbrygb&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第37問"

[[entries]]
query = "field=0_o.....o.....rrgrr.rggrb.yrybbgyyrrrg&steps=gyrybygyrg&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard 第38問"

[[entries]]
query = "field=0_y....gr...grgr.gryrg.rybyrg&steps=ggrgrygbgbgb&goal=0_0_7_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Hard 第39問"

[[entries]]
query = "field=0_yy....rr....bb....yy.brbrrrbbrbbbrrbrrr&steps=bybybyryrb&goal=0_0_8_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Hard 第40問"

[[entries]]
query = "field=0_r.....r....by.g.ryyrr.rbbbrgrrrryyy&steps=bybbggbrry&goal=0_0_8_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Hard 第41問"

[[entries]]
query = "field=0_gry...gryg..grygg.yybpbbybbppb&steps=bgyprgyb&goal=1_0_5_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Hard 第42問"

[[entries]]
query = "field=0_o....obg.rbbob.bybyorbbggg&steps=yybbrbrb&goal=0_0_6_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Hard 第43問"

[[entries]]
query = "field=0_bbb...rrgb..rgbb.bbbrr.&steps=ggbbrrbr&goal=0_0_6_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Hard 第44問"

[[entries]]
query = "field=0_g.....bb...rgg...rbb...rbo...ggrrroooooooooooo&steps=rgbbggbr&goal=0_0_6_1_0"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Hard 第45問"

[[entries]]
query = "field=0_rrrgggyyyrrrbbbyyy&steps=ybbbbgbryr&goal=0_0_7_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Hard 第46問"

[[entries]]
query = "field=0_y.....yybb..ooobo.orrro.bboyy.boooy.ooboo.yobbr.yyorr&steps=yrybbbyr&goal=0_2_7_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Hard 第47問"

[[entries]]
query = "field=0_b.....yy....byoyy.bbggg.&steps=bybybgby&goal=0_0_5_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Hard 第48問"

[[entries]]
query = "field=0_o.....oyrgb.oyrgbrorgbyrorgbyrorgbyooooooo&steps=ryryrgry&goal=_0"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Hard 第49問"

[[entries]]
query = "field=0_g.....gy....gyp...bypg..bbpgy.rpbgy.rrbby.&steps=rbpgbyygpg&goal=0_0_8_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Hard 第50問"

[[entries]]
query = "field=0_p..r..pprr.gggpppoooooooooooooroogo&steps=grggrrrpgp&goal=0_0_6_0_1"
creators = "ぷらいむ"
source = "戦技研HP"
sourceDetail = "Hard 第51問"

[[entries]]
query = "field=0_br..yygyggyrrbbgbbrbrrgyyggyggrbyyorrbbo&steps=yrrbgbyg&goal=_1"
creators = "shimogon"
source = "戦技研HP"
sourceDetail = "Hard 第52問"

[[entries]]
query = "field=0_bg...ggbb.bgybggbrrrbgbgggbbrbbbrrrgggrgryyygg&steps=rgrbbbrg&goal=1_0_4_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Hard 第53問"

[[entries]]
query = "field=0_b....byy...rrbyy.yryby.ybbrrr&steps=rybyrbyyry&goal=0_0_7_0_0"
creators = "hides"
source = "戦技研HP"
sourceDetail = "Hard 第54問"
