[[entries]]
query = "field=0_y.....b.....g....br....bryy..grrrrybggggbbg&steps=yyrbyygbry&goal=0_0_8_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Hard+ 第1問"

[[entries]]
query = "field=0_b.....y....rr....yg.g..gr.b..gb.r..gr.gg.yyyrg&steps=rggryygbgy&goal=0_3_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第2問"

[[entries]]
query = "field=0_g.g...bbg...bry.r.gryrbrggrbrrrryybb&steps=yggrbyyyrr&goal=0_3_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第3問"

[[entries]]
query = "field=0_b.r..br.rggob.ggrobrgorooogoooooo&steps=rbbbrggb&goal=0_0_6_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Hard+ 第4問"

[[entries]]
query = "field=0_y.....r.....r.....r.....b.....g.....g.....g.bg.gyybggyggg&steps=bygryyrryrgr&goal=0_3_8_0_"
creators = "moja"
source = "戦技研HP"
sourceDetail = "Hard+ 第5問"

[[entries]]
query = "field=0_r.....rr..bbbg..yyrg..bryg.bbrrybrgggybrryyb&steps=gybyrybygyrb&goal=0_0_11_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第6問"

[[entries]]
query = "field=0_y.....y.....r.....r.....g.....r...r.yy..yygybryrybbbrbbggbbybyg&steps=gygyrbybgyby&goal=0_1_11_0_"
creators = "any"
source = "戦技研HP"
sourceDetail = "Hard+ 第7問"

[[entries]]
query = "field=0_r....rrb..brrbyybryybbyyybrrbyrrbbrrrbyybr&steps=yybbbyrybyby&goal=0_3_11_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第8問"

[[entries]]
query = "field=0_bbrrggbyyrbgggybbygrrgyyyrbggryybbrr&steps=ygybgbrb&goal=1_0_4_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第9問"

[[entries]]
query = "field=0_yygg.grrbbyggbryyrrrbbb&steps=gyrrbbgygy&goal=0_2_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第10問"

[[entries]]
query = "field=0_br....rb....br....rb..yrbrbyyyrbyyrrbrbb&steps=rybyryby&goal=0_0_8_0_0"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第11問"

[[entries]]
query = "field=0_b..b.by..ybbyggybbrbbrbrryyrr&steps=yggbybyryr&goal=0_0_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第12問"

[[entries]]
query = "field=0_b....byybb.ygbbrbrrryrrbbgbygbggrgrgbbrrgyybbbyggybyrrybygggrr&steps=rbrgrgrgryrb&goal=0_0_16_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第13問"

[[entries]]
query = "field=0_b.....rb....yrb...byr...rby...byb...yry..rryr..yyryy&steps=bryyyryryr&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第14問"

[[entries]]
query = "field=0_r..r..g..y.ryg.b.gbyrb.yrbgr.byrrg.yyrgg&steps=byyyryrgrbby&goal=0_0_10_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第15問"

[[entries]]
query = "field=0_r....rrg...oggy..obyyrobbgrrgoggyggooyyroooorrboooobb&steps=ygbrbgyrrg&goal=0_0_10_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第16問"

[[entries]]
query = "field=0_r..y..bgrg..bbgg..grbr..ggrr..rbyb..rrbb.&steps=brybrbgyrb&goal=0_0_9_0_"
creators = "float"
source = "戦技研HP"
sourceDetail = "Hard+ 第17問"

[[entries]]
query = "field=0_rg...brgy..brgy..byby..rybr..rybr.&steps=rrgyryrbrb&goal=0_0_8_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard+ 第18問"

[[entries]]
query = "field=0_yy....rp..yrrppyypprryooproooorpoooorpoooorpooooyyoo&steps=yprpyyrpry&goal=0_0_9_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard+ 第19問"

[[entries]]
query = "field=0_bb....oo..bboo..oooo..oooo..oooo..bbrr..rrbb.&steps=rbrbrrbbrb&goal=_0"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard+ 第20問"

[[entries]]
query = "field=0_y....yby...yby...yby..oooooooooooo&steps=bbbybyby&goal=0_0_4_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard+ 第21問"

[[entries]]
query = "field=0_b.b...y.y..yoyb..yoyb..yoyb..oboo..oboo..obyy.&steps=bybyyybyby&goal=0_0_7_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard+ 第22問"

[[entries]]
query = "field=0_r....rroooorrogggrgoooobgorrrbgoooob&steps=rbgybyyyrbrg&goal=1_0_4_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard+ 第23問"

[[entries]]
query = "field=0_y....bbr.b.ryrybybyrbyrbybbyyrr&steps=rbrbrbrbrb&goal=0_0_8_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Hard+ 第24問"

[[entries]]
query = "field=0_r.....b....rryygbrbyrrgbbrggrrr&steps=grbbgbgyrg&goal=0_3_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第25問"

[[entries]]
query = "field=0_r.....g.b.ybb.ybryb.ygrrgyrrygggybbyyggbrry&steps=rbrrrrbbrrrb&goal=0_3_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第26問"

[[entries]]
query = "field=0_r.....r.....r.....g.b.ybb.ybryb.ygrrgyrrygggybbyyggbrry&steps=rbrrrbrbrb&goal=0_3_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第27問"

[[entries]]
query = "field=0_g.....bbbyyyoyorogyyrrggogoyobggyybboroborrrbbrr&steps=ybryrgrbby&goal=0_0_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第28問"

[[entries]]
query = "field=0_r.g...b.y.r.brygrrbgybrrrggbb&steps=ggrrrbygrb&goal=0_2_8_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第29問"

[[entries]]
query = "field=0_yg...ygbyyyygbgggygbrrrrrrybygggybyrrryby&steps=rygbryrbgy&goal=0_0_11_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第30問"

[[entries]]
query = "field=0_rroorrrobboryobrbbyyooyybbrboyrobborrroorr&steps=bbbybbbyrr&goal=0_0_9_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第31問"

[[entries]]
query = "field=0_r.....y.....or.yo.oobyo.ogoyo.ogyoo.ogbro.yyrrgrybybgrrybbg&steps=gbrrgyrbry&goal=0_0_10_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Hard+ 第32問"

[[entries]]
query = "field=0_b...orryo.ooryo.ogoyo.ogyoo.ogbro.yyrrgrybybgrrybbg&steps=gbrbyyrgry&goal=0_0_10_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Hard+ 第33問"

[[entries]]
query = "field=0_o.rro.ooyyo.oyoyo.obyoo.obrro.yygrgrybybgrrybbg&steps=rbgbryrgggry&goal=0_0_10_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Hard+ 第34問"

[[entries]]
query = "field=0_y.....gg.yyrry.ppyprpypgppgggrrryyyggg&steps=ypyryggryyyy&goal=0_0_10_0_"
creators = "ワタリ"
source = "戦技研HP"
sourceDetail = "Hard+ 第35問"

[[entries]]
query = "field=0_oo....ry....ry....ry....yo....ro....ro.y..ro.yg.yyggr.oygyy.rorryrry&steps=ggrgrygy&goal=_2"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Hard+ 第36問"

[[entries]]
query = "field=0_r.....o.....rrrbb.ggyyyrgbbbgrrrrggr&steps=rgyybyyybbrg&goal=0_0_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第37問"

[[entries]]
query = "field=0_o....gbbr..gbyr..gyyr..yrgb..yrgb..yrgb.&steps=bgbrbybgbrby&goal=0_0_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第38問"

[[entries]]
query = "field=0_y.....y....br....bb....rr...gbyrbbbggr&steps=rbrbgyrbbb&goal=0_0_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第39問"

[[entries]]
query = "field=0_o.y...o.rb..bgbb.bbrrr.rryybggrybrbbggggrrr&steps=yyrgryrbryrb&goal=0_0_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第40問"

[[entries]]
query = "field=0_g.....r.....g.....g.b...gbg...rpyggrrggyygrbbggrgggbrr&steps=pybbyybyppgy&goal=0_0_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第41問"

[[entries]]
query = "field=0_yyr...byb...bbbg..bggooyygbooyoygorryyyggygbbrrygbgggrg&steps=rrbgygyyyygb&goal=0_2_13_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第42問"

[[entries]]
query = "field=0_r...r.y...ryr...yryy..bybb..rryy.bbbggg&steps=gybryyby&goal=0_0_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第43問"

[[entries]]
query = "field=0_oo.b.obbobryybobrryorrbggoyrbbgyygrrrogg&steps=yrgbybgrrb&goal=0_0_10_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Hard+ 第44問"

[[entries]]
query = "field=0_bgby..bgby..bgby..yrgr..yrgr..yrgr..gbyg..gbyg..gbyg.&steps=ygybrgybgbrg&goal=0_0_12_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Hard+ 第45問"

[[entries]]
query = "field=0_b..r..r..y..b..b..y..r..yb.ryrrrbyy&steps=ryrbryrbrb&goal=0_0_7_0_"
creators = "K-NES"
source = "戦技研HP"
sourceDetail = "Hard+ 第46問"

[[entries]]
query = "field=0_r.y...r.y.bby.rybyy.ryrrgbbgrggbggoooooooooooooooooo&steps=rrbgyrgrbr&goal=0_0_9_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Hard+ 第47問"

[[entries]]
query = "field=0_r...r.r...grg..rgrr..rrbbr.gggbrr&steps=grrbggrg&goal=0_2_6_0_"
creators = "和樹"
source = "戦技研HP"
sourceDetail = "Hard+ 第48問"

[[entries]]
query = "field=0_ggrgrrgrgrgrrggrrggoooorgrrggrrgrgrgrrgrgg&steps=rgrgrgrgrg&goal=2_0_19_0_"
creators = "sim"
source = "戦技研HP"
sourceDetail = "Hard+ 第50問"

[[entries]]
query = "field=0_g...rbr.bbbrr.yyygg.oooro&steps=rrbgbbryrb&goal=0_0_6_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Hard+ 第51問"

[[entries]]
query = "field=0_pp..pppogroprryygggryogrggoorroyoopooyyppo&steps=bypgrbpgbbpy&goal=1_0_5_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Hard+ 第52問"

[[entries]]
query = "field=0_bbrr.ogggrooyyyboorrbbooooooo&steps=gbrbryrb&goal=0_0_3_1_0"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Hard+ 第53問"

[[entries]]
query = "field=0_br...brg...rbb...gby..bggb..bbyygg&steps=rbbygbygbg&goal=0_0_7_0_0"
creators = "shimogon"
source = "戦技研HP"
sourceDetail = "Hard+ 第54問"

[[entries]]
query = "field=0_g..b.gg..gryb..rgby..ggyy..rybb.gggyb.&steps=bbgyyrgbyg&goal=0_0_8_0_0"
creators = "すぴぃちゃん"
source = "戦技研HP"
sourceDetail = "Hard+ 第55問"

[[entries]]
query = "field=0_ggbb..grrr..yygg..bbbg.rrryyyoooooooooooo&steps=bybrbgygyr&goal=0_0_4_1_0"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Hard+ 第56問"
