[[entries]]
query = "field=0_o....ob....bb....oo..oobboooooboobboooboboobb&steps=yybbrrbbrrryrrry&goal=0_2_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第1問"

[[entries]]
query = "field=0_y.....yy....bb....brr...ggr...gyb...yybbyyrbyyyrrbby&steps=byrbgyryby&goal=0_0_10_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第2問"

[[entries]]
query = "field=0_ggry..bbgy..bybr..rryr..yyrb..ggbb..gbgg..rbyg..rryy.&steps=ybgrybbgryrg&goal=0_0_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第3問"

[[entries]]
query = "field=0_y....yy....yrryybbrybrybybyyryrybrybrryybb&steps=byrbbyrbyyrb&goal=0_0_11_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第4問"

[[entries]]
query = "field=0_oyyggogoygoyggooyybboorrborbororrbbooooooo&steps=rbryrgrbryrg&goal=0_2_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第5問"

[[entries]]
query = "field=0_oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo&steps=rgrgrgrgrgrgrgrgrgrgrrggggrgrg&goal=2_2_16_0_"
creators = "飛車ちゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第6問"

[[entries]]
query = "field=0_bbrr..gogo..rrbb..ogog..rrbb..gogo.&steps=rbrbrbggbbrrrb&goal=0_0_8_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第7問"

[[entries]]
query = "field=0_b...rrr..groooooo&steps=rbgggggggbrrrb&goal=0_0_5_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第8問"

[[entries]]
query = "field=0_o...o.o..ooor..ooro..oroo..rooo..&steps=ggrrggrrggrrrgrg&goal=0_0_5_0_0"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第9問"

[[entries]]
query = "field=0_g....bg....by....yy...brr...ybr...gby..ggyy.&steps=ppgpypgbgbyyybyr&goal=0_0_9_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第10問"

[[entries]]
query = "field=0_ppyyo.poyor.yyorr.yoroy.orryy.royoprryypp&steps=rypyryrprprp&goal=2_2_20_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第11問"

[[entries]]
query = "field=0_rbybbbrbygggrbyrbrgggrbrbbbrbr&steps=rbyyrgrybbygyb&goal=0_0_11_0_"
creators = "ぷらいむ"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第12問"

[[entries]]
query = "field=0_gggrrrrbbbyyrryggyggybbbygyrrrybbbgg&steps=bybbryyyrbygrg&goal=0_0_11_0_0"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第13問"

[[entries]]
query = "field=0_b.....bb....ggg...bbb...rggrbbrrgrgbyybbgrybybrrrrryyy&steps=rgbybgrbrybg&goal=1_0_4_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第14問"

[[entries]]
query = "field=0_bgb...bbg..bggr..bgrbb.brrbr.&steps=bgbgrgrgrgrg&goal=0_0_5_0_0"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第15問"

[[entries]]
query = "field=0_yrrbggyyrbbgbryygbbrrygggbbryyggbrryrbggyrrbbgyy&steps=rbybgybgrbyrgy&goal=0_0_9_1_0"
creators = "shimogon"
source = "戦技研HP"
sourceDetail = "Lunatic+ 第16問"
