[[entries]]
query = "field=0_gy....gg...bbg...ybr...ryrb..rybbyggrrggbbgrgbgrgyrbggryyrbrbrrbgrb&steps=rgyggyygbrby&goal=0_0_15_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Chaotic 第1問"

[[entries]]
query = "field=0_o.....b.....b....gr....ggr...ybr...yyg...rbb...ggb.byrrr.bbyyy&steps=rgggbyggbrgrgrbr&goal=0_0_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Chaotic 第2問"

[[entries]]
query = "field=0_bbbgggoroorogggbbborooroorooroorooro&steps=ybyrygyyrryrgb&goal=0_0_8_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Chaotic 第3問"

[[entries]]
query = "field=0_rrygbbryyggbggbryygbbrryyyrbggyrrbbgbbgyrrbggyyr&steps=ryyggbgbyrbrgrby&goal=0_0_15_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Chaotic 第4問"

[[entries]]
query = "field=0_b...rrgg.gggyyyoooooooooooooooooooooooooooooooooooo&steps=yyrgyyyyggygyyggrg&goal=0_0_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Chaotic 第5問"

[[entries]]
query = "field=0_r..bgbyrgbgbyrgbgbyrgrroobbroggoboybbyooyyoyoroggoyrrooyo&steps=bybgbrbgyrbg&goal=0_0_12_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Chaotic 第6問"

[[entries]]
query = "field=0_yryr..rbry..yryg..gygy..bgbr..ryrb..yryr..ryry..bbgg.ggyybb&steps=bbggbbggrryyrryy&goal=_0"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Chaotic 第7問"

[[entries]]
query = "field=0_y.....orro..ooro..oroo..obbo..bryb..yybbybrrryy&steps=bbrrryyybyrbby&goal=0_0_9_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Chaotic 第9問"

[[entries]]
query = "field=0_rr....gr....yg.r..yyrr..ggygbygyybyybgbbbbryygbggyggrrgryy&steps=byrggyggrggy&goal=1_0_4_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Chaotic 第10問"

[[entries]]
query = "field=0_pgggyyybooobbbyooobbyyrrrroogoorrbggypbboyy&steps=ybpryrpbpgpppbgy&goal=0_0_11_0_0"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Chaotic 第11問"

[[entries]]
query = "field=0_yb...oooo..obbo..obgo..ooog..obby..oggb..oyby..bbyy.&steps=bbbybygyyyggbgby&goal=0_0_9_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Chaotic 第12問"
