[[entries]]
query = "field=0_y.p..ypyy..yypy.&steps=yp&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_y.p...pyy...goy..ggop.yyypp.&steps=yg&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_b.....rb...ggrb..grrb..rbgo..rrbg..bbgg.&steps=rg&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_r.....yy....rr....yy...ryr...yoor.ryyrryrrooyy&steps=ry&goal=0_0_5_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_by...obb...yyob..oyoy..bbbyy&steps=yb&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_y.....b..by.bb.bb.yy.oy.yobby.oyyby.bybyb.bbobb.&steps=by&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_gg....gbg..goggbbbbobb&steps=bg&goal=0_0_3_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_y....yy....oo..y.yo..yyoyyy&steps=yy&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_p.....p.....p.....b....bb....pp....pob...obb...boo..bopp..bbop..&steps=bp&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_g....gr....ggr...rorr.rrggg&steps=rg&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_ob...bbg...bob...ggb...bgbob.bbobb&steps=bb&goal=0_0_2_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_b.....r.....b.....bg....br....gr....gr....bg....rr....rg.g..bbgg&steps=rb&goal=0_0_5_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_gg....yg...yyoy.gggyy.ooyggg&steps=gy&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_rr...brbb..bbobrrrrorr&steps=br&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "ミニなぞぷよTA大会"

[[entries]]
query = "field=0_bb....gggr..rorr.brrbb.&steps=brbgbr&goal=0_0_5_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2018"

[[entries]]
query = "field=0_r....gg....gb.rggrbbgrgrrggrr&steps=rgrgrbrg&goal=0_0_7_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2018"

[[entries]]
query = "field=0_r.....hb....rh....hb....rh....hb....rb..&steps=yybbryrrbyrb&goal=0_0_5_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2018"

[[entries]]
query = "field=0_rbb...rrb...bby...byy...rrr...yyb...ybb...brr...bbr..&steps=bryrbr&goal=0_0_4_1_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2018"

[[entries]]
query = "field=0_yy..gggy..oobb..rrbg..ryyg..obyg..gbor..gbrr.yyygggrrhhbb&steps=yrbgygrgrbyb&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2018"

[[entries]]
query = "field=0_oo...bbor..borr..oooo.&steps=br&goal=_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"

[[entries]]
query = "field=0_by....bb.yyyyoyy&steps=bbby&goal=0_0_3_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"

[[entries]]
query = "field=0_y.....o....ggo...ygy...ybyy..bbgg..ogoo.&steps=gggyyb&goal=0_0_5_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"

[[entries]]
query = "field=0_p.....b.....o.....b.....o...p.bb..p.po.&steps=bpppbbbp&goal=0_0_4_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"

[[entries]]
query = "field=0_g.....o.....g...g.gbb.ggogb.&steps=bgbgbgbbgg&goal=0_0_5_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"

[[entries]]
query = "field=0_o.....b....gr..ogrgr.orrbr.bbbrbo&steps=bgggbbbgbgbr&goal=0_0_7_0_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"

[[entries]]
query = "field=0_gbobyrgogbyoorgbogyrgorgyroyrgyobyroogbyoyrgbobyrgogbyrorgbo&steps=ybgrygyrrbbgyr&goal=0_0_4_1_0"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"

[[entries]]
query = "field=0_yy....gyyyg.ggygg.bbbrr.brbbr.rryyy.ggggr.yggrr.yybbb.rrrry.rbrgggbb&steps=brygbyrggrgbbyry&goal=0_0_13_1_"
creators = "π"
source = "戦技研活動日誌"
sourceDetail = "招待状2019"
