[[entries]]
query = "field=0_r.....b..ybrbb.bbgrr.yy&steps=ygbgbg&goal=0_0_5_0_"
creators = "sai"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.1"

[[entries]]
query = "field=0_ooo...ooooo.gbboooggrbyobbbrbyrrrbyy&steps=rrbgrbbgrb&goal=0_0_7_0_"
creators = "ざいろ"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.2"

[[entries]]
query = "field=0_ggb..bgpppggrbrgrrbbbgprbrrrgppgggpbb&steps=rrbpgbrbrg&goal=0_0_10_0_"
creators = "ざいろ"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.3"

[[entries]]
query = "field=0_b.....bbg...rgrrr.rrggg&steps=grggbr&goal=0_0_5_0_"
creators = "sai"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.4"

[[entries]]
query = "field=0_oo....oo...ryo.ryogy.ggopy.rroby.ryobgoooorgoooyrgooobrpooobypooopyy&steps=ypypppgg&goal=_2"
creators = "日和"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.5"

[[entries]]
query = "field=0_g....gg....bb...rbr...ggg...rrr...&steps=gbgb&goal=0_0_4_0_"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.6"

[[entries]]
query = "field=0_ryyr..gybr..ggbr..ryby..rryy&steps=brrryrgr&goal=0_0_7_0_"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.7"

[[entries]]
query = "field=0_g.....g.....g.....boo...bgy...boy...yoy...ybo...ybo...obo...ggo.&steps=yyybyyyb&goal=_4"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.8"

[[entries]]
query = "field=0_g.....g.....g.....b.....b.....y.....y.....rr....ryy...grb.r.ggrgr.rrbbb.&steps=rbgyrbrb&goal=0_0_7_0_"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.9"

[[entries]]
query = "field=0_yp.y..py.g.gppyg.ggyyg&steps=pppgyygp&goal=0_0_6_0_"
creators = "ざいろ"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.10"

[[entries]]
query = "field=0_y.brr.y.byy.obrbyrrrggg&steps=gyrrrryyrr&goal=0_0_7_0_"
creators = "sai"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.11"

[[entries]]
query = "field=0_p.....p.....g..rrgg..yryy..yygy.rrrgg.&steps=gygprpyr&goal=0_0_7_0_"
creators = "ざいろ"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.12"

[[entries]]
query = "field=0_oo..oorroo&steps=yyyyo1_1_1_1_1_1oyyo1_1_1_1_1_1orryyyyyy&goal=0_0_4_0_"
creators = "えぷそん"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.14"

[[entries]]
query = "field=0_r.....r.....r.....b.....rr....br....bb....ry....yy....rg....rrg...&steps=ggyr&goal=0_0_5_0_"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.15"

[[entries]]
query = "field=0_bbg...gry...yyb..ybbr..byby..rryy..rggg..bbyyy&steps=grygbbrgrb&goal=0_0_9_1_2"
creators = "sai"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.17"

[[entries]]
query = "field=0_g....gog..oogo..bbgyy.oygbo.oyobo.oyobo.&steps=ybgygbgygbgg&goal=0_0_7_0_"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.18"

[[entries]]
query = "field=0_rrro..roorrbroooggboooogroooooroooooroooooooooooooooooooooooooooooo&steps=rgrgrrrgrg&goal=0_2_5_0_"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.19"

[[entries]]
query = "field=0_y.....y.....b.....y.....r.....y.....yb....orr..boyrybbrryy&steps=byrbry&goal=0_2_5_0_"
creators = "ざいろ"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.20"

[[entries]]
query = "field=0_oo...ooo...bbo...ooobooobbobbobobbobobb&steps=bbbbbbbb&goal=0_0_5_0_"
creators = "えぷそん"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.21"

[[entries]]
query = "field=0_r..g..r..g.bb..b.yy..y.rg..rgrgbbrgrgyyrg&steps=gbbbbygr&goal=_0"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.23"

[[entries]]
query = "field=0_obopppbobooooborrrrrrpppooooooppprrr&steps=rrpbbbprpb&goal=0_2_8_0_"
creators = "きゅい"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.24"

[[entries]]
query = "field=0_rr....rb....grr...gbr..&steps=bbrgrg&goal=0_0_4_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.25"

[[entries]]
query = "field=0_b.....r....hr....gb....bb....rr...grb...ggh..&steps=bbrrrb&goal=0_0_5_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.26"

[[entries]]
query = "field=0_r.....r.....r.....b.....b.....r.....b.....yr...gbr..ggbr.&steps=bbyygbry&goal=0_0_6_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.27"

[[entries]]
query = "field=0_b....rb....grr...rgg...grr.&steps=bgbgrgrg&goal=0_0_5_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.28"

[[entries]]
query = "field=0_y.....g.....g..b.gy..ggrr.bgbyyy&steps=ryybyggr&goal=0_2_6_0_"
creators = "pakista"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.29"

[[entries]]
query = "field=0_by.y..bbyb..yybo.&steps=bbyyyb&goal=0_0_4_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.30"

[[entries]]
query = "field=0_b...yry...yry...yry...rggg..rrbb.&steps=bryrgy&goal=0_0_5_1_0"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.31"

[[entries]]
query = "field=0_ogg...ogb...obb...bgg...bbg...ooo..&steps=brbrgrgr&goal=0_0_5_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.32"

[[entries]]
query = "field=0_g.....og..y.rg..ryyg.ryrrr.&steps=yryyyr&goal=0_0_5_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.33"

[[entries]]
query = "field=0_b..orbb..bboo..boro..oorr.&steps=brrrbr&goal=0_0_4_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.34"

[[entries]]
query = "field=0_brr..obbr..oooo..oooo..ooorr.&steps=brbrbbrb&goal=0_0_4_0_"
creators = "せりー"
source = "津田沼エースぷよぷよ対戦会HP"
sourceDetail = "No.35"
