[[entries]]
query = "field=0_gr....ggr...rrg.yy&steps=ggggyy&goal=0_0_4_0_"
creators = "ぷよまつ"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第1問"

[[entries]]
query = "field=0_ry....ry..yyygggrrrbbb&steps=brrrrg&goal=0_0_5_0_"
creators = "可憐な私(笑)"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第2問"

[[entries]]
query = "field=0_bbgr..gbrr..rrbg..rgbb.&steps=rbrb&goal=0_0_5_0_"
creators = "飛車ちゅう"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第3問"

[[entries]]
query = "field=0_yy....ygr...gry...gry...gry...&steps=ryrrry&goal=0_0_5_0_"
creators = "かにすけ"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第4問"

[[entries]]
query = "field=0_g.rgr.grrggr&steps=gggrrr&goal=0_0_4_0_"
creators = "可憐な私(笑)"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第5問"

[[entries]]
query = "field=0_b.....g.....b.r...bgry..&steps=rbgygryy&goal=0_0_4_0_"
creators = "貧弱PC"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第6問"

[[entries]]
query = "field=0_r.....r.gyr.ygyrgyrgyrgyr&steps=ygrgyg&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第8問"

[[entries]]
query = "field=0_g.....b.br.rrrbbrybgrryybb&steps=rgygbb&goal=0_0_6_0_"
creators = "あいつが噂の"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第9問"

[[entries]]
query = "field=0_b....rbygryrygrrbrbygyybbygryb&steps=rybyyy&goal=0_0_8_0_"
creators = "貧弱PC"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第10問"

[[entries]]
query = "field=0_oo....oo...org...orgo..rgbooorgbboo&steps=rryyrrybyy&goal=0_0_5_0_"
creators = "千春"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第11問"

[[entries]]
query = "field=0_p.....p....yby.yybbyy&steps=yppbyr&goal=0_0_4_0_"
creators = "ソウマ"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第12問"

[[entries]]
query = "field=0_o.yo..r.yo..r.bb.&steps=byyrrb&goal=0_0_3_0_"
creators = "PRRN"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第14問"

[[entries]]
query = "field=0_bry...bry.y.bry.ybrygbgbrygbgbrygbg&steps=ygbgyg&goal=0_0_7_0_"
creators = "可憐な私(笑)"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第15問"

[[entries]]
query = "field=0_yr....rr..o.oooororoyrbrrrgyybggybbr&steps=yyrgry&goal=0_0_7_0_"
creators = "貧弱PC"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第16問"

[[entries]]
query = "field=0_r..b..r..b..r..o.obrbrbrbrbrbrbrbrorobrbr&steps=rbbbrb&goal=0_0_8_0_"
creators = "PRRN"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第17問"

[[entries]]
query = "field=0_g.....rg....rb....yryg.ryybygrbbyygg&steps=rgryrg&goal=0_0_7_0_"
creators = "つみき"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第18問"

[[entries]]
query = "field=0_y.....r.....r...o.oooororgyrbrrrgyybggybbr&steps=yyrrry&goal=0_0_7_0_"
creators = "貧弱PC"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第19問"

[[entries]]
query = "field=0_y.y.ygpgy.pggpgpyypgypygpgy&steps=pypg&goal=_6"
creators = "PRRN"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第20問"

[[entries]]
query = "field=0_b.....r.....bb&steps=rrrrbb&goal=0_0_2_0_0"
creators = "可憐な私(笑)"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第21問"

[[entries]]
query = "field=0_yb.r..rybr..rybrbyryb&steps=bbo2_2_2_2_2_2orbrb&goal=0_0_5_0_"
creators = "貧弱PC"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第22問"

[[entries]]
query = "field=0_r.p...rbp...rbpr.&steps=brbprrrr&goal=0_0_4_0_"
creators = "貧弱PC"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第23問"

[[entries]]
query = "field=0_g.....y...r.y.g.bbr.g.brryy&steps=rbrrrg&goal=0_6_5_0_"
creators = "せりー"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第24問"

[[entries]]
query = "field=0_y.....grby..ggrb..rrbby.&steps=yybgo3_3_3_3_3_3obbby&goal=0_0_5_0_"
creators = "ろじろじ"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第25問"

[[entries]]
query = "field=0_r.....b.....r.....b....bbgyrgbbggrggrryyrbrgyrgb&steps=rbgrgg&goal=1_0_3_0_"
creators = "飛車ちゅう"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第26問"

[[entries]]
query = "field=0_y.r..rrgr.ryrg&steps=yyggrr&goal=0_0_4_0_"
creators = "可憐な私(笑)"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第27問"

[[entries]]
query = "field=0_gpp...pgp...ppg...yrr...ryr...rry.&steps=rppgry&goal=0_0_6_0_"
creators = "ルヨル"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第28問"

[[entries]]
query = "field=0_g.....rbr...rrb.rrbbgbbb&steps=brgbrg&goal=0_0_5_0_"
creators = "ぜっとり"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第29問"

[[entries]]
query = "field=0_b.....y....by...bbo...yyobb.yooob&steps=yyyb&goal=0_0_4_0_"
creators = "りさ"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第31問"

[[entries]]
query = "field=0_oooo..rrro..oooo..orrr..ooooo&steps=rrrr&goal=0_0_2_0_"
creators = "ルヨル"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第32問"

[[entries]]
query = "field=0_r....ygy..yrgry.yrgry.&steps=ryrgry&goal=0_0_5_0_"
creators = "PRRN"
source = "ぷよっとじっけんしつ！"
sourceDetail = "なぞぷよマスターへの道 第33問"

[[entries]]
query = "field=0_rg....brrr..byyo..bgyb..oggb..rrrb.&steps=ygggbgrb&goal=0_0_7_0_"
creators = "りさ"
source = "ぷよっとじっけんしつ！"
sourceDetail = "ぷよぷよ名人戦"

[[entries]]
query = "field=0_b.....b.....rg...bbbr..oooobbobbobbbobro&steps=gbrbgbgb&goal=0_0_6_0_"
creators = "せりー"
source = "ぷよっとじっけんしつ！"
sourceDetail = "ぷよぷよ名人戦"
