[[entries]]
query = "field=0_o.b...ooo...ooo...oooo..oyyoo.gyboooybbooogrgoooggrgoorrggoo&steps=byyyyybbyyyb&goal=0_2_8_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_o.....o.....y.o...yob...ybg...grgo..ggro..rrggoo&steps=gbby&goal=_2"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_byb...yby...byb...yby...oyb...ooy.&steps=bbbbby&goal=_2"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_b...b.b.b.b.r.b.y.r.y.y.bbbob&steps=rrbbyb&goal=0_2_4_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_oo..oooo..ooooooooooooooooyrooooyyrooorroooo&steps=ybrbrbrrby&goal=0_2_4_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_y....rr.rr.ryrbr.orryb.&steps=byrrrb&goal=0_2_5_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_g.....r....brg.yrbbg.&steps=yrgbyy&goal=0_2_4_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_b.....b.....g.....g.....y.....byg..bboo..oooo&steps=gybbyb&goal=0_0_4_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_y.....g....yg.grbrr.ggror.rrobgy&steps=rygbgb&goal=0_0_6_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_b.....rr....rb....ooy...oyy..&steps=bbry&goal=0_2_3_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_r.....r.gr.og.ggrggorrbboo&steps=gbrrgb&goal=0_0_5_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_b.....b.....o.....o.....g.....gr....gbr...rro...&steps=brrrrg&goal=0_0_4_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_bb....gg....gbg...bgb..&steps=bgbgbg&goal=0_0_4_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"

[[entries]]
query = "field=0_r.....g...boro..borg..bogg..&steps=bgrggg&goal=0_2_4_0_"
creators = "あじ"
source = "X"
sourceDetail = "#あじのなぞぷよ"
