[[entries]]
query = "field=0_rrr...bbg...bgg...rrr...gbb...ggb...rrr...bbg..obggo.&steps=rbbgrb&goal=_3"
creators = "あすなろ"
source = "X"
sourceDetail = "なぞぷよ大会没問"

[[entries]]
query = "field=0_rrr...bbg...bgg...rrr...gbb...ggb...rrr...bbg..obggo.&steps=rgbgrg&goal=_3"
creators = "あすなろ"
source = "X"
sourceDetail = "なぞぷよ大会没問"
