[[entries]]
query = "field=0_y....ryy.obrrh.rbboorrrrryyy&steps=rybrry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyrr..yoor..rryy.bbrybbboooobrrryyy&steps=byryrbry&goal=0_0_8_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yrr..yyryb.bbbyb.rrryb&steps=bryryb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyr...yrrbb.byyybhbbrrr&steps=bryryb&goal=0_0_6_0_0"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bb.r..ybrr.yrrby.yrbbyy&steps=rybyrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy....ybb...rrb.rbbry.rrbyy.&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyyr..bbrr.rrbob.ryyybb&steps=bybryr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbb...yrr...yry...yby...bby..orrr.&steps=brryby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_b.....by....byy..rrbbrrrbyyyr&steps=yrybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_o....yyo...ybrr..bbyr..ryyb..rrbb.&steps=ybrbry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y....ry...yry..byro..byoo..brob..rrbb.&steps=bryrby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_br....yr....yy....bb....rb....yy....yb...orbo..orro.&steps=rbyryb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r....rr...bby.y.byy.rrrbb.yyyrb.&steps=bybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rbbb..rryy..yyoy..ybbr.oobrr.&steps=ybbryr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyr..byrrb.bbobbrrryyy&steps=brbyry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy....yrr..boor..byyy..bobb..rrrb.&steps=rbybyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r....yrr..byybb.bboobrrryyy&steps=byrbry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbr...brry..yoyy..yybb..rrrb.&steps=brybry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbb.rrryyybbbrrrooyyyo&steps=brbyyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.rr..yyrb..oobb.bbboy.rrryy&steps=rbbyyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyy.rrooobrbyyrbbbyrrb&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyy.yybrr.ybbrb.rrrbb.&steps=rbbyry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_b.....bb....yy...rry...yrbrr.yybbr&steps=brryby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yrb...yrb...yrb...ooo...byr...byr...byr..&steps=bybryr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y..bbyy..brrr..ryyb.rrybb.&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r.....r.....r.....o....byb...byb...byb...ooo..yyyrrr&steps=rbbyyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_by....byy...brrb.rorbb.rryyy.&steps=byrbry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_ybr...ybr...ybr...boy...boy...boy...rrr..&steps=bryrby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.....yyb...rbby..rryy..oobb..rrrb.&steps=brybyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyrb..yrrb..bbob..byrr..oyyr.&steps=rbybry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyy...rbbb..rroy..bbby..rrry.&steps=ybyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rrr...ybbb..yyoy..bbby..rrry.&steps=yrrbby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r.....rroo..ybbb..yyoy..rrry..bbby.&steps=byrbyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y....yyr...brr...bby...ryyb..rrbb.&steps=rbbyyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_ryby..ryby..ryby..oooo.bbbrrr&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyy...rrbbb.ryyyr.bbbrr&steps=byyrbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_brrr..bbyy.rryby.ryybb.&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.....o...y.y..oyoy.yoyoy.oyoyo.ooooo.hyyoy.hooyy.oyyooyoyoyyyyoyoyooyoyo&steps=yyo1_0_0_0_0_0oyyo0_0_0_0_1_0oyyyy&goal=0_0_8_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.....y.....y.....oy....oo....ooy.y.ooyoyoyoyoy&steps=yyo0_0_0_0_1_0oyyyy&goal=0_0_4_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yybb..yryb..rryy..oooo.bbbrrr&steps=rbbyry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy....yr....brr...bbyy..ooyrr.obbbr&steps=yrrbby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.....yyr...brr...bbo...ooy...ryyb..rrbb.&steps=rbbyyr&goal=0_1_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy...bby..rrbr..ryyr..bbyr..booo.&steps=ybbrry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy....yr....brr...bbyy..rrryb.ooobb&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy...bby...bro...yrr...yoo...yobb..rrrb.&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.....yyb...rbb...rro...bbo...ybr..yyrr..&steps=rbyrby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy...bby...brr...yro...yoo...yobb..rrrb.&steps=yrbyrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_b..y.rbbyy.ryrrr.ryybbb&steps=yrybrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyy...roo...rrbb..ooob..ryyy..rooo..rbbb.&steps=brryyb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbb...yor..yyorr.rooob.rooob.ryyyb&steps=rbyrby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yr...yyrr..roob..roob..rbyb..bbyy.&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_ryy...roy...ror..bbor..boor..yobb..yybo.&steps=brryyb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rry...royy..boobb.booob.booor.yyyrr&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rrr...yob...yob...yob..bboy..booy..rrry.&steps=ybbrry&goal=0_1_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_ryy...roy...rob.bbbob.rooob.rryyy&steps=rybryb&goal=0_1_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_brr...bor..ybob.yyoob.rooob.rryyy&steps=rbyrby&goal=0_1_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_br....br...ybr...yoob..yoob..oryb..rryy.&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_ryy...roy...rob...bob...bob...boy...roy...rry..&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y....ryy...rrb...oobb..boyyy.bbrrr&steps=brryyb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bb....br....yrr...yyo...oooy.roboy.rrbby.&steps=brbyry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rrr..yybb..yoby..boyy.bbrrr.&steps=bryybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbbyy.roooy.robbb.rooor.yyyrr&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bb....byy...rry...roo...orrry.bbbyy&steps=rybryb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_o..yrrr..yobb..ybob..rbbo..rryyy&steps=yrbyrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_br....br....bry...yoy...yoyb..yoob..rrrb..&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_ybbr..yobr..yoor..booy..broy..brry.&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rrrbb.yooob.yooyr.yoyyr.bbbor.&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_b.rrrybyyyoybobbbyorrroo&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbrr..byryy.yyobyrrrbbo&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyyrrrbrbyyybrbooobrb&steps=rbbyyr&goal=6_0_25_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bb....rb....ry...yry...yoy...yoo...ooo.rrrbbb&steps=byyrrb&goal=0_7_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rr....br....by...yby...yoy...yoo...ooo.rrrbbb&steps=byyrrb&goal=0_7_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbb...ory...rryyy.bbrryyobro&steps=ybbrry&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r....rr...yyb..rryb..rbob..obbyyy&steps=rybryb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_o.....yyy...rrbbrbbrybrrbyyo&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rr...yyr...ryb...rbb...rooy..oooy..bbby.&steps=rbyrby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rr...yyr...ryb...rbb...roo..bbbyyyoooooo&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_obbb..roro..rbrb..rbrb..obob..rrro..oooo.&steps=rbrbrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_obbb..roro..rbrb..rbrb..obob..rrro..oooo.&steps=rbrbrb&goal=0_0_3_0_0"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rrrb..obob..bbob..yooy..yyoy..rrry.&steps=ryybbr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyy..bbbo..yoor..yoor..yoor..bbbo..orrr.&steps=rbbyyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bb...rob..rroo..bbbo.rooob.roobb.roorrr&steps=rbrbrb&goal=0_0_5_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyr..byorr.bboob.yyyob.orrrb&steps=byyrrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.....yyb...bobb..byyy..borr.rrror.&steps=rbbyyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r..ybrr..ybyy..ybyb..rrrb.oooobo&steps=yrbyrb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bboobbbrrorbyrorryyyooyy&steps=yrrbby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyoy..yoyy..bobb..bbob..rorr.orroro&steps=byrbyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rrr..yyoy..yooy..rooyr.rooor.ryyyr&steps=yryryr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r..y..rooy..ryyr..yoor..yoor..oooo..yyyo..rooy..ryyo..rooy..yyyo..oooo.&steps=ryryryry&goal=0_0_7_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bb....yyor..yobb.bbbob&steps=rrybbbbr&goal=0_0_5_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_ryy...roy...rob..bbobb.byoor.oyyrr.&steps=brryyb&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bbr...brr...yyby..ryby..rrby.&steps=ybrybr&goal=0_1_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_h...rrr...hyyy..bbbr..hrrh..rhhr..brrb.rrbbrrryrryr&steps=rbbyrybr&goal=2_1_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yyb.rrryb.ybbrb.yybrr.&steps=rbbyyr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yybb..yoob..rryy..rbyr..bbrr.&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_bb....brrry.yyyoy.rrooy.rbbbo&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_rbb...rob...ooy...boy...boy.yyyrrroooooo&steps=rrbybrby&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_yy....ry....rr...yybb..ybrb..bbrr.&steps=ybrybr&goal=0_0_6_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_y.....bg....bb....gggrr.&steps=yyrbry&goal=0_0_4_0_"
creators = "iso"
source = "X"
sourceDetail = "光のなぞぷよ"

[[entries]]
query = "field=0_r...rrg...rgg...yyy...grr...ggr...yyy...rrg..yrggy.&steps=gryrgr&goal=0_0_5_0_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_g.r...rrg...rgg...yyy...grr...ggr...yyy...rrg..yrggy.&steps=yrgrgr&goal=0_0_4_0_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_rygg..rryg..gyrr..ggyr..rygg..rryg.&steps=gyrygr&goal=0_0_5_1_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_yrrr..gggy..yrrr..gggy..yrrr..yhhy.&steps=gyryrg&goal=2_0_7_0_"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_y..y..rrgg..hyyy..rrgg..yyyh.rrrggg&steps=gyryrg&goal=_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_y.....y..gyrr..ggyr..rygg.hrrygh&steps=rygyrg&goal=0_0_4_0_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_rggg..hyyy..rrrg..yyyh.rrrggg&steps=gyrygy&goal=0_0_4_1_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_h.....h...bhyy..bbrh..yyrr..rbbb..rryy..yyrr..bbbr.&steps=ybrbyrrb&goal=0_0_6_0_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_byyr..bbrr..yrby..hooh..yrby..bbrr.hbyyrhrrrbbb&steps=byyryb&goal=_0"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_bb.r.rgg.yygry.yrryr.rggrg.gbgrb.brrgb.bbrbr.grbrygrgryybybrrgrgrbrggrrbryyygg&steps=gygyybyb&goal=0_0_19_0_"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_rrbr..ryrr..ybyy..yyry..brbb..bbyb..yyry..ybyy.rrrbbb&steps=rbryyb&goal=0_0_7_0_"
creators = "iso"
source = "X"

[[entries]]
query = "field=0_bb....brr..yybr..ybyb..byby..rbbrr.rrory&steps=yrbrbr&goal=0_0_7_0_0"
creators = "iso"
source = "X"
