[[entries]]
id = 1923
query = "field=0_g..r..g..g..h..g..g.hr..rrgg..rhog..ggrr..orhg..rrggrggghrr&steps=rgrrrgrg&goal=0_0_7_0_"
creators = "可憐な私(笑)"
source = "X"
sourceDetail = "なぞぷよ大会没問"

[[entries]]
id = 1924
query = "field=0_g..r..g..g..h..g..g.hr..rrgg..rhog..ggrr..orhg..rrggrggghrr&steps=rgrrrgrg&goal=0_0_8_0_"
creators = "可憐な私(笑)"
source = "X"
sourceDetail = "なぞぷよ大会没問"

[[entries]]
id = 1925
query = "field=0_r.....r.....yb...rbr...rbby..ryry..bbrr..rbyb.rryybbhhhhhh&steps=bryryrbr&goal=0_0_7_1_"
creators = "可憐な私(笑)"
source = "X"
sourceDetail = "なぞぷよ大会没問"

[[entries]]
id = 1926
query = "field=0_y.....b.....rbr...bry...rbbr..ryry..bbrr..rbyb.rryybbhhhhhh&steps=bryryrbr&goal=0_0_5_0_0"
creators = "可憐な私(笑)"
source = "X"
sourceDetail = "なぞぷよ大会没問"

[[entries]]
id = 1927
query = "field=0_b.....o.....b.....p.o...bby...hopy.pbppb.pbbhypphyyppyphphy&steps=ybpypypb&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "X"
sourceDetail = "なぞぷよ大会没問"

[[entries]]
id = 1928
query = "field=0_r.....ry....ygg..rrgr..rhhg..yrgy..hyyh..ggrr..grgr..rrgg.hhyhyh&steps=yrygyrgryrgr&goal=0_0_6_1_2"
creators = "可憐な私(笑)"
source = "X"
sourceDetail = "なぞぷよ大会没問"
