[[entries]]
query = "field=0_o.....o.....o.....o.....o.....o.....o.....o.....o...oooooo&steps=rrrrrrrrrrrr&goal=_1"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_b....gg....gbb..bbggg.&steps=bbggbg&goal=0_0_4_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_y....bbb..bgggb.bbybb.&steps=gybybb&goal=0_0_5_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_grgr.rggyb.yoybb.&steps=ybybybybyb&goal=0_0_5_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_b.....b...ppy.ypbpybbppby&steps=pybybypy&goal=0_0_6_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_b...bbpb..ppgp.bpygp.pyygpboooooo&steps=bybgbp&goal=0_0_6_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_g.....b....gy..ybbg..byyg.gbgyg.ggygbgyyggbb&steps=ybgb&goal=0_0_7_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_rr....bb....bgb...ggrr..&steps=ybgbybybyb&goal=0_0_5_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_r....yy....bb....bg....ggyy..&steps=ybybybybgb&goal=0_0_5_0_"
creators = "けんろう"
source = "X"
sourceDetail = "早大没問"
