[[entries]]
id = 1938
query = "field=0_y..y..y..y..ry.ry.ry.ry.yr.yr.yr.yr.by.by.by.by.rb.rb.rr.rr.&steps=brbbbbbbbbbr&goal=0_0_12_0_"
creators = "live"
source = "X"

[[entries]]
id = 1939
query = "field=0_o....op....pp....py....yy.oo.yrpooprrgoogr&steps=ryrypgpgryry&goal=0_0_7_0_"
creators = "live"
source = "X"

[[entries]]
id = 1940
query = "field=0_y.....r.....r.....r..y..y..ry.yr.rr.rrypp.pyyprrprr&steps=yyyryrpr&goal=2_0_17_0_"
creators = "live"
source = "X"

[[entries]]
id = 1941
query = "field=0_rgrg..grgr..rgrg.ygrgr.yyobbb&steps=ybgrgggrgrgggr&goal=0_0_9_0_"
creators = "live"
source = "X"

[[entries]]
id = 1942
query = "field=0_b....pp..ybpr.brybp.pbyby.ybbbyyrry&steps=prbrypybrbrypy&goal=0_0_10_0_"
creators = "live"
source = "X"

[[entries]]
id = 1943
query = "field=0_o....ooo...obo...rpr...rgr...bgp...ogo...oro..bbrpp.borop.ogggoo&steps=pbrgrrbbgprrpb&goal=1_0_3_0_"
creators = "live"
source = "X"

[[entries]]
id = 1944
query = "field=0_o.g.g.g.o.g.gpgpo.gpopg.oygyg.gyoyg.gygyo&steps=ygppggppggyg&goal=0_0_9_0_"
creators = "live"
source = "X"

[[entries]]
id = 1945
query = "field=0_pg...pbgg.pgbby.bggyygbbygbggyybb&steps=bggygbybgpgg&goal=0_0_10_0_"
creators = "live"
source = "X"

[[entries]]
id = 1946
query = "field=0_g.....pp..b.bbrbb.brgrr.pppggg&steps=rrrpbrppgggb&goal=0_0_8_0_"
creators = "live"
source = "X"

[[entries]]
id = 1947
query = "field=0_b.....p.....pbr...bpp...pbb...ppr...brr...ppp..&steps=bbbrrrbbbrpp&goal=0_0_8_0_"
creators = "live"
source = "X"

[[entries]]
id = 1948
query = "field=0_g....gr...gyyo..rroo.yyooo.rooog&steps=ryrrryryrrry&goal=0_0_6_0_"
creators = "live"
source = "X"

[[entries]]
id = 1949
query = "field=0_rg....gr....pp....rg...rrgg..ggrr..pgrp.&steps=grrppgrpgrpg&goal=0_0_8_0_"
creators = "live"
source = "X"

[[entries]]
id = 1950
query = "field=0_orrb..orby..ooyb..yoyb..boob..byoy..byoo..ybro..brro.&steps=ryybyyrb&goal=_0"
creators = "live"
source = "X"

[[entries]]
id = 1951
query = "field=0_rrr...ogo...oog...ogo...goo...ogo...oog...ogo...goo..rogorg&steps=ggrrrrgggrgrgr&goal=0_0_7_0_"
creators = "live"
source = "X"

[[entries]]
id = 1952
query = "field=0_ppgo..ogoo..oogo..ppog..gopp..ogoo..oogo..ogpp.&steps=rgbgbprppppbpgbrgrpp&goal=0_0_9_0_"
creators = "live"
source = "X"

[[entries]]
id = 1953
query = "field=0_gop..yoop..oooo..oooy..oogoyobbgoooboooggoppogoogpbboygyboppyy&steps=ggpyyypggbybpypp&goal=0_0_11_0_"
creators = "live"
source = "X"
