[[entries]]
query = "field=0_brr..bbyry.ryygyyrrgg&steps=rbygry&goal=0_0_6_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_bg....bg....bgryyyryrgggryrbbbry&steps=ryrybgbg&goal=0_0_8_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_r.....b.....g.....g.....g.....b.....b....gb..bggrgbgbbrrggbg&steps=rrrrgbrgbbbg&goal=0_0_8_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_ryyyrgrgggrgrbbbrg&steps=rbbgbrbgby&goal=0_0_7_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_gb..yyygb.gggrrr&steps=ygbbggrg&goal=0_0_5_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_gb..yyygb.gggrrr&steps=ygbbggry&goal=0_0_5_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_gb..yyygb.gggyyy&steps=ygbbggyy&goal=0_0_5_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_oo...oyy...yoooo.yoyyo.yooyo.ryyor.rooor.roror.ororo.&steps=yyyryryryy&goal=0_0_7_0_1"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_g.ooogg.roooo.rrooy.gooyy.ggoor.royrr.rryyggggogg&steps=grgryrgygg&goal=0_0_9_0_1"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_bbrrggbrggrgyrbbryyyrryy&steps=bygbggby&goal=0_0_8_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_g.....rr....ry....yybbrrgrgrbrggrggbrrgbbr&steps=ryyybyby&goal=0_0_9_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_y...oyyb..gyybbggyrggrrbrrgrbb&steps=rggbbyry&goal=0_0_8_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_ybrgbggggbggyybrbbbybrrb&steps=bbyygyby&goal=0_0_8_0_"
creators = "OMR"
source = "X"

[[entries]]
query = "field=0_rryb..rbyy..ybbr..yyrr..&steps=rybybbrb&goal=0_0_6_0_"
creators = "OMR"
source = "X"
