[[entries]]
query = "field=0_p.....op....pp...ggo...gppp.&steps=gp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第1問"

[[entries]]
query = "field=0_b.....o.....bbr.bbobr.&steps=rbrb&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第9問"

[[entries]]
query = "field=0_o..o..po.g..pg.ggopggppp&steps=gpgp&goal=1_0_2_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2025"
sourceDetail = "第17問"
