[[entries]]
query = "field=0_orro..grgg..ggrg..orro.&steps=grgr&goal=0_0_4_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_o.....o....rr...grgg..ggrg..orro.&steps=grgr&goal=0_0_4_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_y...bbb...ooo...bbby.yyyooy&steps=byby&goal=0_0_4_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_r.o...brb...bbr...rrgg..rgrrr&steps=bbrrgbrb&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_brb...bbrr..rrgg..rgrrr&steps=brbgbrbr&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_r.....brb...bbr...rrgg..rgrrr&steps=bbbrgbrr&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_r.....brb...bbr...rrgg..rgrrr&steps=rrbbgbbr&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_r...brr...bbgr..rrgo..rgrrr&steps=rbgggggr&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_b...rbrr.gggbrgorrbgg&steps=brbgbgbr&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_b...rbrr.gggbrgorrbgg&steps=bbrbgbgr&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_b...rbrr.gggbrgorrbgg&steps=gbrrbbgb&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_bbrgrgbrbrrgrrggg&steps=rgbbbgbg&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_g.....g...rrbr..gbgr.rgrrg.rgrgg.rooooo&steps=gbgrgbgr&goal=0_0_7_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_g.....rgg...rbbr..rgbg..grrg..ggrg.ooooo.&steps=rrbgrrgr&goal=0_0_7_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_g.r...rbr...gbgr.rgrrg.rgrgg.rooooo&steps=gbgrgbgr&goal=0_0_7_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_o....gg...rrb...gbgr.rgrrg.rgrgg.rooooo&steps=rgbbrgrg&goal=0_0_7_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_y...b.b...h.b...ybo..yhyb..yboy..bboyy&steps=yyybbbby&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_r.....or....rbb..ggbg..rrrg..obbg.&steps=rbrbgggb&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_r.....or....rbb..ggbg..rrrg..obbg.&steps=bgbrbgrg&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2018没問"

[[entries]]
query = "field=0_b.....by....gbb..gryy..rrby.&steps=ybybgygbyr&goal=0_0_6_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2019没問"

[[entries]]
query = "field=0_bbrrrbrbgybbrggyyrryyggrbbygbrbrrrbb&steps=yrbgrgyrbbryrb&goal=0_0_12_0_0"
creators = "π"
source = "X"
sourceDetail = "早大没問"

[[entries]]
query = "field=0_rp....pprr..roor..rppp.&steps=prpr&goal=0_0_4_0_"
creators = "π"
source = "ぷよぷよキャンプ"
sourceDetail = "早大2019めざまし問題"

[[entries]]
query = "field=0_yb....by.b..oo.b..ooyoooooooooyoooooyyoooo&steps=brbyrrbybr&goal=0_0_5_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_p....prp...bpb..obpb..ooooo.&steps=rbrprbpbpb&goal=0_0_5_0_0"
creators = "π"
source = "X"

[[entries]]
query = "field=0_o....oo....ooo...ooo...oooo..oooo..ooooo.ooooo.ooooooo&steps=ryrrbbbbbbbbryyy&goal=0_0_4_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_o....ob....bb....bo....ob....bb....bo....bb....ob....bo....bb.bo.oboog.bbogbgb&steps=bbbbbbbb&goal=0_0_2_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_bybyy.bgrbb.grory.gbrgg.ybbyg.yygyb.&steps=bggyyb&goal=_1"
creators = "π"
source = "X"

[[entries]]
query = "field=0_rrr...ggg...brb...brb...brb...ggg..&steps=bgbgrr&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_rrby..rbyy..brro..yyrb..yobb.&steps=byrbyr&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_rrby..rbyy..brro..yyrb..yobb.&steps=byyrrb&goal=0_0_5_0_0"
creators = "π"
source = "X"

[[entries]]
query = "field=0_b.g...rrr...ggg...brb...brb...brb...ggg..&steps=rbrg&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_bg....rr...ggbh..rrro..ogbo..rgbg..grrr.&steps=grgrgggr&goal=0_0_7_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_b.r...r.r...b.b...r.b..&steps=brrrbbrb&goal=0_0_4_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_r.b...r.r...b.b...r.b..&steps=rbbbrrrb&goal=0_0_4_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_by....oo....oo..r.oo.g&steps=brbgrybygyrg&goal=0_0_4_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_g.....gg....bo...gbbrb.ggrrb&steps=brbgbg&goal=0_0_5_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_bbbyy.ooooy.yyybb.oooyb.bbbyy&steps=ybybyb&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_r.....r.....bbo...brb...oorrr&steps=rrrbrbrbrb&goal=0_0_5_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_brbyrbbrbyrbbrbyrbybyrbrybyrbrybyrbrryrbryryrbryryrbry&steps=rbbyyrrbbyyr&goal=0_0_11_1_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_bbbyy.oorry.yyybb.orryb.bbbyy&steps=ybybyb&goal=0_0_6_1_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_oo...bbb...yoob..ooybb.oooyo.bbbyy&steps=ybbyyb&goal=0_0_5_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_b.....b.....r.....by....brr.y.oyr.yyobyy&steps=rbrbryrb&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_b.....b.....r.....bby...brr.y.oyr.yyooyy&steps=rbrbrryb&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_gbrr..rbbr..rrgg..gbgr..bbrro&steps=bbggrrgr&goal=0_0_7_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_o...b.h..gggr..rorr..rrbb.&steps=bbbrbgbr&goal=0_0_5_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_o.rr..goor..ggro..rrgo..roog..orgg..ogrr..goor..ggro..rrgo..roog..orgg.&steps=rgrg&goal=0_0_4_1_0"
creators = "π"
source = "X"

[[entries]]
query = "field=0_yyr...rygy.yrggryyyrroy&steps=yrgyyr&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_g..gbbg.rgybbbrbygbyybggggbrrrrgbyybrrbrgbbggrgybyyrbyhrrggh&steps=rybgrgygbybr&goal=_1"
creators = "π"
source = "X"

[[entries]]
query = "field=0_r....rg....go..grro..grgg..ogro..ogrr.&steps=grrrgggr&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_rr....rh....ororrrrhrr&steps=ryyyry&goal=0_0_4_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_g..g.gg..ggbb..rogrr.rrogr.&steps=rgbgrgbg&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_g..g.gg..ggbb..rogrr.rrogr.&steps=rgbgbgrg&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_g.....o..goog..ggog..rogrr.rrogr.&steps=rgggrg&goal=0_0_5_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_r..p..r.bp..ppbp..prboo&steps=rpbp&goal=0_0_4_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_yo...ybb...yyb...ooo.bbbyyy&steps=ybby&goal=0_0_4_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_r...r.b...r.r...b.o...b.r..&steps=rrbr&goal=_0"
creators = "π"
source = "X"

[[entries]]
query = "field=0_ggo...ogo..ybob.yygybboggyyo&steps=ybgbgbyb&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_ggo...ogo..ybob.yygybboggyyo&steps=ybgbybgb&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_ggo...ogo..ybob.yygybboggyyo&steps=gygbbbyb&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_ggo...ogo..ybob.yygybboggyyo&steps=gybbgbyb&goal=0_0_6_0_"
creators = "π"
source = "X"

[[entries]]
query = "field=0_r...r.pb..p.po..p.orr.rrbbr&steps=ppbppr&goal=0_0_5_0_"
creators = "π"
source = "X"
