[[entries]]
query = "field=0_r.....yyy...orr.y.oho.yyrrr.&steps=ryryry&goal=0_0_4_0_"
creators = "らねあ"
source = "ぷよぷよキャンプ"
sourceDetail = "カウンターなぞぷよ"

[[entries]]
query = "field=0_or....br....ro...bgrg..rrgg.&steps=bbgggrgr&goal=0_0_5_0_"
creators = "らねあ"
source = "ぷよぷよキャンプ"
sourceDetail = "カウンターなぞぷよ"

[[entries]]
query = "field=0_g..ry.gh.ry.rgygy.ryrgr.rgrgr.ggryr.&steps=ryrgryygyrygyr&goal=0_0_10_0_"
title = "廃ビル"
creators = "らねあ"
source = "ぷよぷよキャンプ"
sourceDetail = "カウンターなぞぷよ"

[[entries]]
query = "field=0_o.o...r.g...r.r...o.g...r.b...g.o...r.r..rgogr.&steps=grggbbgggrbrgr&goal=0_0_7_0_0"
title = "御柱"
creators = "らねあ"
source = "ぷよぷよキャンプ"
sourceDetail = "カウンターなぞぷよ"

[[entries]]
query = "field=0_ry...rryy.gggbbbyybgrrybbggroyyrrobbyrggbggbbgorgbyorrooyy&steps=gbyryrgbyrgb&goal=_0"
title = "陽明門"
creators = "らねあ"
source = "ぷよぷよキャンプ"
sourceDetail = "カウンターなぞぷよ"

[[entries]]
query = "field=0_o..o..ggyy..gbgy..bbgg..rryyo.ryryg.yyrrgg&steps=bbbrbbgryygrgrbryr&goal=0_0_11_1_0"
title = "キリマンジャロ"
creators = "らねあ"
source = "ぷよぷよキャンプ"
sourceDetail = "カウンターなぞぷよ"
