[[entries]]
query = "field=0_g.....g....ppp...rgy...rgy...rgy.&steps=gygprg&goal=0_6_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ1作目"

[[entries]]
query = "field=0_rg....gg....ry....ryy...rgg.&steps=gyyygygy&goal=0_6_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ2作目"

[[entries]]
query = "field=0_g....gr....yr....yyr..rggr.&steps=rgryggrg&goal=0_6_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ3作目"

[[entries]]
query = "field=0_rg....rg....rg....ppp...rgy..prgy..prgy.&steps=ypgprprg&goal=0_6_7_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ4作目"

[[entries]]
query = "field=0_g.....ry....gr....gr....grg.&steps=ggyyrrrrgy&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ5作目"

[[entries]]
query = "field=0_g.....y.....y.....y.....g.....y....ry....ry....rg..&steps=gggggyry&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ6作目"

[[entries]]
query = "field=0_gg..rryr..yryr..ggyr.&steps=yyryry&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ7作目"

[[entries]]
query = "field=0_y.....y.....g.....r.....r.....r.....g.....g.....y.....y....rggg.&steps=rrrgrg&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ8作目"

[[entries]]
query = "field=0_g....yyy...rgr...rgr...ryyr&steps=yyrgry&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ9作目"

[[entries]]
query = "field=0_ry....yg....yy....rg....rgg...ryy.&steps=gggygy&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ10作目"

[[entries]]
query = "field=0_g.....gg....ry...rry...ppyp.&steps=rryprrrg&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ11作目"

[[entries]]
query = "field=0_r.....r.....r.....yy....rg....rp...ggp..&steps=rygpyprr&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ12作目"

[[entries]]
query = "field=0_y.....gg....gyy...rryr..rggr&steps=rrggrg&goal=0_0_5_0_"
creators = "ROI_yas"
source = "X"
sourceDetail = "なぞぷよ15作目"
