[[entries]]
id = 2822
query = "field=0_bbgg..bgbb..rrgg..bbrr.&steps=rgrrgbrg&goal=0_0_6_0_"
creators = "せりー"
source = "X"

[[entries]]
id = 2823
query = "field=0_r.....r.....g....oo...orog..grrg..ggoog.&steps=gggrgrgr&goal=0_0_5_0_"
creators = "せりー"
source = "X"

[[entries]]
id = 2824
query = "field=0_ob....br....rb...rbb...ggr..rrgb.&steps=rbrbrg&goal=0_0_5_0_"
creators = "せりー"
source = "X"

[[entries]]
id = 2825
query = "field=0_g.....oggr..grro..rggr..grrg..oggoooooooo&steps=rrrrggrg&goal=0_0_6_0_"
creators = "せりー"
source = "X"

[[entries]]
id = 2826
query = "field=0_b....gg....gbb...ogb..rrrgggoooooo&steps=bbbrbg&goal=0_0_5_0_"
creators = "せりー"
source = "X"

[[entries]]
id = 2827
query = "field=0_y.....r....rgg...rrg...yyy...org..rrygg.&steps=yrygyg&goal=_0"
creators = "せりー"
source = "X"

[[entries]]
id = 2828
query = "field=0_rr.rb.gr.rbrrg.rooooo&steps=rbrgrgrb&goal=0_0_5_0_"
creators = "せりー"
source = "X"

[[entries]]
id = 2829
query = "field=0_o.....o.o..rrbb..orbo..roob..rrbb.oooooo&steps=rbrrrrrb&goal=0_0_5_0_"
creators = "せりー"
source = "X"
