[[entries]]
query = "field=0_p.....o.....o.....o..b..yyoo..ppoo..&steps=bybpby&goal=0_0_3_0_0"
creators = "ともろん"
source = "X"

[[entries]]
query = "field=0_o.....o.....o.....h.....r.....g.....bb....bg....gy..rogyorrorrybboryrrbo&steps=brrrbr&goal=0_0_7_0_0"
creators = "ともろん"
source = "X"

[[entries]]
query = "field=0_b.....gp....gb....bgg...bgp...&steps=pgpgpg&goal=0_0_4_0_2"
creators = "ともろん"
source = "X"
