[[entries]]
query = "field=0_g.b...b.g...bgb...oro..ggob..rbbr..rror.&steps=grbggr&goal=0_0_6_0_"
creators = ["mtsd", "なぞぷよジェネレータ君"]

[[entries]]
query = "field=0_b....rr....grg...bbrb..brog..orbg..ggoo.&steps=brgbrg&goal=0_0_6_0_"
creators = ["mtsd", "なぞぷよジェネレータ君"]

[[entries]]
query = "field=0_g.b...r.b...rrg...obb...ogob..orrb..ggrb.&steps=grrgbg&goal=0_0_6_0_"
creators = ["mtsd", "なぞぷよジェネレータ君"]

[[entries]]
query = "field=0_r.....b.....rr...brb...gbg..gbrg..grrb.&steps=gbgbgr&goal=0_0_6_0_"
creators = ["mtsd", "なぞぷよジェネレータ君"]

[[entries]]
query = "field=0_r...r.r...r.r...o.o...h.rr..rrho..rorr..hooh..rror..hhhr..rorh.&steps=rrrrrr&goal=2_0_4_0_"
creators = ["mtsd", "なぞぷよジェネレータ君"]

[[entries]]
query = "field=0_r.....r.r...r.r...o.o...r.r...o.r...hrh...oorr..rhrh..orhr..orro..rhhh.&steps=rrrrrr&goal=2_0_4_0_"
creators = ["mtsd", "なぞぷよジェネレータ君"]

[[entries]]
query = "field=0_r.....r....roo...ror...orr..roho..rrhr..ohrr..rroh..hooh..orrr.&steps=rrrrrr&goal=2_0_4_0_"
creators = ["mtsd", "なぞぷよジェネレータ君"]

[[entries]]
query = "field=0_booob.bhohb.ooooo.bbobb.bbobb.yyyyy.rrorr.rohor.ooooo.rrror.rrorr.&steps=rbbbrbrb&goal=0_0_3_1_0"
creators = ["OrangeP", "π"]
source = "X"
sourceDetail = "令和記念なぞぷよ"
