source = "早大なぞぷよマスターズ2018"

[[entries]]
query = "field=0_ob....ob....obbbyyogbgryogggrrogbbggoybrrgoyyryyoyybbyorybggorrrrgor&steps=bgrgrybyybyrgrgb&goal=0_0_12_1_"
creators = ["OrangeP", "π"]
title = "究極虚数銀河"
sourceDetail = "第40問"
