source = "早大なぞぷよマスターズ2022"

[[entries]]
query = "field=0_&steps=o1_0_0_0_0_0oyyo0_1_0_1_0_1oyyo1_0_0_0_1_1oyyo0_1_0_0_1_1oyyo0_0_1_0_1_1oyy&goal=_0"
creators = "π"
title = "流れ星"
sourceDetail = "第30問"
