[[entries]]
id = 7
query = "field=0_y....rry...ryr...yrr..&steps=rr&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第1問"

[[entries]]
id = 8
query = "field=0_p.....g....pg.p.ppgpp.&steps=gp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第2問"

[[entries]]
id = 9
query = "field=0_yby.yybybbybbyyb&steps=by&goal=_0"
title = "だぁ"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第3問"

[[entries]]
id = 10
query = "field=0_p....pgpp..ppggp&steps=pg&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第4問"

[[entries]]
id = 11
query = "field=0_g.....g.....b....bb...rrgg..grbg..&steps=rg&goal=0_0_3_0_"
creators = "hides"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第5問"

[[entries]]
id = 12
query = "field=0_gbb..grgb.ggrgg.&steps=rgrb&goal=0_0_4_0_"
creators = "hides"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第6問"

[[entries]]
id = 13
query = "field=0_y..bybryybbybbyyyrbrr&steps=yb&goal=0_0_5_0_"
title = "4ダブ回避"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第7問"

[[entries]]
id = 14
query = "field=0_gr....gr...bbr...boo.&steps=bgrg&goal=0_0_3_0_"
title = "椅子"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第8問"

[[entries]]
id = 15
query = "field=0_gg...gpp...pgp..ppgg.&steps=pgpg&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第9問"

[[entries]]
id = 16
query = "field=0_y.....yy....rr.bb.rgggb&steps=gyrb&goal=0_0_4_0_"
creators = "shimogon"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第10問"

[[entries]]
id = 17
query = "field=0_brr...bbr...ryb...ryb...rybr.&steps=ybbr&goal=0_0_5_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第11問"

[[entries]]
id = 18
query = "field=0_y.....y.....p.y...ppyb..yybb..&steps=ybyp&goal=0_0_4_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第12問"

[[entries]]
id = 19
query = "field=0_r...rror..gggrr&steps=rgrg&goal=0_0_3_0_0"
creators = "hides"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第13問"

[[entries]]
id = 20
query = "field=0_y.y...ryrr.yyryy.rryrr.&steps=rryy&goal=_0"
creators = "yoshi"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第14問"

[[entries]]
id = 21
query = "field=0_by....bby...rry..oobb..oorboo&steps=rbyb&goal=0_0_4_0_0"
title = "アダムスミス"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第15問"

[[entries]]
id = 22
query = "field=0_rr....by....by....rr..&steps=yrbyrb&goal=_3"
title = "電池"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第16問"

[[entries]]
id = 23
query = "field=0_g....gg..ggppggpgpgpgppggpp&steps=pgpg&goal=0_0_4_1_0"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第17問"

[[entries]]
id = 24
query = "field=0_pp..b.pyyybbbbbppp&steps=bppybp&goal=0_0_5_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "第18問"

[[entries]]
id = 25
query = "field=0_gb....gb...rrgr..rbrr..ggbb..grrb.&steps=rgrbgb&goal=0_0_4_0_0"
creators = "hides"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第1問"

[[entries]]
id = 26
query = "field=0_yo....ro....rg.r..rryryyyyrggbbyyrrbyrgbgyyrrgbggggbbgy&steps=bgrbyr&goal=0_0_10_0_"
creators = "shimogon"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第2問"

[[entries]]
id = 27
query = "field=0_r..bbrr..brgbbbrr&steps=rgrgbgrb&goal=0_0_5_0_"
creators = "aojil"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第3問"

[[entries]]
id = 28
query = "field=0_bb...rrb.ybryybyybbybbgbrrgygyyrbgbyggbbrrrg&steps=yrgbyrgrgb&goal=0_0_12_0_0"
title = "宇宙訓練"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第4問"

[[entries]]
id = 29
query = "field=0_o.....ob...poo..obpbb.pooob.bpobp.ooppbppopbopbbbopoobpbbopppbpbbpopoboooopppo&steps=pbpbpbpb&goal=2_0_23_0_"
title = "宇宙万能説"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第5問"

[[entries]]
id = 30
query = "field=0_g.....r.....rg..bygg..grryo.rrrroogyygooyyyyoogbbgbogbggrybybbbryyrrrbbb&steps=yyrbgggy&goal=0_0_9_1_"
title = "カウンター"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第6問"

[[entries]]
id = 31
query = "field=0_byy.ggbbr.gyyyr.rrrgg&steps=yyrgrbrgyg&goal=0_3_7_0_"
title = "つよそう"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第7問"

[[entries]]
id = 32
query = "field=0_r.b...r.r...y.g...g.y...b.y...r.y...g.b...y.b...y.y...y.b...g.b...y.r..&steps=gbrgrryyggby&goal=0_0_9_0_"
title = "ツインタワー"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第8問"

[[entries]]
id = 33
query = "field=0_y.br.ybbrbrryobroyyobroyyobroybbrbrryobroy&steps=brryybbrryyb&goal=_2"
title = "︱‡‡︱"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第9問"

[[entries]]
id = 34
query = "field=0_rrbbbroooyyyrbbbrrooyyyobbbrrroyyyoobbrrro&steps=rbbyyrbyrb&goal=0_0_8_1_0"
title = "エスカレーター"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第10問"

[[entries]]
id = 35
query = "field=0_o....ogggyyyorrrbboogggboooyyyooorrroobbbgoyyyggbbbrrr&steps=yrgrgbybrbgy&goal=0_0_10_1_0"
creators = "shimogon"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第11問"

[[entries]]
id = 36
query = "field=0_b.r.b.r.y.y.b.b.r.&steps=brbryrbrbryr&goal=0_0_5_0_0"
title = "信号機"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第12問"

[[entries]]
id = 37
query = "field=0_gggbbryyrrbryggryrbgbyygbrbbggbrryyy&steps=rgbyrbrybgyg&goal=0_0_11_1_"
creators = "shimogon"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第13問"

[[entries]]
id = 38
query = "field=0_y.y.y.r.byy.ryrbb.oyyrb.gggrr.&steps=yrbbygyrbbyr&goal=0_0_8_0_0"
creators = "shimogon"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第14問"

[[entries]]
id = 39
query = "field=0_bbo..boob..ggyb.gobgo.rrygorogrooroyrooorrooooyoooo&steps=bgrgrgbgbbggbbrb&goal=0_0_8_0_"
title = "リング"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第15問"

[[entries]]
id = 40
query = "field=0_bbrr..yygg..rygb..yrbg..bbrr..yygg..oygo.rroobbrggyyb&steps=gbgyrygbyrrb&goal=0_0_7_1_0"
title = "聖杯"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第16問"

[[entries]]
id = 41
query = "field=0_go..rggo..rrbb..oggb..rgrr..rrbr..obbg..rrggboorobb&steps=gbrbgrgrgbrb&goal=0_0_9_1_2"
title = "プロミスリング"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第17問"

[[entries]]
id = 42
query = "field=0_rrybggryybbggbbrryggbryyyyrgbbyrrggbbggyyrbbgyrr&steps=yrbgygbgygbryrbr&goal=0_0_16_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "上級 第18問"

[[entries]]
id = 43
query = "field=0_h..o..h..o..h..o.rggrrgrrgrggggrgrrgrgrgrrgrgrgoggrrh&steps=rrgrgggr&goal=0_0_5_1_0"
title = "角刀牛虫(蟹)"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "おかわり 第1問"

[[entries]]
id = 44
query = "field=0_ggrr..ghor..yybb..yohb..rrgg..rhog..bbyy..obyo.rrohggrhoohg&steps=yrrgbybgrg&goal=0_0_6_1_0"
title = "初固"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "おかわり 第2問"

[[entries]]
id = 45
query = "field=0_bbhy..bhyy..gggr..hhrr..ybbb..yygg..rrrg..hhyy..bbyh.rrbhggrhhhhg&steps=brbygrgyrybg&goal=0_0_4_0_1"
title = "肩こり・改"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "おかわり 第3問"

[[entries]]
id = 46
query = "field=0_ooooo.rbrry.oboyo.oyobo.yoooby&steps=rrrbryyyybybrbyy&goal=0_0_7_0_"
title = "π"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "おかわり 第π問"

[[entries]]
id = 47
query = "field=0_h.h...b.y...y.b...o.r...r.o...y.b...o.r...b.y...r.h...b.r...y.b...r.y..&steps=rbbybrybrrbybyyr&goal=0_0_4_1_1"
title = "ツインタワー・邪"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "おかわり 第4問"

[[entries]]
id = 48
query = "field=0_brr...byg...rrr...gbb...gbg...ygr...ybr...ryb...rbr...ygr...rbg...brg...rrb&steps=gbrgrygrbbrgrybybb&goal=0_0_14_0_0"
title = "激辛ガエル"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "おかわり 第5問"

[[entries]]
id = 49
query = "field=0_o.oo.ooooorogooorogooorogobooooobooooobooyoooooyoooooy&steps=yrbbggyyrrbbggyyrrgb&goal=0_0_8_0_"
title = "滝登り"
creators = "π"
source = "早大なぞぷよマスターズ2017"
sourceDetail = "おかわり 第6問"
