[[entries]]
id = 1494
query = "field=0_gp...rgy...brp..&steps=ybbrrggppyyb&goal=0_0_5_0_"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120612a"

[[entries]]
id = 1495
query = "field=0_yryr..ryry..yryr..ryry..yryr.&steps=ybyrrbybyrrb&goal=2_2_15_0_"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120619a"

[[entries]]
id = 1496
query = "field=0_gp.r..ry.r..bp.byoooooo&steps=bbyyypggppgyrrbyyg&goal=0_0_6_0_1"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120701a"

[[entries]]
id = 1497
query = "field=0_y..r..hh.hh.&steps=yyryyyryry&goal=0_0_3_0_0"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120715a"

[[entries]]
id = 1498
query = "field=0_yhy...hhh...&steps=ryryyyryry&goal=0_0_3_0_0"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120715a"

[[entries]]
id = 1499
query = "field=0_y...r.hh.hh&steps=yyryyyryry&goal=0_0_3_0_0"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120715a"

[[entries]]
id = 1500
query = "field=0_y.hyh.hh&steps=ryryyyryry&goal=0_0_3_0_0"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120715a"

[[entries]]
id = 1501
query = "field=0_h.....hy...rryhr.hhrhh&steps=ryryyyryry&goal=0_0_4_0_0"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120715a"

[[entries]]
id = 1502
query = "field=0_gr..ggrrg.boooooo&steps=brgrgrgrbgbr&goal=0_0_5_0_0"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20120715a"

[[entries]]
id = 1503
query = "field=0_g.....g...ryy...gyr...yrg..rrgy..&steps=ryrgygrgyg&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20121219d"

[[entries]]
id = 1504
query = "field=0_y....grgbygybrygbybrgbrbbgbgbyyrybggygryrbybgbrbgrgyryggrryy&steps=ggryrbgrbgbrrrrbbbrg&goal=0_0_19_0_"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20130104a"

[[entries]]
id = 1505
query = "field=0_r....hh..h.hyh.&steps=yyyryyyryr&goal=0_0_3_0_0"
creators = "可憐な私(笑)"
source = "IPS投稿なぞぷよアーカイブ"
sourceDetail = "20161103a"
