[[entries]]
id = 2812
query = "field=0_y.....o.....o....go....yo..g.oo..oogo.oyrogoyyrroobb&steps=ygrryrybrggbrg&goal=0_3_7_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2813
query = "field=0_b.....bbrbryybbgrgyrrrgbbgggrgg&steps=rbyyrbbb&goal=0_0_8_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2814
query = "field=0_gg.gg.grrbgbbbbrbbrrrgrr&steps=rgrrrbgr&goal=0_0_7_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2815
query = "field=0_yybb..yrobg.orrgg.&steps=bbbgbryb&goal=0_0_5_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2816
query = "field=0_o...o.o...o.o...o.o...o.o...o.o.o.gyr.o.rry.o.rgr.oggrrbo&steps=gyggbbgybr&goal=0_0_6_0_0"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2817
query = "field=0_r.....bbr...bggyy.rrgry.&steps=rgrbry&goal=0_0_5_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2818
query = "field=0_gg.ggrrrbrgbggbrrbbgb&steps=grgrgbgb&goal=0_0_7_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2819
query = "field=0_yy....ygyrrgrggrggrryyrr&steps=rrgrygyr&goal=0_0_7_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2820
query = "field=0_g.....y....br....gr....gr.gybgb.ybbrgbbyryygyyyrgyyrryygg&steps=bb&goal=0_0_9_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"

[[entries]]
id = 2821
query = "field=0_gr..gbyy..byry..yyrr&steps=bybgyg&goal=0_0_5_0_"
creators = "SAKI"
source = "X"
sourceDetail = "即興なぞぷよ"
