[[entries]]
id = 234
query = "field=0_y.....yy....op....ypp...oyyy.&steps=py&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第1問"

[[entries]]
id = 235
query = "field=0_r....gg...rgrr..rror.&steps=gr&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第2問"

[[entries]]
id = 236
query = "field=0_o.....y.....y.....y....yo....bb....byyy.&steps=yb&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第3問"

[[entries]]
id = 237
query = "field=0_p.....p.....p.....g.....g.....p.....pp...pgog..gogg.&steps=gp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第4問"

[[entries]]
id = 238
query = "field=0_or....ro....rr....yy...roy.&steps=rrry&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第5問"

[[entries]]
id = 239
query = "field=0_o...o.g..gg.p..go.p..oogg.&steps=gpgp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第6問"

[[entries]]
id = 240
query = "field=0_y.....yo....yb.b..orrr.&steps=bybr&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第7問"

[[entries]]
id = 241
query = "field=0_b.....bb....gg....rg...roo&steps=rbrg&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第8問"

[[entries]]
id = 242
query = "field=0_o.....o.....yp....yy....pop..ppoo..&steps=pppy&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第9問"

[[entries]]
id = 243
query = "field=0_o.....g...o.rr..obgr..obbo&steps=gbgr&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第10問"

[[entries]]
id = 244
query = "field=0_o.o...y.o..yo.pp.rrrop.&steps=yryp&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第11問"

[[entries]]
id = 245
query = "field=0_g.....p.....o.....p....gog...gogg.&steps=gpgp&goal=0_0_3_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第12問"

[[entries]]
id = 246
query = "field=0_gg....go....po....pg...ppggopp&steps=gpgp&goal=1_0_2_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第13問"

[[entries]]
id = 247
query = "field=3_~rpor...pp.....y.....y.....y&steps=ryrp&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第14問"

[[entries]]
id = 248
query = "field=3_~.gppp..ro....rr.....g&steps=gpgr&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第15問"

[[entries]]
id = 249
query = "field=0_yyyy..yoooo.r&steps=rryyry&goal=0_0_3_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第16問"

[[entries]]
id = 250
query = "field=0_g.....o....ggr...bor..gbbr..&steps=gbgggr&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第17問"

[[entries]]
id = 251
query = "field=0_b.b...g.b...ogg..gbbg.&steps=gbgbgb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第18問"

[[entries]]
id = 252
query = "field=0_y.....y.....o.....y.b...y.b.&steps=ybyyyb&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第19問"

[[entries]]
id = 253
query = "field=0_r....oo....or.g..orrg.&steps=rrrgrg&goal=0_0_3_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第20問"

[[entries]]
id = 254
query = "field=0_y.....y.....o.y...y.r...r.r...rry.&steps=yyrrry&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第21問"

[[entries]]
id = 255
query = "field=0_b.....o.....o...bby...byy...yoo..yyoo..&steps=ybbbyb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第22問"

[[entries]]
id = 256
query = "field=0_go....op....gg....gp..ppopp.&steps=gpgggp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第23問"

[[entries]]
id = 257
query = "field=0_b....rr....bb....bo...rrbb.&steps=rbrrrb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第24問"

[[entries]]
id = 258
query = "field=0_g.b...o.b...ogg...obb...ggg..&steps=bbgbgb&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第25問"

[[entries]]
id = 259
query = "field=0_y.....y.....o.....y.....pp....op....po...yoyy.&steps=yppppy&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第26問"

[[entries]]
id = 260
query = "field=0_b.....o...y.b...ybob..ooyb..yyoo.&steps=bybyby&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第27問"

[[entries]]
id = 261
query = "field=0_p..o..oppp..ggoo..gppg.&steps=gpgggp&goal=0_0_4_0_"
creators = "OrangeP"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第28問"

[[entries]]
id = 262
query = "field=0_r.....o....roy...ryr...ryr...ooy.&steps=ryyyry&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第29問"

[[entries]]
id = 263
query = "field=0_r.....g.....gg....pr....rp....rr....pp....por.&steps=rgpprp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第30問"

[[entries]]
id = 264
query = "field=3_~.ypor..oprr..y.yy....y&steps=ypyyrp&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第31問"

[[entries]]
id = 265
query = "field=3_~.yyr...rrg...oyo...r.r...r.....o.....o&steps=grggyr&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第32問"

[[entries]]
id = 266
query = "field=3_~.obr...bob...rrb...ror...obr...rg.....g&steps=brbgbg&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第33問"

[[entries]]
id = 267
query = "field=0_y.....o.....y..ybyy..yyoo.&steps=byyybyby&goal=0_0_4_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第34問"

[[entries]]
id = 268
query = "field=0_y.....y.....p.....y.....y.....prr...pop...yyo..&steps=yprpyprp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第35問"

[[entries]]
id = 269
query = "field=0_grg...grr...rgo...rrpp&steps=ggrggprp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第36問"

[[entries]]
id = 270
query = "field=0_b.....o.....b.....g.b...b.o...o.o...bbb..&steps=bgbbbgbg&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第37問"

[[entries]]
id = 271
query = "field=0_r...r.bb..y.ro..yooo.rrrbb.&steps=rbbbryby&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第38問"

[[entries]]
id = 272
query = "field=0_r.....g.....r.b...gbb...gog...rrr..&steps=ggrrrgbg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第39問"

[[entries]]
id = 273
query = "field=0_r.....p.....p..rr.rr.pp.ggr&steps=prgrppgp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第40問"

[[entries]]
id = 274
query = "field=0_yy....oo....yr....oo...yyry..yrry.&steps=ryyyrrry&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第41問"

[[entries]]
id = 275
query = "field=0_g...pgg...oor..popp.rrrpo.&steps=rprgrprp&goal=0_0_5_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第42問"

[[entries]]
id = 276
query = "field=0_yy....ppy...orr...oooy..prry.oppry.&steps=yppprrry&goal=0_0_6_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第43問"

[[entries]]
id = 277
query = "field=0_b....br....br...yrbr..yorr..&steps=byrrbbby&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第44問"

[[entries]]
id = 278
query = "field=0_r.....pg....pr....oo....rr....rp....porr&steps=rpggppgp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第45問"

[[entries]]
id = 279
query = "field=0_y.....y.....bb....yy....oo..yyoobb&steps=ybybybyyyb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第46問"

[[entries]]
id = 280
query = "field=0_o.....r.....or..y.yr..y.oy..ggoy.&steps=gyrryyrrrg&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第47問"

[[entries]]
id = 281
query = "field=0_b.o...g.b..rb.o..rrbbb&steps=gbrgrgrrrb&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第48問"

[[entries]]
id = 282
query = "field=0_g.....r..r..o..o..g..o..rggp.&steps=gprgprrrgrgp&goal=0_0_5_0_"
creators = "π"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第49問"

[[entries]]
id = 283
query = "field=3_~.y..rg.r&steps=gggyrgggygry&goal=0_0_4_0_"
creators = "Pon!通"
source = "早大なぞぷよマスターズ2024"
sourceDetail = "第50問"
