[[entries]]
id = 822
query = "field=0_o..o..o..o..o..o..o..o..o..o.yyyrrrrrryyy&steps=bbrybbry&goal=0_0_5_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第1問"

[[entries]]
id = 823
query = "field=0_b.b..gg.gggrrrbbbgggyyy&steps=rbgbyb&goal=0_0_6_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第2問"

[[entries]]
id = 824
query = "field=0_y.....y.....y.....b.....b.....by....gg...gbr...ybry..yggr..ygrr&steps=gygyyy&goal=0_3_7_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Easy+ 第3問"

[[entries]]
id = 825
query = "field=0_g.r...r.g...ryy...gyr..rrggg.ryrrr.&steps=rgrg&goal=0_3_6_0_"
creators = "凸凹マスター"
source = "戦技研HP"
sourceDetail = "Easy+ 第4問"

[[entries]]
id = 826
query = "field=0_br....bobr.rrror.ooobbb&steps=rbrb&goal=0_0_4_0_"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Easy+ 第5問"

[[entries]]
id = 827
query = "field=0_bbbrrrooooooyyygggoooooorrrbbbooo&steps=rgbyrb&goal=0_2_6_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Easy+ 第6問"

[[entries]]
id = 828
query = "field=0_y...ryy...rbry..byyrr.byryy.&steps=ybrryy&goal=0_0_6_0_"
creators = "シレスト"
source = "戦技研HP"
sourceDetail = "Easy+ 第7問"

[[entries]]
id = 829
query = "field=0_br....rg....rb....br....brb...ggg...brr...bbr...ggbb..grrb..&steps=rgrb&goal=0_0_8_0_"
creators = "igo"
source = "戦技研HP"
sourceDetail = "Easy+ 第8問"

[[entries]]
id = 830
query = "field=0_r..r..r..r..grrb..ggbb..&steps=grbr&goal=_2"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第9問"

[[entries]]
id = 831
query = "field=0_y.....gb...rbb...yyy...gbbygrgrygrrgrrygg&steps=ryrb&goal=0_0_7_0_"
creators = "sky"
source = "戦技研HP"
sourceDetail = "Easy+ 第10問"

[[entries]]
id = 832
query = "field=0_r.....y.g...y.bg..y.gbb.rrrggg&steps=bgyg&goal=0_0_5_0_"
creators = "sky"
source = "戦技研HP"
sourceDetail = "Easy+ 第11問"

[[entries]]
id = 833
query = "field=0_r.....go.g.ggoorybrrgoobrrroobrggyyoo&steps=bgyg&goal=0_0_6_0_"
creators = "sky"
source = "戦技研HP"
sourceDetail = "Easy+ 第12問"

[[entries]]
id = 834
query = "field=0_y.....b....bb....ry..b.yy..ggrrybgyrbbbygybyrygybyyrygyrrygyb&steps=bygb&goal=0_0_11_0_"
creators = "シュレディンガー"
source = "戦技研HP"
sourceDetail = "Easy+ 第13問"

[[entries]]
id = 835
query = "field=0_y....ggb...bby...yygb.rrrbb&steps=bgbr&goal=0_2_5_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Easy+ 第14問"

[[entries]]
id = 836
query = "field=0_g.r...rrg...rgr...grg...rgr...rgrg..&steps=grgggr&goal=0_2_6_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Easy+ 第15問"

[[entries]]
id = 837
query = "field=0_gbb...ggr.byrrgbyygrggbb&steps=bggrby&goal=0_0_6_0_"
creators = "ねるん"
source = "戦技研HP"
sourceDetail = "Easy+ 第16問"

[[entries]]
id = 838
query = "field=0_gg....yy....gy....gg..ryyr..grrg.rgrggrrryyrr&steps=ggry&goal=_2"
creators = "any"
source = "戦技研HP"
sourceDetail = "Easy+ 第17問"

[[entries]]
id = 839
query = "field=0_b...rgrb..rrgy..ggrr..bbbr.&steps=bbbr&goal=0_0_5_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第18問"

[[entries]]
id = 840
query = "field=0_r....goy...gry...goy...yrg...yog...yrg..&steps=gygy&goal=0_0_5_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第19問"

[[entries]]
id = 841
query = "field=0_g.....g....go....go....oo....yo....yog...ygg..&steps=ygyyyy&goal=0_0_4_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第20問"

[[entries]]
id = 842
query = "field=0_r....yr....ro....roy...ooy...yoy...yrg...ygg.&steps=ygyg&goal=0_0_4_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第21問"

[[entries]]
id = 843
query = "field=0_yr....ry...ryr...yorroyyoooo&steps=ryry&goal=_0"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Easy+ 第22問"

[[entries]]
id = 844
query = "field=0_b.....r.....ry....rb....gb....yb.b.pyryr.yygyrggbgbbrrrgbpggryyppyrbbbyy&steps=yyry&goal=0_0_11_0_"
creators = "わんりゅう"
source = "戦技研HP"
sourceDetail = "Easy+ 第23問"

[[entries]]
id = 845
query = "field=0_b....byy..yyyr..rybbggbbrbrrbr&steps=rrggyy&goal=_2"
creators = "みそしる"
source = "戦技研HP"
sourceDetail = "Easy+ 第24問"

[[entries]]
id = 846
query = "field=0_r.....g..g..g..byyrrrbygggbbrrrybgggyyb&steps=rbybyb&goal=0_0_8_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Easy+ 第25問"

[[entries]]
id = 847
query = "field=0_b.....p....pp...rry...yryoooooooooooooooobo&steps=ybpbbr&goal=0_0_4_0_"
creators = "じんじょ"
source = "戦技研HP"
sourceDetail = "Easy+ 第26問"

[[entries]]
id = 848
query = "field=0_yb.by.yy.yy.bb.bb.by.by.yy.yy.&steps=ybyb&goal=2_2_12_0_"
creators = "きゅい"
source = "戦技研HP"
sourceDetail = "Easy+ 第27問"

[[entries]]
id = 849
query = "field=0_br.r..bbrbr.rrbbrr&steps=brrrrb&goal=0_2_5_0_"
creators = "anagura"
source = "戦技研HP"
sourceDetail = "Easy+ 第28問"

[[entries]]
id = 850
query = "field=0_b..r..y..y..yrby.bbbrrrgggbbb&steps=gygyyy&goal=0_0_6_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Easy+ 第29問"

[[entries]]
id = 851
query = "field=0_rro...obb...ggo...yyy...rgb&steps=ggbbrryy&goal=0_0_4_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Easy+ 第30問"

[[entries]]
id = 852
query = "field=0_bb....byb.gyggg.yyyyy.gg&steps=rbgrrrgy&goal=0_0_6_0_"
creators = "ワタリ"
source = "戦技研HP"
sourceDetail = "Easy+ 第31問"

[[entries]]
id = 853
query = "field=0_g....bgg...bbr...rgr...rgrb.brgbo.&steps=rggbrb&goal=0_0_6_0_"
creators = "じんじょ"
source = "戦技研HP"
sourceDetail = "Easy+ 第32問"

[[entries]]
id = 854
query = "field=0_o.b...o.b...o.b.o.o.ooo.r.rro.r.oor.rborobobooobrborob&steps=brbrbr&goal=_0"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Easy+ 第36問"

[[entries]]
id = 855
query = "field=0_gg..ryyyryyrrryy&steps=grrrgy&goal=0_0_5_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Easy+ 第37問"

[[entries]]
id = 856
query = "field=0_yybb.ryyrbryryrryyr&steps=yyyryb&goal=0_0_6_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Easy+ 第38問"

[[entries]]
id = 857
query = "field=0_r...g.ryb.g.oyb&steps=ygbrgbry&goal=1_0_3_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Easy+ 第39問"

[[entries]]
id = 858
query = "field=0_bb..ooogg.orrrg&steps=bgbr&goal=0_0_3_0_0"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Easy+ 第40問"

[[entries]]
id = 859
query = "field=0_ggr...grr...rgg...rrg...ggr...grr...rgg...rrg..&steps=rgrg&goal=0_0_5_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Easy+ 第41問"

[[entries]]
id = 860
query = "field=0_b..r..b..r..r..b..r..b.&steps=rbrbrbrb&goal=0_0_4_0_"
creators = "qwer"
source = "戦技研HP"
sourceDetail = "Easy+ 第42問"

[[entries]]
id = 861
query = "field=0_bbyy.gbggygggrrgg&steps=rrbgyg&goal=0_0_5_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Easy+ 第43問"

[[entries]]
id = 862
query = "field=0_b.pb..ybpbbyyypoyy&steps=bpbyby&goal=0_0_5_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Easy+ 第44問"

[[entries]]
id = 863
query = "field=0_brr.g.byyyg.&steps=yggrrbby&goal=0_0_4_0_"
creators = "けんろう"
source = "戦技研HP"
sourceDetail = "Easy+ 第45問"

[[entries]]
id = 864
query = "field=0_r.bo.or.byooroorryooyrgrbyyggbb&steps=yyrbygbb&goal=0_0_7_0_"
creators = "すぴぃちゃん"
source = "戦技研HP"
sourceDetail = "Easy+ 第46問"

[[entries]]
id = 865
query = "field=0_rrb...ybr...brr...yyy.&steps=rrrb&goal=0_0_4_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Easy+ 第47問"

[[entries]]
id = 866
query = "field=0_r.bbb.gggrrrrrrggg&steps=gbgr&goal=0_0_5_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Easy+ 第48問"

[[entries]]
id = 867
query = "field=0_r.....rr..rybby.yygbyyrrrggg&steps=yryb&goal=0_0_6_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Easy+ 第49問"

[[entries]]
id = 868
query = "field=0_rr....bb...rrrg..bbyg..rryy..&steps=rgyg&goal=0_0_5_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Easy+ 第50問"

[[entries]]
id = 869
query = "field=0_bb....rb....rr....yyo...oyo...ggg..&steps=bryg&goal=0_0_4_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Easy+ 第51問"

[[entries]]
id = 870
query = "field=0_gr...rrg..grbb.rggbgrr&steps=ggrb&goal=0_0_5_0_"
creators = "h!de"
source = "戦技研HP"
sourceDetail = "Easy+ 第52問"

[[entries]]
id = 871
query = "field=0_yy..rryr..ryrr..yy&steps=yryryr&goal=2_0_13_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Easy+ 第53問"

[[entries]]
id = 872
query = "field=0_r.....rr...ggy..rbry..rrbb..&steps=ybygrg&goal=0_0_5_0_"
creators = "platinum"
source = "戦技研HP"
sourceDetail = "Easy+ 第54問"

[[entries]]
id = 873
query = "field=0_y..b.bbyyoyyobbb&steps=yybbyb&goal=0_0_4_0_"
creators = "aojil"
source = "戦技研HP"
sourceDetail = "Easy+ 第55問"
