[[entries]]
id = 697
query = "field=0_b..rgbrg.rgbrg.rgbrg&steps=grgr&goal=0_0_5_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題1"

[[entries]]
id = 698
query = "field=0_r.....gb....rgbgb.rgbgb.rgbgb&steps=ggbbgb&goal=0_0_5_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題2"

[[entries]]
id = 699
query = "field=0_r...ygg.y.gbryb.rrgrygbrrygybbrrygygggygyggrrbgbrbyrbbgrbyrggrbyrggrbyrg&steps=bbybry&goal=0_0_18_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題3"

[[entries]]
id = 700
query = "field=0_y.r...y.rb.grgbbggbgryyrrbrbygrb&steps=yyggyb&goal=0_0_8_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題4"

[[entries]]
id = 701
query = "field=0_o..o..b..b..rr.ggbobbob&steps=rgrg&goal=_1"
creators = "PRRN"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題5"

[[entries]]
id = 702
query = "field=0_o.....oobo.bbb&steps=bbbb&goal=_1"
creators = "FELF"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題6"

[[entries]]
id = 703
query = "field=0_r.r.r.r.r.r.r.r.g.g.ggoooooorororororororororooboyop&steps=rgrg&goal=_1"
creators = "あすなろ"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題7"

[[entries]]
id = 704
query = "field=0_r...b.r...b.r...yrb.y.ybrbryrrbryyyyrbrr&steps=yyo3_3_3_3_3_3oybyr&goal=0_0_5_1_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題8"

[[entries]]
id = 705
query = "field=0_p.....y.....y.....y.....p.....y....yyp...ppy..&steps=pppy&goal=0_0_4_0_"
creators = "π"
source = "初春なぞぷよ大会2022"
sourceDetail = "甘口 問題9"

[[entries]]
id = 706
query = "field=0_r...r.g.r.bgogb.bbrbbgggorr&steps=bgrbgr&goal=0_0_6_0_"
creators = "PRRN"
source = "初春なぞぷよ大会2022"
sourceDetail = "中辛 問題1"

[[entries]]
id = 707
query = "field=0_r....rp.p..rr.r..pp.pp.pr.rr.rpprp&steps=prpppr&goal=_0"
creators = "FELF"
source = "初春なぞぷよ大会2022"
sourceDetail = "中辛 問題2"

[[entries]]
id = 708
query = "field=0_rrr...ggb...gbb...rrr...ggb...gbb...rrr...ggb..ogbbo.&steps=rggbbr&goal=_3"
creators = "あすなろ"
source = "初春なぞぷよ大会2022"
sourceDetail = "中辛 問題3"

[[entries]]
id = 709
query = "field=0_y.....y.....gy....gr..g.gr..g.yr..y.gg..gryy..rrgg.gooror&steps=yryggr&goal=0_0_6_0_"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "中辛 問題4"

[[entries]]
id = 710
query = "field=0_o.....b.....p.....o....ppp...ggo...ogb...bop...bbp..&steps=pbgbpb&goal=0_0_5_0_"
creators = "π"
source = "初春なぞぷよ大会2022"
sourceDetail = "中辛 問題5"

[[entries]]
id = 711
query = "field=0_r.....r.....g.....g.....o.....o.....r.y.rroyy.&steps=yrgrgr&goal=0_0_4_0_"
creators = "redeye"
source = "初春なぞぷよ大会2022"
sourceDetail = "中辛 問題6"

[[entries]]
id = 712
query = "field=0_gg...ror...gggo..bobr..rrbo..bogg.ggbbo.&steps=grbgrbgr&goal=_0"
creators = "PRRN"
source = "初春なぞぷよ大会2022"
sourceDetail = "激辛 問題1"

[[entries]]
id = 713
query = "field=0_ppoopppggbbpogbgboobgbgopbbggpppoopp&steps=gpgbbbgp&goal=_0"
creators = "FELF"
source = "初春なぞぷよ大会2022"
sourceDetail = "激辛 問題2"

[[entries]]
id = 714
query = "field=0_o.b...o.o...g.gb..rbor..rbor..gggrbb&steps=rggbbrrg&goal=0_3_5_0_"
creators = "あすなろ"
source = "初春なぞぷよ大会2022"
sourceDetail = "激辛 問題3"

[[entries]]
id = 715
query = "field=0_g...y.g..hrgy..ryhy..yygr..rrgg..gryr.ggygrrhhhhhh&steps=gryryggr&goal=0_0_6_0_0"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "激辛 問題4"

[[entries]]
id = 716
query = "field=0_g.....g.....rr...gor...bbg..rrgg..orobb.&steps=rbbbgrgb&goal=0_0_6_0_"
creators = "π"
source = "初春なぞぷよ大会2022"
sourceDetail = "激辛 問題5"

[[entries]]
id = 717
query = "field=0_y.....y.....b.....b.....o.....b.....r.....r.r...b.o...brr.&steps=brbyryrb&goal=0_0_5_0_"
creators = "redeye"
source = "初春なぞぷよ大会2022"
sourceDetail = "激辛 問題6"

[[entries]]
id = 718
query = "field=0_r.....o.....p.o...r.p.o.p.o.r.o.r.p.r.o.r.p.p.o&steps=rprrprrppppr&goal=0_0_6_0_"
creators = "PRRN"
source = "初春なぞぷよ大会2022"
sourceDetail = "殿堂 問題1"

[[entries]]
id = 719
query = "field=0_y.p..oo.oo.ooooo.rrorr.&steps=yrgpggypgryp&goal=_3"
creators = "FELF"
source = "初春なぞぷよ大会2022"
sourceDetail = "殿堂 問題2"

[[entries]]
id = 720
query = "field=0_rg....gb....by....yr....rg....gr..&steps=rggbbyyrrggr&goal=0_1_6_0_"
creators = "あすなろ"
source = "初春なぞぷよ大会2022"
sourceDetail = "殿堂 問題3"

[[entries]]
id = 721
query = "field=0_r.....gyr...grr...rgy..rhhg..yrgy..hyyh..ggrr..grgr..rrgg.hhyhyh&steps=yrygyrgryrgr&goal=0_0_8_1_1"
creators = "可憐な私(笑)"
source = "初春なぞぷよ大会2022"
sourceDetail = "殿堂 問題4"

[[entries]]
id = 722
query = "field=0_oby...oby...oby...orbggyorbgyyorbrggoggrrgoggbbyoggbyyoyrrobbyrgggby&steps=rgbgbryrygyb&goal=_0"
creators = "π"
source = "初春なぞぷよ大会2022"
sourceDetail = "殿堂 問題5"

[[entries]]
id = 723
query = "field=0_pgy...ppg...ggy...oooyyy&steps=ypgpypgggpyp&goal=1_0_3_0_"
creators = "redeye"
source = "初春なぞぷよ大会2022"
sourceDetail = "殿堂 問題6"
