[[entries]]
id = 2841
query = "field=0_y.....y.....oyy..yyrr.&steps=ryry&goal=0_0_3_0_"
creators = "redeye"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第1問"

[[entries]]
id = 2842
query = "field=0_r.r...r.r...y.o.y.o.y.o.ory.rroro.yyoyy.ooorrr&steps=rr&goal=0_0_5_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第2問"

[[entries]]
id = 2843
query = "field=0_g...ygr...rygr..rygr..rygr.&steps=yryr&goal=0_0_4_0_0"
creators = "可憐な私（笑）"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第3問"

[[entries]]
id = 2844
query = "field=0_rbb...rrb...bbr...brr..&steps=rbrb&goal=0_0_4_0_"
creators = "こいぬ"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第4問"

[[entries]]
id = 2845
query = "field=0_y....oo....yy....yo....oyy...oooo.ooyyy.&steps=yyyy&goal=0_0_3_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第5問"

[[entries]]
id = 2846
query = "field=0_y.....y.o...y.y..royrr.rroro.ooyyo.&steps=ryry&goal=0_0_4_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第6問"

[[entries]]
id = 2847
query = "field=0_rr...obr..rbby..rryy.&steps=byrr&goal=0_0_4_0_"
creators = "べ〜た"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第7問"

[[entries]]
id = 2848
query = "field=0_ggo...gby...oyy...obo...ggo...gby...oyy...obo..&steps=gygy&goal=0_0_5_0_"
creators = "PRRN"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第8問"

[[entries]]
id = 2849
query = "field=0_g.....g.....o.....g.....g.....g...p.o...pop.&steps=gggp&goal=0_0_3_0_"
creators = "OrangeP"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第9問"

[[entries]]
id = 2850
query = "field=0_go....gg....ppg.opopggpp&steps=gpgp&goal=1_0_2_0_"
creators = "OrangeP"
source = "新春なぞぷよ大会2026"
sourceDetail = "甘口 第10問"

[[entries]]
id = 2851
query = "field=0_y.....b.....bo...boo..yoby..yooyy&steps=bbybyb&goal=0_0_4_0_"
creators = "べ〜た"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第1問"

[[entries]]
id = 2852
query = "field=0_ggg.rgrorrrrgrorggrggg&steps=rgrg&goal=_0"
creators = "あやと"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第2問"

[[entries]]
id = 2853
query = "field=0_b.....oy...gby...ggo...ybg...ogg...ybo..&steps=gyyygy&goal=0_0_5_0_"
creators = "PRRN"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第3問"

[[entries]]
id = 2854
query = "field=0_r....ry....yo....yob...yrgb..prgb..&steps=pgppbg&goal=0_0_5_1_"
creators = "ちょにき"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第4問"

[[entries]]
id = 2855
query = "field=0_r.....g....gg....yr....ry...yrgg..ygry..ygry.&steps=gryryg&goal=0_0_4_0_0"
creators = "可憐な私（笑）"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第5問"

[[entries]]
id = 2856
query = "field=0_ry....ro....yo....yr....or....yo....rr....oo..&steps=yyryry&goal=0_0_4_0_"
creators = "redeye"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第6問"

[[entries]]
id = 2857
query = "field=0_bg...gyy..gbgy..yygb..yboy&steps=bgbgyg&goal=0_0_5_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第7問"

[[entries]]
id = 2858
query = "field=0_r.....r.....r.....g.....ro...&steps=rgrgrg&goal=_0"
creators = "あすなろ"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第8問"

[[entries]]
id = 2859
query = "field=0_y.....yr....gr....gg....rr.g..ryyg&steps=rgrgrg&goal=0_0_5_0_"
creators = "ロイ・ヤス"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第9問"

[[entries]]
id = 2860
query = "field=0_g.....g.....bb..g.ybygrgyggrrg&steps=gbbyrg&goal=0_0_5_1_"
creators = "こいぬ"
source = "新春なぞぷよ大会2026"
sourceDetail = "中辛 第10問"

[[entries]]
id = 2861
query = "field=0_ry....bg...yyo...gbgy..ggog..ybgy..yyog.rrbro.&steps=gyyygggy&goal=0_0_8_0_"
creators = "PRRN"
source = "新春なぞぷよ大会2026"
sourceDetail = "激辛 第1問"

[[entries]]
id = 2862
query = "field=0_o.....o.....y.p...y.g.gppyo.ggogo.yoopy.yyoyy.&steps=gypypgyg&goal=0_0_6_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2026"
sourceDetail = "激辛 第2問"

[[entries]]
id = 2863
query = "field=0_oo..o.or..roor..roor..roog..goor..ro&steps=rgrgggrg&goal=_0"
creators = "あすなろ"
source = "新春なぞぷよ大会2026"
sourceDetail = "激辛 第3問"

[[entries]]
id = 2864
query = "field=0_r.....o.....o.....y.....yo....or....oy....yo....rr....oo..&steps=ryrryyry&goal=0_0_4_0_"
creators = "redeye"
source = "新春なぞぷよ大会2026"
sourceDetail = "激辛 第4問"

[[entries]]
id = 2865
query = "field=0_y....ob...oyo...yyb..obbo.&steps=bbbybyyy&goal=0_0_4_0_"
creators = "べ〜た"
source = "新春なぞぷよ大会2026"
sourceDetail = "激辛 第5問"

[[entries]]
id = 2866
query = "field=0_y.....g.....r...o.r...yyg...oryg..ryyg.ygrgryyyrgyyoooooo&steps=grgrygyr&goal=0_0_4_0_0"
creators = "可憐な私（笑）"
source = "新春なぞぷよ大会2026"
sourceDetail = "激辛 第6問"

[[entries]]
id = 2867
query = "field=0_g.....o.....p.....g.....p.....og....ggp.&steps=gpppgpgp&goal=0_0_4_0_"
creators = "OrangeP"
source = "新春なぞぷよ大会2026"
sourceDetail = "激辛 第7問"

[[entries]]
id = 2868
query = "field=0_go...gby...oyy...gbg...ggo..yybyy.ggogg.oybyy.&steps=gyyygygggygy&goal=0_0_9_0_"
creators = "PRRN"
source = "新春なぞぷよ大会2026"
sourceDetail = "殿堂 第1問"

[[entries]]
id = 2869
query = "field=0_o..o..oooo..ybor..ybor..rooy..rryy.&steps=bbyrbbyrbrby&goal=0_0_6_0_"
creators = "べ〜た"
source = "新春なぞぷよ大会2026"
sourceDetail = "殿堂 第2問"

[[entries]]
id = 2870
query = "field=0_g.....o.....g....gr....ro....yr....ry....yo....gy..&steps=rygyryggrgry&goal=0_0_6_0_"
creators = "redeye"
source = "新春なぞぷよ大会2026"
sourceDetail = "殿堂 第3問"

[[entries]]
id = 2871
query = "field=0_r.....g.....yy....gr....rh..ryry..rygg..ghyr.ggyyrrhhhhhh&steps=rgyggrgyrygr&goal=0_0_4_0_0"
creators = "可憐な私（笑）"
source = "新春なぞぷよ大会2026"
sourceDetail = "殿堂 第4問"

[[entries]]
id = 2872
query = "field=0_og....oyg...ggy...yop...ypg...pyg..ogog..oyoyy.gopoy&steps=gggppyyyppgy&goal=0_0_8_0_0"
creators = "ことみ"
source = "新春なぞぷよ大会2026"
sourceDetail = "殿堂 第5問"

[[entries]]
id = 2873
query = "field=3_~.ggo...ogo...pop....pp....go&steps=gpgpgpgp&goal=0_0_4_0_"
creators = "OrangeP"
source = "新春なぞぷよ大会2026"
sourceDetail = "殿堂 第6問"
